/**
 * Generated by orval
 * Do not edit manually.
 */
import * as zod from 'zod';


/**
 * @summary Get list of topics
 */
export const getApiAlphaTopicListQueryIncludeCommunitiesDefault = true;

export const getApiAlphaTopicListQueryParams = zod.object({
  "include_communities": zod.boolean().default(getApiAlphaTopicListQueryIncludeCommunitiesDefault).describe('include list of communities in each topic with result')
})

export const getApiAlphaTopicListResponse = zod.object({
  "topics": zod.array(zod.object({
  "children": zod.array(zod.unknown()),
  "communities": zod.array(zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
})),
  "communities_count": zod.number(),
  "id": zod.number(),
  "name": zod.string(),
  "show_posts_from_children": zod.boolean(),
  "title": zod.string(),
  "parent_topic_id": zod.number().nullish()
}))
})

