/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type {
  CreatePrivateMessageRequest,
  DefaultError,
  DeletePrivateMessageRequest,
  EditPrivateMessageRequest,
  GetApiAlphaPrivateMessageConversationParams,
  GetApiAlphaPrivateMessageListParams,
  GetPrivateMessageConversationResponse,
  LeaveConversationRequest,
  ListPrivateMessagesResponse,
  MarkPrivateMessageAsReadRequest,
  PrivateMessageResponse,
  ReportPrivateMessageRequest,
  UnprocessableEntityResponse
} from '../../schemas';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary List private messages.
 */
export type getApiAlphaPrivateMessageListResponse200 = {
  data: ListPrivateMessagesResponse
  status: 200
}

export type getApiAlphaPrivateMessageListResponse400 = {
  data: DefaultError
  status: 400
}

export type getApiAlphaPrivateMessageListResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type getApiAlphaPrivateMessageListResponseSuccess = (getApiAlphaPrivateMessageListResponse200) & {
  headers: Headers;
};
export type getApiAlphaPrivateMessageListResponseError = (getApiAlphaPrivateMessageListResponse400 | getApiAlphaPrivateMessageListResponse422) & {
  headers: Headers;
};

export type getApiAlphaPrivateMessageListResponse = (getApiAlphaPrivateMessageListResponseSuccess | getApiAlphaPrivateMessageListResponseError)

export const getGetApiAlphaPrivateMessageListUrl = (params?: GetApiAlphaPrivateMessageListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/private_message/list?${stringifiedParams}` : `/api/alpha/private_message/list`
}

export const getApiAlphaPrivateMessageList = async (params?: GetApiAlphaPrivateMessageListParams, options?: RequestInit): Promise<getApiAlphaPrivateMessageListResponse> => {
  
  return customFetch<getApiAlphaPrivateMessageListResponse>(getGetApiAlphaPrivateMessageListUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get conversation with a specific person.
 */
export type getApiAlphaPrivateMessageConversationResponse200 = {
  data: GetPrivateMessageConversationResponse
  status: 200
}

export type getApiAlphaPrivateMessageConversationResponse400 = {
  data: DefaultError
  status: 400
}

export type getApiAlphaPrivateMessageConversationResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type getApiAlphaPrivateMessageConversationResponseSuccess = (getApiAlphaPrivateMessageConversationResponse200) & {
  headers: Headers;
};
export type getApiAlphaPrivateMessageConversationResponseError = (getApiAlphaPrivateMessageConversationResponse400 | getApiAlphaPrivateMessageConversationResponse422) & {
  headers: Headers;
};

export type getApiAlphaPrivateMessageConversationResponse = (getApiAlphaPrivateMessageConversationResponseSuccess | getApiAlphaPrivateMessageConversationResponseError)

export const getGetApiAlphaPrivateMessageConversationUrl = (params?: GetApiAlphaPrivateMessageConversationParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/private_message/conversation?${stringifiedParams}` : `/api/alpha/private_message/conversation`
}

export const getApiAlphaPrivateMessageConversation = async (params?: GetApiAlphaPrivateMessageConversationParams, options?: RequestInit): Promise<getApiAlphaPrivateMessageConversationResponse> => {
  
  return customFetch<getApiAlphaPrivateMessageConversationResponse>(getGetApiAlphaPrivateMessageConversationUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Leave a conversation
 */
export type postApiAlphaPrivateMessageConversationLeaveResponse200 = {
  data: void
  status: 200
}

export type postApiAlphaPrivateMessageConversationLeaveResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaPrivateMessageConversationLeaveResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaPrivateMessageConversationLeaveResponseSuccess = (postApiAlphaPrivateMessageConversationLeaveResponse200) & {
  headers: Headers;
};
export type postApiAlphaPrivateMessageConversationLeaveResponseError = (postApiAlphaPrivateMessageConversationLeaveResponse400 | postApiAlphaPrivateMessageConversationLeaveResponse422) & {
  headers: Headers;
};

export type postApiAlphaPrivateMessageConversationLeaveResponse = (postApiAlphaPrivateMessageConversationLeaveResponseSuccess | postApiAlphaPrivateMessageConversationLeaveResponseError)

export const getPostApiAlphaPrivateMessageConversationLeaveUrl = () => {


  

  return `/api/alpha/private_message/conversation/leave`
}

export const postApiAlphaPrivateMessageConversationLeave = async (leaveConversationRequest: LeaveConversationRequest, options?: RequestInit): Promise<postApiAlphaPrivateMessageConversationLeaveResponse> => {
  
  return customFetch<postApiAlphaPrivateMessageConversationLeaveResponse>(getPostApiAlphaPrivateMessageConversationLeaveUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      leaveConversationRequest,)
  }
);}


/**
 * @summary Create a new private message.
 */
export type postApiAlphaPrivateMessageResponse200 = {
  data: PrivateMessageResponse
  status: 200
}

export type postApiAlphaPrivateMessageResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaPrivateMessageResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type postApiAlphaPrivateMessageResponse429 = {
  data: DefaultError
  status: 429
}
    
export type postApiAlphaPrivateMessageResponseSuccess = (postApiAlphaPrivateMessageResponse200) & {
  headers: Headers;
};
export type postApiAlphaPrivateMessageResponseError = (postApiAlphaPrivateMessageResponse400 | postApiAlphaPrivateMessageResponse422 | postApiAlphaPrivateMessageResponse429) & {
  headers: Headers;
};

export type postApiAlphaPrivateMessageResponse = (postApiAlphaPrivateMessageResponseSuccess | postApiAlphaPrivateMessageResponseError)

export const getPostApiAlphaPrivateMessageUrl = () => {


  

  return `/api/alpha/private_message`
}

export const postApiAlphaPrivateMessage = async (createPrivateMessageRequest: CreatePrivateMessageRequest, options?: RequestInit): Promise<postApiAlphaPrivateMessageResponse> => {
  
  return customFetch<postApiAlphaPrivateMessageResponse>(getPostApiAlphaPrivateMessageUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPrivateMessageRequest,)
  }
);}


/**
 * @summary Edit a private message.
 */
export type putApiAlphaPrivateMessageResponse200 = {
  data: PrivateMessageResponse
  status: 200
}

export type putApiAlphaPrivateMessageResponse400 = {
  data: DefaultError
  status: 400
}

export type putApiAlphaPrivateMessageResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type putApiAlphaPrivateMessageResponseSuccess = (putApiAlphaPrivateMessageResponse200) & {
  headers: Headers;
};
export type putApiAlphaPrivateMessageResponseError = (putApiAlphaPrivateMessageResponse400 | putApiAlphaPrivateMessageResponse422) & {
  headers: Headers;
};

export type putApiAlphaPrivateMessageResponse = (putApiAlphaPrivateMessageResponseSuccess | putApiAlphaPrivateMessageResponseError)

export const getPutApiAlphaPrivateMessageUrl = () => {


  

  return `/api/alpha/private_message`
}

export const putApiAlphaPrivateMessage = async (editPrivateMessageRequest: EditPrivateMessageRequest, options?: RequestInit): Promise<putApiAlphaPrivateMessageResponse> => {
  
  return customFetch<putApiAlphaPrivateMessageResponse>(getPutApiAlphaPrivateMessageUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      editPrivateMessageRequest,)
  }
);}


/**
 * @summary Mark a private message as read or unread.
 */
export type postApiAlphaPrivateMessageMarkAsReadResponse200 = {
  data: PrivateMessageResponse
  status: 200
}

export type postApiAlphaPrivateMessageMarkAsReadResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaPrivateMessageMarkAsReadResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaPrivateMessageMarkAsReadResponseSuccess = (postApiAlphaPrivateMessageMarkAsReadResponse200) & {
  headers: Headers;
};
export type postApiAlphaPrivateMessageMarkAsReadResponseError = (postApiAlphaPrivateMessageMarkAsReadResponse400 | postApiAlphaPrivateMessageMarkAsReadResponse422) & {
  headers: Headers;
};

export type postApiAlphaPrivateMessageMarkAsReadResponse = (postApiAlphaPrivateMessageMarkAsReadResponseSuccess | postApiAlphaPrivateMessageMarkAsReadResponseError)

export const getPostApiAlphaPrivateMessageMarkAsReadUrl = () => {


  

  return `/api/alpha/private_message/mark_as_read`
}

export const postApiAlphaPrivateMessageMarkAsRead = async (markPrivateMessageAsReadRequest: MarkPrivateMessageAsReadRequest, options?: RequestInit): Promise<postApiAlphaPrivateMessageMarkAsReadResponse> => {
  
  return customFetch<postApiAlphaPrivateMessageMarkAsReadResponse>(getPostApiAlphaPrivateMessageMarkAsReadUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      markPrivateMessageAsReadRequest,)
  }
);}


/**
 * @summary Delete or restore a private message.
 */
export type postApiAlphaPrivateMessageDeleteResponse200 = {
  data: PrivateMessageResponse
  status: 200
}

export type postApiAlphaPrivateMessageDeleteResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaPrivateMessageDeleteResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaPrivateMessageDeleteResponseSuccess = (postApiAlphaPrivateMessageDeleteResponse200) & {
  headers: Headers;
};
export type postApiAlphaPrivateMessageDeleteResponseError = (postApiAlphaPrivateMessageDeleteResponse400 | postApiAlphaPrivateMessageDeleteResponse422) & {
  headers: Headers;
};

export type postApiAlphaPrivateMessageDeleteResponse = (postApiAlphaPrivateMessageDeleteResponseSuccess | postApiAlphaPrivateMessageDeleteResponseError)

export const getPostApiAlphaPrivateMessageDeleteUrl = () => {


  

  return `/api/alpha/private_message/delete`
}

export const postApiAlphaPrivateMessageDelete = async (deletePrivateMessageRequest: DeletePrivateMessageRequest, options?: RequestInit): Promise<postApiAlphaPrivateMessageDeleteResponse> => {
  
  return customFetch<postApiAlphaPrivateMessageDeleteResponse>(getPostApiAlphaPrivateMessageDeleteUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      deletePrivateMessageRequest,)
  }
);}


/**
 * @summary Report a private message.
 */
export type postApiAlphaPrivateMessageReportResponse200 = {
  data: PrivateMessageResponse
  status: 200
}

export type postApiAlphaPrivateMessageReportResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaPrivateMessageReportResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaPrivateMessageReportResponseSuccess = (postApiAlphaPrivateMessageReportResponse200) & {
  headers: Headers;
};
export type postApiAlphaPrivateMessageReportResponseError = (postApiAlphaPrivateMessageReportResponse400 | postApiAlphaPrivateMessageReportResponse422) & {
  headers: Headers;
};

export type postApiAlphaPrivateMessageReportResponse = (postApiAlphaPrivateMessageReportResponseSuccess | postApiAlphaPrivateMessageReportResponseError)

export const getPostApiAlphaPrivateMessageReportUrl = () => {


  

  return `/api/alpha/private_message/report`
}

export const postApiAlphaPrivateMessageReport = async (reportPrivateMessageRequest: ReportPrivateMessageRequest, options?: RequestInit): Promise<postApiAlphaPrivateMessageReportResponse> => {
  
  return customFetch<postApiAlphaPrivateMessageReportResponse>(getPostApiAlphaPrivateMessageReportUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reportPrivateMessageRequest,)
  }
);}


