/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type {
  CreatePrivateMessageRequest,
  DeletePrivateMessageRequest,
  EditPrivateMessageRequest,
  GetApiAlphaPrivateMessageConversationParams,
  GetApiAlphaPrivateMessageListParams,
  GetPrivateMessageConversationResponse,
  LeaveConversationRequest,
  ListPrivateMessagesResponse,
  MarkPrivateMessageAsReadRequest,
  PrivateMessageResponse,
  ReportPrivateMessageRequest
} from '../../schemas';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary List private messages.
 */
export const getGetApiAlphaPrivateMessageListUrl = (params?: GetApiAlphaPrivateMessageListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/private_message/list?${stringifiedParams}` : `/api/alpha/private_message/list`
}

export const getApiAlphaPrivateMessageList = async (params?: GetApiAlphaPrivateMessageListParams, options?: RequestInit): Promise<ListPrivateMessagesResponse> => {
  
  return customFetch<ListPrivateMessagesResponse>(getGetApiAlphaPrivateMessageListUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get conversation with a specific person.
 */
export const getGetApiAlphaPrivateMessageConversationUrl = (params?: GetApiAlphaPrivateMessageConversationParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/private_message/conversation?${stringifiedParams}` : `/api/alpha/private_message/conversation`
}

export const getApiAlphaPrivateMessageConversation = async (params?: GetApiAlphaPrivateMessageConversationParams, options?: RequestInit): Promise<GetPrivateMessageConversationResponse> => {
  
  return customFetch<GetPrivateMessageConversationResponse>(getGetApiAlphaPrivateMessageConversationUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Leave a conversation
 */
export const getPostApiAlphaPrivateMessageConversationLeaveUrl = () => {


  

  return `/api/alpha/private_message/conversation/leave`
}

export const postApiAlphaPrivateMessageConversationLeave = async (leaveConversationRequest: LeaveConversationRequest, options?: RequestInit): Promise<void> => {
  
  return customFetch<void>(getPostApiAlphaPrivateMessageConversationLeaveUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      leaveConversationRequest,)
  }
);}


/**
 * @summary Create a new private message.
 */
export const getPostApiAlphaPrivateMessageUrl = () => {


  

  return `/api/alpha/private_message`
}

export const postApiAlphaPrivateMessage = async (createPrivateMessageRequest: CreatePrivateMessageRequest, options?: RequestInit): Promise<PrivateMessageResponse> => {
  
  return customFetch<PrivateMessageResponse>(getPostApiAlphaPrivateMessageUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPrivateMessageRequest,)
  }
);}


/**
 * @summary Edit a private message.
 */
export const getPutApiAlphaPrivateMessageUrl = () => {


  

  return `/api/alpha/private_message`
}

export const putApiAlphaPrivateMessage = async (editPrivateMessageRequest: EditPrivateMessageRequest, options?: RequestInit): Promise<PrivateMessageResponse> => {
  
  return customFetch<PrivateMessageResponse>(getPutApiAlphaPrivateMessageUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      editPrivateMessageRequest,)
  }
);}


/**
 * @summary Mark a private message as read or unread.
 */
export const getPostApiAlphaPrivateMessageMarkAsReadUrl = () => {


  

  return `/api/alpha/private_message/mark_as_read`
}

export const postApiAlphaPrivateMessageMarkAsRead = async (markPrivateMessageAsReadRequest: MarkPrivateMessageAsReadRequest, options?: RequestInit): Promise<PrivateMessageResponse> => {
  
  return customFetch<PrivateMessageResponse>(getPostApiAlphaPrivateMessageMarkAsReadUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      markPrivateMessageAsReadRequest,)
  }
);}


/**
 * @summary Delete or restore a private message.
 */
export const getPostApiAlphaPrivateMessageDeleteUrl = () => {


  

  return `/api/alpha/private_message/delete`
}

export const postApiAlphaPrivateMessageDelete = async (deletePrivateMessageRequest: DeletePrivateMessageRequest, options?: RequestInit): Promise<PrivateMessageResponse> => {
  
  return customFetch<PrivateMessageResponse>(getPostApiAlphaPrivateMessageDeleteUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      deletePrivateMessageRequest,)
  }
);}


/**
 * @summary Report a private message.
 */
export const getPostApiAlphaPrivateMessageReportUrl = () => {


  

  return `/api/alpha/private_message/report`
}

export const postApiAlphaPrivateMessageReport = async (reportPrivateMessageRequest: ReportPrivateMessageRequest, options?: RequestInit): Promise<PrivateMessageResponse> => {
  
  return customFetch<PrivateMessageResponse>(getPostApiAlphaPrivateMessageReportUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reportPrivateMessageRequest,)
  }
);}


