import { defineConfig } from 'orval';

const instance = "https://crust.piefed.social"

export default defineConfig({
  piefedClient: {
    input: {
      target: `${instance}/api/alpha/swagger.json`,
    },
    output: {
      target: './src/client',
      schemas: './src/schemas',
      client: 'fetch',
      mode: 'tags-split',
      clean: true,
      override: {
        header: () => ['Generated by orval', 'Do not edit manually.'],
        mutator: {
          path: './src/mutator/custom-fetch.ts',
          name: 'customFetch',
        },
        fetch: {
          includeHttpResponseReturnType: false,
        },
      },
    },
  },
  piefedZod: {
    input: {
      target: `${instance}/api/alpha/swagger.json`,
    },
    output: {
      target: './src/zod',
      client: 'zod',
      mode: 'tags-split',
      clean: true,
      override: {
        header: () => ['Generated by orval', 'Do not edit manually.'],
      },
    },
  },
});
