/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type {
  BlockInstanceRequest,
  BlockInstanceResponse,
  DefaultError,
  GetApiAlphaSiteInstanceChooserSearchParams,
  GetSiteInstanceChooserResponse,
  GetSiteInstanceChooserSearchResponse,
  GetSiteResponse,
  GetSiteVersionResponse,
  UnprocessableEntityResponse
} from '../../schemas';


/**
 * @summary Gets the site, and your user data.
 */
export type getApiAlphaSiteResponse200 = {
  data: GetSiteResponse
  status: 200
}

export type getApiAlphaSiteResponse400 = {
  data: DefaultError
  status: 400
}
    
export type getApiAlphaSiteResponseSuccess = (getApiAlphaSiteResponse200) & {
  headers: Headers;
};
export type getApiAlphaSiteResponseError = (getApiAlphaSiteResponse400) & {
  headers: Headers;
};

export type getApiAlphaSiteResponse = (getApiAlphaSiteResponseSuccess | getApiAlphaSiteResponseError)

export const getGetApiAlphaSiteUrl = () => {


  

  return `/api/alpha/site`
}

export const getApiAlphaSite = async ( options?: RequestInit): Promise<getApiAlphaSiteResponse> => {
  
  const res = await fetch(getGetApiAlphaSiteUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiAlphaSiteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiAlphaSiteResponse
}


/**
 * @summary Gets version of PieFed.
 */
export type getApiAlphaSiteVersionResponse200 = {
  data: GetSiteVersionResponse
  status: 200
}

export type getApiAlphaSiteVersionResponse400 = {
  data: DefaultError
  status: 400
}
    
export type getApiAlphaSiteVersionResponseSuccess = (getApiAlphaSiteVersionResponse200) & {
  headers: Headers;
};
export type getApiAlphaSiteVersionResponseError = (getApiAlphaSiteVersionResponse400) & {
  headers: Headers;
};

export type getApiAlphaSiteVersionResponse = (getApiAlphaSiteVersionResponseSuccess | getApiAlphaSiteVersionResponseError)

export const getGetApiAlphaSiteVersionUrl = () => {


  

  return `/api/alpha/site/version`
}

export const getApiAlphaSiteVersion = async ( options?: RequestInit): Promise<getApiAlphaSiteVersionResponse> => {
  
  const res = await fetch(getGetApiAlphaSiteVersionUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiAlphaSiteVersionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiAlphaSiteVersionResponse
}


/**
 * @summary Block an instance.
 */
export type postApiAlphaSiteBlockResponse200 = {
  data: BlockInstanceResponse
  status: 200
}

export type postApiAlphaSiteBlockResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaSiteBlockResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaSiteBlockResponseSuccess = (postApiAlphaSiteBlockResponse200) & {
  headers: Headers;
};
export type postApiAlphaSiteBlockResponseError = (postApiAlphaSiteBlockResponse400 | postApiAlphaSiteBlockResponse422) & {
  headers: Headers;
};

export type postApiAlphaSiteBlockResponse = (postApiAlphaSiteBlockResponseSuccess | postApiAlphaSiteBlockResponseError)

export const getPostApiAlphaSiteBlockUrl = () => {


  

  return `/api/alpha/site/block`
}

export const postApiAlphaSiteBlock = async (blockInstanceRequest: BlockInstanceRequest, options?: RequestInit): Promise<postApiAlphaSiteBlockResponse> => {
  
  const res = await fetch(getPostApiAlphaSiteBlockUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      blockInstanceRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAlphaSiteBlockResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAlphaSiteBlockResponse
}


/**
 * @summary Gets the site info for use by other instances in the Instance Chooser functionality.
 */
export type getApiAlphaSiteInstanceChooserResponse200 = {
  data: GetSiteInstanceChooserResponse
  status: 200
}

export type getApiAlphaSiteInstanceChooserResponse400 = {
  data: DefaultError
  status: 400
}
    
export type getApiAlphaSiteInstanceChooserResponseSuccess = (getApiAlphaSiteInstanceChooserResponse200) & {
  headers: Headers;
};
export type getApiAlphaSiteInstanceChooserResponseError = (getApiAlphaSiteInstanceChooserResponse400) & {
  headers: Headers;
};

export type getApiAlphaSiteInstanceChooserResponse = (getApiAlphaSiteInstanceChooserResponseSuccess | getApiAlphaSiteInstanceChooserResponseError)

export const getGetApiAlphaSiteInstanceChooserUrl = () => {


  

  return `/api/alpha/site/instance_chooser`
}

export const getApiAlphaSiteInstanceChooser = async ( options?: RequestInit): Promise<getApiAlphaSiteInstanceChooserResponse> => {
  
  const res = await fetch(getGetApiAlphaSiteInstanceChooserUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiAlphaSiteInstanceChooserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiAlphaSiteInstanceChooserResponse
}


/**
 * @summary Search for other instances.
 */
export type getApiAlphaSiteInstanceChooserSearchResponse200 = {
  data: GetSiteInstanceChooserSearchResponse
  status: 200
}

export type getApiAlphaSiteInstanceChooserSearchResponse400 = {
  data: DefaultError
  status: 400
}

export type getApiAlphaSiteInstanceChooserSearchResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type getApiAlphaSiteInstanceChooserSearchResponseSuccess = (getApiAlphaSiteInstanceChooserSearchResponse200) & {
  headers: Headers;
};
export type getApiAlphaSiteInstanceChooserSearchResponseError = (getApiAlphaSiteInstanceChooserSearchResponse400 | getApiAlphaSiteInstanceChooserSearchResponse422) & {
  headers: Headers;
};

export type getApiAlphaSiteInstanceChooserSearchResponse = (getApiAlphaSiteInstanceChooserSearchResponseSuccess | getApiAlphaSiteInstanceChooserSearchResponseError)

export const getGetApiAlphaSiteInstanceChooserSearchUrl = (params?: GetApiAlphaSiteInstanceChooserSearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/site/instance_chooser_search?${stringifiedParams}` : `/api/alpha/site/instance_chooser_search`
}

export const getApiAlphaSiteInstanceChooserSearch = async (params?: GetApiAlphaSiteInstanceChooserSearchParams, options?: RequestInit): Promise<getApiAlphaSiteInstanceChooserSearchResponse> => {
  
  const res = await fetch(getGetApiAlphaSiteInstanceChooserSearchUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiAlphaSiteInstanceChooserSearchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiAlphaSiteInstanceChooserSearchResponse
}


