/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type {
  BlockInstanceRequest,
  BlockInstanceResponse,
  GetApiAlphaSiteInstanceChooserSearchParams,
  GetSiteInstanceChooserResponse,
  GetSiteInstanceChooserSearchResponse,
  GetSiteResponse,
  GetSiteVersionResponse
} from '../../schemas';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary Gets the site, and your user data.
 */
export const getGetApiAlphaSiteUrl = () => {


  

  return `/api/alpha/site`
}

export const getApiAlphaSite = async ( options?: RequestInit): Promise<GetSiteResponse> => {
  
  return customFetch<GetSiteResponse>(getGetApiAlphaSiteUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Gets version of PieFed.
 */
export const getGetApiAlphaSiteVersionUrl = () => {


  

  return `/api/alpha/site/version`
}

export const getApiAlphaSiteVersion = async ( options?: RequestInit): Promise<GetSiteVersionResponse> => {
  
  return customFetch<GetSiteVersionResponse>(getGetApiAlphaSiteVersionUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Block an instance.
 */
export const getPostApiAlphaSiteBlockUrl = () => {


  

  return `/api/alpha/site/block`
}

export const postApiAlphaSiteBlock = async (blockInstanceRequest: BlockInstanceRequest, options?: RequestInit): Promise<BlockInstanceResponse> => {
  
  return customFetch<BlockInstanceResponse>(getPostApiAlphaSiteBlockUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      blockInstanceRequest,)
  }
);}


/**
 * @summary Gets the site info for use by other instances in the Instance Chooser functionality.
 */
export const getGetApiAlphaSiteInstanceChooserUrl = () => {


  

  return `/api/alpha/site/instance_chooser`
}

export const getApiAlphaSiteInstanceChooser = async ( options?: RequestInit): Promise<GetSiteInstanceChooserResponse> => {
  
  return customFetch<GetSiteInstanceChooserResponse>(getGetApiAlphaSiteInstanceChooserUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Search for other instances.
 */
export const getGetApiAlphaSiteInstanceChooserSearchUrl = (params?: GetApiAlphaSiteInstanceChooserSearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/site/instance_chooser_search?${stringifiedParams}` : `/api/alpha/site/instance_chooser_search`
}

export const getApiAlphaSiteInstanceChooserSearch = async (params?: GetApiAlphaSiteInstanceChooserSearchParams, options?: RequestInit): Promise<GetSiteInstanceChooserSearchResponse> => {
  
  return customFetch<GetSiteInstanceChooserSearchResponse>(getGetApiAlphaSiteInstanceChooserSearchUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


