/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type {
  CreatePostRequest,
  DefaultError,
  DeletePostRequest,
  EditPostRequest,
  FeaturePostRequest,
  GetApiAlphaPostLikeListParams,
  GetApiAlphaPostList2Params,
  GetApiAlphaPostListParams,
  GetApiAlphaPostParams,
  GetApiAlphaPostRepliesParams,
  GetApiAlphaPostSiteMetadataParams,
  GetPostRepliesResponse,
  GetPostResponse,
  GetSiteMetadataResponse,
  HidePostRequest,
  LikePostRequest,
  ListPostLikesResponse,
  ListPostsResponse,
  LockPostRequest,
  MarkPostAsReadRequest,
  PollVoteRequest,
  PollVoteResponse,
  PostReportResponse,
  PostSetFlairRequest,
  PostSetFlairResponse,
  RemovePostRequest,
  ReportPostRequest,
  SavePostRequest,
  SubscribePostRequest,
  SuccessResponse,
  UnprocessableEntityResponse
} from '../../schemas';


/**
 * @summary List posts.
 */
export type getApiAlphaPostListResponse200 = {
  data: ListPostsResponse
  status: 200
}

export type getApiAlphaPostListResponse400 = {
  data: DefaultError
  status: 400
}

export type getApiAlphaPostListResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type getApiAlphaPostListResponseSuccess = (getApiAlphaPostListResponse200) & {
  headers: Headers;
};
export type getApiAlphaPostListResponseError = (getApiAlphaPostListResponse400 | getApiAlphaPostListResponse422) & {
  headers: Headers;
};

export type getApiAlphaPostListResponse = (getApiAlphaPostListResponseSuccess | getApiAlphaPostListResponseError)

export const getGetApiAlphaPostListUrl = (params?: GetApiAlphaPostListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/post/list?${stringifiedParams}` : `/api/alpha/post/list`
}

export const getApiAlphaPostList = async (params?: GetApiAlphaPostListParams, options?: RequestInit): Promise<getApiAlphaPostListResponse> => {
  
  const res = await fetch(getGetApiAlphaPostListUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiAlphaPostListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiAlphaPostListResponse
}


/**
 * @summary List posts. For testing only, do not use.
 */
export type getApiAlphaPostList2Response200 = {
  data: ListPostsResponse
  status: 200
}

export type getApiAlphaPostList2Response400 = {
  data: DefaultError
  status: 400
}

export type getApiAlphaPostList2Response422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type getApiAlphaPostList2ResponseSuccess = (getApiAlphaPostList2Response200) & {
  headers: Headers;
};
export type getApiAlphaPostList2ResponseError = (getApiAlphaPostList2Response400 | getApiAlphaPostList2Response422) & {
  headers: Headers;
};

export type getApiAlphaPostList2Response = (getApiAlphaPostList2ResponseSuccess | getApiAlphaPostList2ResponseError)

export const getGetApiAlphaPostList2Url = (params?: GetApiAlphaPostList2Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/post/list2?${stringifiedParams}` : `/api/alpha/post/list2`
}

export const getApiAlphaPostList2 = async (params?: GetApiAlphaPostList2Params, options?: RequestInit): Promise<getApiAlphaPostList2Response> => {
  
  const res = await fetch(getGetApiAlphaPostList2Url(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiAlphaPostList2Response['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiAlphaPostList2Response
}


/**
 * @summary Get/fetch a post
 */
export type getApiAlphaPostResponse200 = {
  data: GetPostResponse
  status: 200
}

export type getApiAlphaPostResponse400 = {
  data: DefaultError
  status: 400
}

export type getApiAlphaPostResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type getApiAlphaPostResponseSuccess = (getApiAlphaPostResponse200) & {
  headers: Headers;
};
export type getApiAlphaPostResponseError = (getApiAlphaPostResponse400 | getApiAlphaPostResponse422) & {
  headers: Headers;
};

export type getApiAlphaPostResponse = (getApiAlphaPostResponseSuccess | getApiAlphaPostResponseError)

export const getGetApiAlphaPostUrl = (params: GetApiAlphaPostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/post?${stringifiedParams}` : `/api/alpha/post`
}

export const getApiAlphaPost = async (params: GetApiAlphaPostParams, options?: RequestInit): Promise<getApiAlphaPostResponse> => {
  
  const res = await fetch(getGetApiAlphaPostUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiAlphaPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiAlphaPostResponse
}


/**
 * @summary Create a new post.
 */
export type postApiAlphaPostResponse200 = {
  data: GetPostResponse
  status: 200
}

export type postApiAlphaPostResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaPostResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type postApiAlphaPostResponse429 = {
  data: DefaultError
  status: 429
}
    
export type postApiAlphaPostResponseSuccess = (postApiAlphaPostResponse200) & {
  headers: Headers;
};
export type postApiAlphaPostResponseError = (postApiAlphaPostResponse400 | postApiAlphaPostResponse422 | postApiAlphaPostResponse429) & {
  headers: Headers;
};

export type postApiAlphaPostResponse = (postApiAlphaPostResponseSuccess | postApiAlphaPostResponseError)

export const getPostApiAlphaPostUrl = () => {


  

  return `/api/alpha/post`
}

export const postApiAlphaPost = async (createPostRequest: CreatePostRequest, options?: RequestInit): Promise<postApiAlphaPostResponse> => {
  
  const res = await fetch(getPostApiAlphaPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPostRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAlphaPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAlphaPostResponse
}


/**
 * @summary Edit a post.
 */
export type putApiAlphaPostResponse200 = {
  data: GetPostResponse
  status: 200
}

export type putApiAlphaPostResponse400 = {
  data: DefaultError
  status: 400
}

export type putApiAlphaPostResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type putApiAlphaPostResponseSuccess = (putApiAlphaPostResponse200) & {
  headers: Headers;
};
export type putApiAlphaPostResponseError = (putApiAlphaPostResponse400 | putApiAlphaPostResponse422) & {
  headers: Headers;
};

export type putApiAlphaPostResponse = (putApiAlphaPostResponseSuccess | putApiAlphaPostResponseError)

export const getPutApiAlphaPostUrl = () => {


  

  return `/api/alpha/post`
}

export const putApiAlphaPost = async (editPostRequest: EditPostRequest, options?: RequestInit): Promise<putApiAlphaPostResponse> => {
  
  const res = await fetch(getPutApiAlphaPostUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      editPostRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: putApiAlphaPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as putApiAlphaPostResponse
}


/**
 * @summary Get replies/comments for a post with nested structure.
 */
export type getApiAlphaPostRepliesResponse200 = {
  data: GetPostRepliesResponse
  status: 200
}

export type getApiAlphaPostRepliesResponse400 = {
  data: DefaultError
  status: 400
}

export type getApiAlphaPostRepliesResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type getApiAlphaPostRepliesResponseSuccess = (getApiAlphaPostRepliesResponse200) & {
  headers: Headers;
};
export type getApiAlphaPostRepliesResponseError = (getApiAlphaPostRepliesResponse400 | getApiAlphaPostRepliesResponse422) & {
  headers: Headers;
};

export type getApiAlphaPostRepliesResponse = (getApiAlphaPostRepliesResponseSuccess | getApiAlphaPostRepliesResponseError)

export const getGetApiAlphaPostRepliesUrl = (params?: GetApiAlphaPostRepliesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/post/replies?${stringifiedParams}` : `/api/alpha/post/replies`
}

export const getApiAlphaPostReplies = async (params?: GetApiAlphaPostRepliesParams, options?: RequestInit): Promise<getApiAlphaPostRepliesResponse> => {
  
  const res = await fetch(getGetApiAlphaPostRepliesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiAlphaPostRepliesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiAlphaPostRepliesResponse
}


/**
 * @summary Get metadata about a url.
 */
export type getApiAlphaPostSiteMetadataResponse200 = {
  data: GetSiteMetadataResponse
  status: 200
}

export type getApiAlphaPostSiteMetadataResponse400 = {
  data: DefaultError
  status: 400
}

export type getApiAlphaPostSiteMetadataResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type getApiAlphaPostSiteMetadataResponseSuccess = (getApiAlphaPostSiteMetadataResponse200) & {
  headers: Headers;
};
export type getApiAlphaPostSiteMetadataResponseError = (getApiAlphaPostSiteMetadataResponse400 | getApiAlphaPostSiteMetadataResponse422) & {
  headers: Headers;
};

export type getApiAlphaPostSiteMetadataResponse = (getApiAlphaPostSiteMetadataResponseSuccess | getApiAlphaPostSiteMetadataResponseError)

export const getGetApiAlphaPostSiteMetadataUrl = (params?: GetApiAlphaPostSiteMetadataParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/post/site_metadata?${stringifiedParams}` : `/api/alpha/post/site_metadata`
}

export const getApiAlphaPostSiteMetadata = async (params?: GetApiAlphaPostSiteMetadataParams, options?: RequestInit): Promise<getApiAlphaPostSiteMetadataResponse> => {
  
  const res = await fetch(getGetApiAlphaPostSiteMetadataUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiAlphaPostSiteMetadataResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiAlphaPostSiteMetadataResponse
}


/**
 * @summary Like or unlike a post.
 */
export type postApiAlphaPostLikeResponse200 = {
  data: GetPostResponse
  status: 200
}

export type postApiAlphaPostLikeResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaPostLikeResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaPostLikeResponseSuccess = (postApiAlphaPostLikeResponse200) & {
  headers: Headers;
};
export type postApiAlphaPostLikeResponseError = (postApiAlphaPostLikeResponse400 | postApiAlphaPostLikeResponse422) & {
  headers: Headers;
};

export type postApiAlphaPostLikeResponse = (postApiAlphaPostLikeResponseSuccess | postApiAlphaPostLikeResponseError)

export const getPostApiAlphaPostLikeUrl = () => {


  

  return `/api/alpha/post/like`
}

export const postApiAlphaPostLike = async (likePostRequest: LikePostRequest, options?: RequestInit): Promise<postApiAlphaPostLikeResponse> => {
  
  const res = await fetch(getPostApiAlphaPostLikeUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      likePostRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAlphaPostLikeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAlphaPostLikeResponse
}


/**
 * @summary Save or unsave a post.
 */
export type putApiAlphaPostSaveResponse200 = {
  data: GetPostResponse
  status: 200
}

export type putApiAlphaPostSaveResponse400 = {
  data: DefaultError
  status: 400
}

export type putApiAlphaPostSaveResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type putApiAlphaPostSaveResponseSuccess = (putApiAlphaPostSaveResponse200) & {
  headers: Headers;
};
export type putApiAlphaPostSaveResponseError = (putApiAlphaPostSaveResponse400 | putApiAlphaPostSaveResponse422) & {
  headers: Headers;
};

export type putApiAlphaPostSaveResponse = (putApiAlphaPostSaveResponseSuccess | putApiAlphaPostSaveResponseError)

export const getPutApiAlphaPostSaveUrl = () => {


  

  return `/api/alpha/post/save`
}

export const putApiAlphaPostSave = async (savePostRequest: SavePostRequest, options?: RequestInit): Promise<putApiAlphaPostSaveResponse> => {
  
  const res = await fetch(getPutApiAlphaPostSaveUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      savePostRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: putApiAlphaPostSaveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as putApiAlphaPostSaveResponse
}


/**
 * @summary Subscribe or unsubscribe to a post.
 */
export type putApiAlphaPostSubscribeResponse200 = {
  data: GetPostResponse
  status: 200
}

export type putApiAlphaPostSubscribeResponse400 = {
  data: DefaultError
  status: 400
}

export type putApiAlphaPostSubscribeResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type putApiAlphaPostSubscribeResponseSuccess = (putApiAlphaPostSubscribeResponse200) & {
  headers: Headers;
};
export type putApiAlphaPostSubscribeResponseError = (putApiAlphaPostSubscribeResponse400 | putApiAlphaPostSubscribeResponse422) & {
  headers: Headers;
};

export type putApiAlphaPostSubscribeResponse = (putApiAlphaPostSubscribeResponseSuccess | putApiAlphaPostSubscribeResponseError)

export const getPutApiAlphaPostSubscribeUrl = () => {


  

  return `/api/alpha/post/subscribe`
}

export const putApiAlphaPostSubscribe = async (subscribePostRequest: SubscribePostRequest, options?: RequestInit): Promise<putApiAlphaPostSubscribeResponse> => {
  
  const res = await fetch(getPutApiAlphaPostSubscribeUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      subscribePostRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: putApiAlphaPostSubscribeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as putApiAlphaPostSubscribeResponse
}


/**
 * @summary Delete or restore a post.
 */
export type postApiAlphaPostDeleteResponse200 = {
  data: GetPostResponse
  status: 200
}

export type postApiAlphaPostDeleteResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaPostDeleteResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaPostDeleteResponseSuccess = (postApiAlphaPostDeleteResponse200) & {
  headers: Headers;
};
export type postApiAlphaPostDeleteResponseError = (postApiAlphaPostDeleteResponse400 | postApiAlphaPostDeleteResponse422) & {
  headers: Headers;
};

export type postApiAlphaPostDeleteResponse = (postApiAlphaPostDeleteResponseSuccess | postApiAlphaPostDeleteResponseError)

export const getPostApiAlphaPostDeleteUrl = () => {


  

  return `/api/alpha/post/delete`
}

export const postApiAlphaPostDelete = async (deletePostRequest: DeletePostRequest, options?: RequestInit): Promise<postApiAlphaPostDeleteResponse> => {
  
  const res = await fetch(getPostApiAlphaPostDeleteUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      deletePostRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAlphaPostDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAlphaPostDeleteResponse
}


/**
 * @summary Report a post.
 */
export type postApiAlphaPostReportResponse200 = {
  data: PostReportResponse
  status: 200
}

export type postApiAlphaPostReportResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaPostReportResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaPostReportResponseSuccess = (postApiAlphaPostReportResponse200) & {
  headers: Headers;
};
export type postApiAlphaPostReportResponseError = (postApiAlphaPostReportResponse400 | postApiAlphaPostReportResponse422) & {
  headers: Headers;
};

export type postApiAlphaPostReportResponse = (postApiAlphaPostReportResponseSuccess | postApiAlphaPostReportResponseError)

export const getPostApiAlphaPostReportUrl = () => {


  

  return `/api/alpha/post/report`
}

export const postApiAlphaPostReport = async (reportPostRequest: ReportPostRequest, options?: RequestInit): Promise<postApiAlphaPostReportResponse> => {
  
  const res = await fetch(getPostApiAlphaPostReportUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reportPostRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAlphaPostReportResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAlphaPostReportResponse
}


/**
 * @summary Lock or unlock a post.
 */
export type postApiAlphaPostLockResponse200 = {
  data: GetPostResponse
  status: 200
}

export type postApiAlphaPostLockResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaPostLockResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaPostLockResponseSuccess = (postApiAlphaPostLockResponse200) & {
  headers: Headers;
};
export type postApiAlphaPostLockResponseError = (postApiAlphaPostLockResponse400 | postApiAlphaPostLockResponse422) & {
  headers: Headers;
};

export type postApiAlphaPostLockResponse = (postApiAlphaPostLockResponseSuccess | postApiAlphaPostLockResponseError)

export const getPostApiAlphaPostLockUrl = () => {


  

  return `/api/alpha/post/lock`
}

export const postApiAlphaPostLock = async (lockPostRequest: LockPostRequest, options?: RequestInit): Promise<postApiAlphaPostLockResponse> => {
  
  const res = await fetch(getPostApiAlphaPostLockUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      lockPostRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAlphaPostLockResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAlphaPostLockResponse
}


/**
 * @summary Hide or unhide a post.
 */
export type postApiAlphaPostHideResponse200 = {
  data: GetPostResponse
  status: 200
}

export type postApiAlphaPostHideResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaPostHideResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaPostHideResponseSuccess = (postApiAlphaPostHideResponse200) & {
  headers: Headers;
};
export type postApiAlphaPostHideResponseError = (postApiAlphaPostHideResponse400 | postApiAlphaPostHideResponse422) & {
  headers: Headers;
};

export type postApiAlphaPostHideResponse = (postApiAlphaPostHideResponseSuccess | postApiAlphaPostHideResponseError)

export const getPostApiAlphaPostHideUrl = () => {


  

  return `/api/alpha/post/hide`
}

export const postApiAlphaPostHide = async (hidePostRequest: HidePostRequest, options?: RequestInit): Promise<postApiAlphaPostHideResponse> => {
  
  const res = await fetch(getPostApiAlphaPostHideUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      hidePostRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAlphaPostHideResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAlphaPostHideResponse
}


/**
 * @summary Feature or unfeature a post.
 */
export type postApiAlphaPostFeatureResponse200 = {
  data: GetPostResponse
  status: 200
}

export type postApiAlphaPostFeatureResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaPostFeatureResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaPostFeatureResponseSuccess = (postApiAlphaPostFeatureResponse200) & {
  headers: Headers;
};
export type postApiAlphaPostFeatureResponseError = (postApiAlphaPostFeatureResponse400 | postApiAlphaPostFeatureResponse422) & {
  headers: Headers;
};

export type postApiAlphaPostFeatureResponse = (postApiAlphaPostFeatureResponseSuccess | postApiAlphaPostFeatureResponseError)

export const getPostApiAlphaPostFeatureUrl = () => {


  

  return `/api/alpha/post/feature`
}

export const postApiAlphaPostFeature = async (featurePostRequest: FeaturePostRequest, options?: RequestInit): Promise<postApiAlphaPostFeatureResponse> => {
  
  const res = await fetch(getPostApiAlphaPostFeatureUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      featurePostRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAlphaPostFeatureResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAlphaPostFeatureResponse
}


/**
 * @summary Remove or restore a post as a moderator.
 */
export type postApiAlphaPostRemoveResponse200 = {
  data: GetPostResponse
  status: 200
}

export type postApiAlphaPostRemoveResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaPostRemoveResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaPostRemoveResponseSuccess = (postApiAlphaPostRemoveResponse200) & {
  headers: Headers;
};
export type postApiAlphaPostRemoveResponseError = (postApiAlphaPostRemoveResponse400 | postApiAlphaPostRemoveResponse422) & {
  headers: Headers;
};

export type postApiAlphaPostRemoveResponse = (postApiAlphaPostRemoveResponseSuccess | postApiAlphaPostRemoveResponseError)

export const getPostApiAlphaPostRemoveUrl = () => {


  

  return `/api/alpha/post/remove`
}

export const postApiAlphaPostRemove = async (removePostRequest: RemovePostRequest, options?: RequestInit): Promise<postApiAlphaPostRemoveResponse> => {
  
  const res = await fetch(getPostApiAlphaPostRemoveUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      removePostRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAlphaPostRemoveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAlphaPostRemoveResponse
}


/**
 * @summary Mark one or more posts as read or unread.
 */
export type postApiAlphaPostMarkAsReadResponse200 = {
  data: SuccessResponse
  status: 200
}

export type postApiAlphaPostMarkAsReadResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaPostMarkAsReadResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaPostMarkAsReadResponseSuccess = (postApiAlphaPostMarkAsReadResponse200) & {
  headers: Headers;
};
export type postApiAlphaPostMarkAsReadResponseError = (postApiAlphaPostMarkAsReadResponse400 | postApiAlphaPostMarkAsReadResponse422) & {
  headers: Headers;
};

export type postApiAlphaPostMarkAsReadResponse = (postApiAlphaPostMarkAsReadResponseSuccess | postApiAlphaPostMarkAsReadResponseError)

export const getPostApiAlphaPostMarkAsReadUrl = () => {


  

  return `/api/alpha/post/mark_as_read`
}

export const postApiAlphaPostMarkAsRead = async (markPostAsReadRequest: MarkPostAsReadRequest, options?: RequestInit): Promise<postApiAlphaPostMarkAsReadResponse> => {
  
  const res = await fetch(getPostApiAlphaPostMarkAsReadUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      markPostAsReadRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAlphaPostMarkAsReadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAlphaPostMarkAsReadResponse
}


/**
 * @summary View post votes as a moderator.
 */
export type getApiAlphaPostLikeListResponse200 = {
  data: ListPostLikesResponse
  status: 200
}

export type getApiAlphaPostLikeListResponse400 = {
  data: DefaultError
  status: 400
}

export type getApiAlphaPostLikeListResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type getApiAlphaPostLikeListResponseSuccess = (getApiAlphaPostLikeListResponse200) & {
  headers: Headers;
};
export type getApiAlphaPostLikeListResponseError = (getApiAlphaPostLikeListResponse400 | getApiAlphaPostLikeListResponse422) & {
  headers: Headers;
};

export type getApiAlphaPostLikeListResponse = (getApiAlphaPostLikeListResponseSuccess | getApiAlphaPostLikeListResponseError)

export const getGetApiAlphaPostLikeListUrl = (params: GetApiAlphaPostLikeListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/post/like/list?${stringifiedParams}` : `/api/alpha/post/like/list`
}

export const getApiAlphaPostLikeList = async (params: GetApiAlphaPostLikeListParams, options?: RequestInit): Promise<getApiAlphaPostLikeListResponse> => {
  
  const res = await fetch(getGetApiAlphaPostLikeListUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiAlphaPostLikeListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiAlphaPostLikeListResponse
}


/**
 * @summary Add/remove flair from a post
 */
export type postApiAlphaPostAssignFlairResponse200 = {
  data: PostSetFlairResponse
  status: 200
}

export type postApiAlphaPostAssignFlairResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaPostAssignFlairResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaPostAssignFlairResponseSuccess = (postApiAlphaPostAssignFlairResponse200) & {
  headers: Headers;
};
export type postApiAlphaPostAssignFlairResponseError = (postApiAlphaPostAssignFlairResponse400 | postApiAlphaPostAssignFlairResponse422) & {
  headers: Headers;
};

export type postApiAlphaPostAssignFlairResponse = (postApiAlphaPostAssignFlairResponseSuccess | postApiAlphaPostAssignFlairResponseError)

export const getPostApiAlphaPostAssignFlairUrl = () => {


  

  return `/api/alpha/post/assign_flair`
}

export const postApiAlphaPostAssignFlair = async (postSetFlairRequest: PostSetFlairRequest, options?: RequestInit): Promise<postApiAlphaPostAssignFlairResponse> => {
  
  const res = await fetch(getPostApiAlphaPostAssignFlairUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postSetFlairRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAlphaPostAssignFlairResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAlphaPostAssignFlairResponse
}


/**
 * @summary Vote in a poll
 */
export type postApiAlphaPostPollVoteResponse200 = {
  data: PollVoteResponse
  status: 200
}

export type postApiAlphaPostPollVoteResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaPostPollVoteResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaPostPollVoteResponseSuccess = (postApiAlphaPostPollVoteResponse200) & {
  headers: Headers;
};
export type postApiAlphaPostPollVoteResponseError = (postApiAlphaPostPollVoteResponse400 | postApiAlphaPostPollVoteResponse422) & {
  headers: Headers;
};

export type postApiAlphaPostPollVoteResponse = (postApiAlphaPostPollVoteResponseSuccess | postApiAlphaPostPollVoteResponseError)

export const getPostApiAlphaPostPollVoteUrl = () => {


  

  return `/api/alpha/post/poll_vote`
}

export const postApiAlphaPostPollVote = async (pollVoteRequest: PollVoteRequest, options?: RequestInit): Promise<postApiAlphaPostPollVoteResponse> => {
  
  const res = await fetch(getPostApiAlphaPostPollVoteUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pollVoteRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAlphaPostPollVoteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAlphaPostPollVoteResponse
}


