/**
 * Generated by orval
 * Do not edit manually.
 */
import type {
  CreatePostRequest,
  DeletePostRequest,
  EditPostRequest,
  FeaturePostRequest,
  GetApiAlphaPostLikeListParams,
  GetApiAlphaPostList2Params,
  GetApiAlphaPostListParams,
  GetApiAlphaPostParams,
  GetApiAlphaPostRepliesParams,
  GetApiAlphaPostSiteMetadataParams,
  GetPostRepliesResponse,
  GetPostResponse,
  GetSiteMetadataResponse,
  HidePostRequest,
  LikePostRequest,
  ListPostLikesResponse,
  ListPostsResponse,
  LockPostRequest,
  MarkPostAsReadRequest,
  PollVoteRequest,
  PollVoteResponse,
  PostReportResponse,
  PostSetFlairRequest,
  PostSetFlairResponse,
  RemovePostRequest,
  ReportPostRequest,
  SavePostRequest,
  SubscribePostRequest,
  SuccessResponse
} from '../../schemas';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary List posts.
 */
export const getGetApiAlphaPostListUrl = (params?: GetApiAlphaPostListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/post/list?${stringifiedParams}` : `/api/alpha/post/list`
}

export const getApiAlphaPostList = async (params?: GetApiAlphaPostListParams, options?: RequestInit): Promise<ListPostsResponse> => {
  
  return customFetch<ListPostsResponse>(getGetApiAlphaPostListUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary List posts. For testing only, do not use.
 */
export const getGetApiAlphaPostList2Url = (params?: GetApiAlphaPostList2Params,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/post/list2?${stringifiedParams}` : `/api/alpha/post/list2`
}

export const getApiAlphaPostList2 = async (params?: GetApiAlphaPostList2Params, options?: RequestInit): Promise<ListPostsResponse> => {
  
  return customFetch<ListPostsResponse>(getGetApiAlphaPostList2Url(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get/fetch a post
 */
export const getGetApiAlphaPostUrl = (params: GetApiAlphaPostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/post?${stringifiedParams}` : `/api/alpha/post`
}

export const getApiAlphaPost = async (params: GetApiAlphaPostParams, options?: RequestInit): Promise<GetPostResponse> => {
  
  return customFetch<GetPostResponse>(getGetApiAlphaPostUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Create a new post.
 */
export const getPostApiAlphaPostUrl = () => {


  

  return `/api/alpha/post`
}

export const postApiAlphaPost = async (createPostRequest: CreatePostRequest, options?: RequestInit): Promise<GetPostResponse> => {
  
  return customFetch<GetPostResponse>(getPostApiAlphaPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPostRequest,)
  }
);}


/**
 * @summary Edit a post.
 */
export const getPutApiAlphaPostUrl = () => {


  

  return `/api/alpha/post`
}

export const putApiAlphaPost = async (editPostRequest: EditPostRequest, options?: RequestInit): Promise<GetPostResponse> => {
  
  return customFetch<GetPostResponse>(getPutApiAlphaPostUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      editPostRequest,)
  }
);}


/**
 * @summary Get replies/comments for a post with nested structure.
 */
export const getGetApiAlphaPostRepliesUrl = (params?: GetApiAlphaPostRepliesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/post/replies?${stringifiedParams}` : `/api/alpha/post/replies`
}

export const getApiAlphaPostReplies = async (params?: GetApiAlphaPostRepliesParams, options?: RequestInit): Promise<GetPostRepliesResponse> => {
  
  return customFetch<GetPostRepliesResponse>(getGetApiAlphaPostRepliesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get metadata about a url.
 */
export const getGetApiAlphaPostSiteMetadataUrl = (params?: GetApiAlphaPostSiteMetadataParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/post/site_metadata?${stringifiedParams}` : `/api/alpha/post/site_metadata`
}

export const getApiAlphaPostSiteMetadata = async (params?: GetApiAlphaPostSiteMetadataParams, options?: RequestInit): Promise<GetSiteMetadataResponse> => {
  
  return customFetch<GetSiteMetadataResponse>(getGetApiAlphaPostSiteMetadataUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Like or unlike a post.
 */
export const getPostApiAlphaPostLikeUrl = () => {


  

  return `/api/alpha/post/like`
}

export const postApiAlphaPostLike = async (likePostRequest: LikePostRequest, options?: RequestInit): Promise<GetPostResponse> => {
  
  return customFetch<GetPostResponse>(getPostApiAlphaPostLikeUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      likePostRequest,)
  }
);}


/**
 * @summary Save or unsave a post.
 */
export const getPutApiAlphaPostSaveUrl = () => {


  

  return `/api/alpha/post/save`
}

export const putApiAlphaPostSave = async (savePostRequest: SavePostRequest, options?: RequestInit): Promise<GetPostResponse> => {
  
  return customFetch<GetPostResponse>(getPutApiAlphaPostSaveUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      savePostRequest,)
  }
);}


/**
 * @summary Subscribe or unsubscribe to a post.
 */
export const getPutApiAlphaPostSubscribeUrl = () => {


  

  return `/api/alpha/post/subscribe`
}

export const putApiAlphaPostSubscribe = async (subscribePostRequest: SubscribePostRequest, options?: RequestInit): Promise<GetPostResponse> => {
  
  return customFetch<GetPostResponse>(getPutApiAlphaPostSubscribeUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      subscribePostRequest,)
  }
);}


/**
 * @summary Delete or restore a post.
 */
export const getPostApiAlphaPostDeleteUrl = () => {


  

  return `/api/alpha/post/delete`
}

export const postApiAlphaPostDelete = async (deletePostRequest: DeletePostRequest, options?: RequestInit): Promise<GetPostResponse> => {
  
  return customFetch<GetPostResponse>(getPostApiAlphaPostDeleteUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      deletePostRequest,)
  }
);}


/**
 * @summary Report a post.
 */
export const getPostApiAlphaPostReportUrl = () => {


  

  return `/api/alpha/post/report`
}

export const postApiAlphaPostReport = async (reportPostRequest: ReportPostRequest, options?: RequestInit): Promise<PostReportResponse> => {
  
  return customFetch<PostReportResponse>(getPostApiAlphaPostReportUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reportPostRequest,)
  }
);}


/**
 * @summary Lock or unlock a post.
 */
export const getPostApiAlphaPostLockUrl = () => {


  

  return `/api/alpha/post/lock`
}

export const postApiAlphaPostLock = async (lockPostRequest: LockPostRequest, options?: RequestInit): Promise<GetPostResponse> => {
  
  return customFetch<GetPostResponse>(getPostApiAlphaPostLockUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      lockPostRequest,)
  }
);}


/**
 * @summary Hide or unhide a post.
 */
export const getPostApiAlphaPostHideUrl = () => {


  

  return `/api/alpha/post/hide`
}

export const postApiAlphaPostHide = async (hidePostRequest: HidePostRequest, options?: RequestInit): Promise<GetPostResponse> => {
  
  return customFetch<GetPostResponse>(getPostApiAlphaPostHideUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      hidePostRequest,)
  }
);}


/**
 * @summary Feature or unfeature a post.
 */
export const getPostApiAlphaPostFeatureUrl = () => {


  

  return `/api/alpha/post/feature`
}

export const postApiAlphaPostFeature = async (featurePostRequest: FeaturePostRequest, options?: RequestInit): Promise<GetPostResponse> => {
  
  return customFetch<GetPostResponse>(getPostApiAlphaPostFeatureUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      featurePostRequest,)
  }
);}


/**
 * @summary Remove or restore a post as a moderator.
 */
export const getPostApiAlphaPostRemoveUrl = () => {


  

  return `/api/alpha/post/remove`
}

export const postApiAlphaPostRemove = async (removePostRequest: RemovePostRequest, options?: RequestInit): Promise<GetPostResponse> => {
  
  return customFetch<GetPostResponse>(getPostApiAlphaPostRemoveUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      removePostRequest,)
  }
);}


/**
 * @summary Mark one or more posts as read or unread.
 */
export const getPostApiAlphaPostMarkAsReadUrl = () => {


  

  return `/api/alpha/post/mark_as_read`
}

export const postApiAlphaPostMarkAsRead = async (markPostAsReadRequest: MarkPostAsReadRequest, options?: RequestInit): Promise<SuccessResponse> => {
  
  return customFetch<SuccessResponse>(getPostApiAlphaPostMarkAsReadUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      markPostAsReadRequest,)
  }
);}


/**
 * @summary View post votes as a moderator.
 */
export const getGetApiAlphaPostLikeListUrl = (params: GetApiAlphaPostLikeListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/post/like/list?${stringifiedParams}` : `/api/alpha/post/like/list`
}

export const getApiAlphaPostLikeList = async (params: GetApiAlphaPostLikeListParams, options?: RequestInit): Promise<ListPostLikesResponse> => {
  
  return customFetch<ListPostLikesResponse>(getGetApiAlphaPostLikeListUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Add/remove flair from a post
 */
export const getPostApiAlphaPostAssignFlairUrl = () => {


  

  return `/api/alpha/post/assign_flair`
}

export const postApiAlphaPostAssignFlair = async (postSetFlairRequest: PostSetFlairRequest, options?: RequestInit): Promise<PostSetFlairResponse> => {
  
  return customFetch<PostSetFlairResponse>(getPostApiAlphaPostAssignFlairUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postSetFlairRequest,)
  }
);}


/**
 * @summary Vote in a poll
 */
export const getPostApiAlphaPostPollVoteUrl = () => {


  

  return `/api/alpha/post/poll_vote`
}

export const postApiAlphaPostPollVote = async (pollVoteRequest: PollVoteRequest, options?: RequestInit): Promise<PollVoteResponse> => {
  
  return customFetch<PollVoteResponse>(getPostApiAlphaPostPollVoteUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pollVoteRequest,)
  }
);}


