/**
 * Generated by orval
 * Do not edit manually.
 */
import type {
  CreateCommentRequest,
  DeleteCommentRequest,
  EditCommentRequest,
  GetApiAlphaCommentLikeListParams,
  GetApiAlphaCommentListParams,
  GetApiAlphaCommentParams,
  GetCommentReplyResponse,
  GetCommentReportResponse,
  GetCommentResponse,
  LikeCommentRequest,
  ListCommentLikesResponse,
  ListCommentsResponse,
  LockCommentRequest,
  MarkCommentAsAnswerRequest,
  MarkCommentAsReadRequest,
  RemoveCommentRequest,
  ReportCommentRequest,
  SaveCommentRequest,
  SubscribeCommentRequest
} from '../../schemas';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary List comments, with various filters.
 */
export const getGetApiAlphaCommentListUrl = (params?: GetApiAlphaCommentListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/comment/list?${stringifiedParams}` : `/api/alpha/comment/list`
}

export const getApiAlphaCommentList = async (params?: GetApiAlphaCommentListParams, options?: RequestInit): Promise<ListCommentsResponse> => {
  
  return customFetch<ListCommentsResponse>(getGetApiAlphaCommentListUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Like / vote on a comment.
 */
export const getPostApiAlphaCommentLikeUrl = () => {


  

  return `/api/alpha/comment/like`
}

export const postApiAlphaCommentLike = async (likeCommentRequest: LikeCommentRequest, options?: RequestInit): Promise<GetCommentResponse> => {
  
  return customFetch<GetCommentResponse>(getPostApiAlphaCommentLikeUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      likeCommentRequest,)
  }
);}


/**
 * @summary Save a comment.
 */
export const getPutApiAlphaCommentSaveUrl = () => {


  

  return `/api/alpha/comment/save`
}

export const putApiAlphaCommentSave = async (saveCommentRequest: SaveCommentRequest, options?: RequestInit): Promise<GetCommentResponse> => {
  
  return customFetch<GetCommentResponse>(getPutApiAlphaCommentSaveUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      saveCommentRequest,)
  }
);}


/**
 * @summary Subscribe to a comment.
 */
export const getPutApiAlphaCommentSubscribeUrl = () => {


  

  return `/api/alpha/comment/subscribe`
}

export const putApiAlphaCommentSubscribe = async (subscribeCommentRequest: SubscribeCommentRequest, options?: RequestInit): Promise<GetCommentResponse> => {
  
  return customFetch<GetCommentResponse>(getPutApiAlphaCommentSubscribeUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      subscribeCommentRequest,)
  }
);}


/**
 * @summary Create a comment.
 */
export const getPostApiAlphaCommentUrl = () => {


  

  return `/api/alpha/comment`
}

export const postApiAlphaComment = async (createCommentRequest: CreateCommentRequest, options?: RequestInit): Promise<GetCommentResponse> => {
  
  return customFetch<GetCommentResponse>(getPostApiAlphaCommentUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCommentRequest,)
  }
);}


/**
 * @summary Edit a comment.
 */
export const getPutApiAlphaCommentUrl = () => {


  

  return `/api/alpha/comment`
}

export const putApiAlphaComment = async (editCommentRequest: EditCommentRequest, options?: RequestInit): Promise<GetCommentResponse> => {
  
  return customFetch<GetCommentResponse>(getPutApiAlphaCommentUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      editCommentRequest,)
  }
);}


/**
 * @summary Get / fetch a comment.
 */
export const getGetApiAlphaCommentUrl = (params: GetApiAlphaCommentParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/comment?${stringifiedParams}` : `/api/alpha/comment`
}

export const getApiAlphaComment = async (params: GetApiAlphaCommentParams, options?: RequestInit): Promise<GetCommentResponse> => {
  
  return customFetch<GetCommentResponse>(getGetApiAlphaCommentUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Delete a comment.
 */
export const getPostApiAlphaCommentDeleteUrl = () => {


  

  return `/api/alpha/comment/delete`
}

export const postApiAlphaCommentDelete = async (deleteCommentRequest: DeleteCommentRequest, options?: RequestInit): Promise<GetCommentResponse> => {
  
  return customFetch<GetCommentResponse>(getPostApiAlphaCommentDeleteUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      deleteCommentRequest,)
  }
);}


/**
 * @summary Report a comment.
 */
export const getPostApiAlphaCommentReportUrl = () => {


  

  return `/api/alpha/comment/report`
}

export const postApiAlphaCommentReport = async (reportCommentRequest: ReportCommentRequest, options?: RequestInit): Promise<GetCommentReportResponse> => {
  
  return customFetch<GetCommentReportResponse>(getPostApiAlphaCommentReportUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reportCommentRequest,)
  }
);}


/**
 * @summary Remove a comment as a moderator.
 */
export const getPostApiAlphaCommentRemoveUrl = () => {


  

  return `/api/alpha/comment/remove`
}

export const postApiAlphaCommentRemove = async (removeCommentRequest: RemoveCommentRequest, options?: RequestInit): Promise<GetCommentResponse> => {
  
  return customFetch<GetCommentResponse>(getPostApiAlphaCommentRemoveUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      removeCommentRequest,)
  }
);}


/**
 * @summary Mark a comment reply as read.
 */
export const getPostApiAlphaCommentMarkAsReadUrl = () => {


  

  return `/api/alpha/comment/mark_as_read`
}

export const postApiAlphaCommentMarkAsRead = async (markCommentAsReadRequest: MarkCommentAsReadRequest, options?: RequestInit): Promise<GetCommentReplyResponse> => {
  
  return customFetch<GetCommentReplyResponse>(getPostApiAlphaCommentMarkAsReadUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      markCommentAsReadRequest,)
  }
);}


/**
 * @summary Mark a comment as the preferred answer to a question.
 */
export const getPostApiAlphaCommentMarkAsAnswerUrl = () => {


  

  return `/api/alpha/comment/mark_as_answer`
}

export const postApiAlphaCommentMarkAsAnswer = async (markCommentAsAnswerRequest: MarkCommentAsAnswerRequest, options?: RequestInit): Promise<GetCommentReplyResponse> => {
  
  return customFetch<GetCommentReplyResponse>(getPostApiAlphaCommentMarkAsAnswerUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      markCommentAsAnswerRequest,)
  }
);}


/**
 * @summary Lock a comment chain as a moderator.
 */
export const getPostApiAlphaCommentLockUrl = () => {


  

  return `/api/alpha/comment/lock`
}

export const postApiAlphaCommentLock = async (lockCommentRequest: LockCommentRequest, options?: RequestInit): Promise<GetCommentResponse> => {
  
  return customFetch<GetCommentResponse>(getPostApiAlphaCommentLockUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      lockCommentRequest,)
  }
);}


/**
 * @summary View comment votes as a moderator.
 */
export const getGetApiAlphaCommentLikeListUrl = (params: GetApiAlphaCommentLikeListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/comment/like/list?${stringifiedParams}` : `/api/alpha/comment/like/list`
}

export const getApiAlphaCommentLikeList = async (params: GetApiAlphaCommentLikeListParams, options?: RequestInit): Promise<ListCommentLikesResponse> => {
  
  return customFetch<ListCommentLikesResponse>(getGetApiAlphaCommentLikeListUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


