/**
 * Generated by orval
 * Do not edit manually.
 */
import type {
  ImageDeleteRequest,
  ImageDeleteResponse,
  ImageUploadRequest,
  ImageUploadResponse
} from '../../schemas';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary Upload a general image.
 */
export const getPostApiAlphaUploadImageUrl = () => {


  

  return `/api/alpha/upload/image`
}

export const postApiAlphaUploadImage = async (imageUploadRequest: ImageUploadRequest, options?: RequestInit): Promise<ImageUploadResponse> => {
    const formData = new FormData();
formData.append(`file`, imageUploadRequest.file)

  return customFetch<ImageUploadResponse>(getPostApiAlphaUploadImageUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}


/**
 * @summary Upload a community image.
 */
export const getPostApiAlphaUploadCommunityImageUrl = () => {


  

  return `/api/alpha/upload/community_image`
}

export const postApiAlphaUploadCommunityImage = async (imageUploadRequest: ImageUploadRequest, options?: RequestInit): Promise<ImageUploadResponse> => {
    const formData = new FormData();
formData.append(`file`, imageUploadRequest.file)

  return customFetch<ImageUploadResponse>(getPostApiAlphaUploadCommunityImageUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}


/**
 * @summary Upload a user image.
 */
export const getPostApiAlphaUploadUserImageUrl = () => {


  

  return `/api/alpha/upload/user_image`
}

export const postApiAlphaUploadUserImage = async (imageUploadRequest: ImageUploadRequest, options?: RequestInit): Promise<ImageUploadResponse> => {
    const formData = new FormData();
formData.append(`file`, imageUploadRequest.file)

  return customFetch<ImageUploadResponse>(getPostApiAlphaUploadUserImageUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}


/**
 * @summary Delete a user image.
 */
export const getPostApiAlphaImageDeleteUrl = () => {


  

  return `/api/alpha/image/delete`
}

export const postApiAlphaImageDelete = async (imageDeleteRequest: ImageDeleteRequest, options?: RequestInit): Promise<ImageDeleteResponse> => {
  
  return customFetch<ImageDeleteResponse>(getPostApiAlphaImageDeleteUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      imageDeleteRequest,)
  }
);}


