/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import * as zod from 'zod';


/**
 * @summary Get / fetch a community.
 */
export const getApiAlphaCommunityQueryParams = zod.object({
  "id": zod.number().optional(),
  "name": zod.string().optional()
})

export const getApiAlphaCommunityResponseModeratorsItemModeratorExtraFieldsMax = 4;

export const getApiAlphaCommunityResponseModeratorsItemModeratorNoteMax = 50;



export const getApiAlphaCommunityResponse = zod.object({
  "community_view": zod.object({
  "activity_alert": zod.boolean(),
  "blocked": zod.boolean(),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "id": zod.number(),
  "post_count": zod.number(),
  "post_reply_count": zod.number(),
  "published": zod.string(),
  "subscriptions_count": zod.number(),
  "total_subscriptions_count": zod.number(),
  "active_daily": zod.number().optional(),
  "active_weekly": zod.number().optional(),
  "active_monthly": zod.number().optional(),
  "active_6monthly": zod.number().optional()
}),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending']),
  "flair_list": zod.array(zod.object({
  "id": zod.number(),
  "community_id": zod.number(),
  "flair_title": zod.string(),
  "text_color": zod.string().describe('Hex color code for the text of the flair'),
  "background_color": zod.string().describe('Hex color code for the background of the flair'),
  "blur_images": zod.boolean(),
  "ap_id": zod.string().nullable().describe('Legacy tags that existed prior to 1.2 and some tags for remote communities might not have a defined ap_id')
})).optional()
}),
  "discussion_languages": zod.array(zod.number()),
  "moderators": zod.array(zod.object({
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "moderator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(getApiAlphaCommunityResponseModeratorsItemModeratorExtraFieldsMax).optional(),
  "note": zod.string().max(getApiAlphaCommunityResponseModeratorsItemModeratorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
})
})),
  "site": zod.object({
  "actor_id": zod.string(),
  "announcement_md": zod.string().optional().describe('The banner at the top of the home page'),
  "announcement": zod.string().optional().describe('The banner at the top of the home page'),
  "name": zod.string(),
  "all_languages": zod.array(zod.object({
  "code": zod.string().optional(),
  "id": zod.number().optional(),
  "name": zod.string().optional()
})).optional(),
  "description": zod.string().optional(),
  "enable_downvotes": zod.boolean().optional(),
  "icon": zod.string().nullish(),
  "registration_mode": zod.enum(['Closed', 'RequireApplication', 'Open']).optional(),
  "sidebar": zod.string().optional(),
  "sidebar_md": zod.string().optional(),
  "user_count": zod.number().optional()
}).optional()
})

/**
 * @summary Create a new community.
 */
export const postApiAlphaCommunityBody = zod.object({
  "name": zod.string(),
  "title": zod.string(),
  "banner_url": zod.string().nullish(),
  "description": zod.string().optional(),
  "discussion_languages": zod.array(zod.number()).optional(),
  "icon_url": zod.string().nullish(),
  "local_only": zod.boolean().optional(),
  "nsfw": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "restricted_to_mods": zod.boolean().optional(),
  "rules": zod.string().optional()
})

export const postApiAlphaCommunityResponse = zod.object({
  "community_view": zod.object({
  "activity_alert": zod.boolean(),
  "blocked": zod.boolean(),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "id": zod.number(),
  "post_count": zod.number(),
  "post_reply_count": zod.number(),
  "published": zod.string(),
  "subscriptions_count": zod.number(),
  "total_subscriptions_count": zod.number(),
  "active_daily": zod.number().optional(),
  "active_weekly": zod.number().optional(),
  "active_monthly": zod.number().optional(),
  "active_6monthly": zod.number().optional()
}),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending']),
  "flair_list": zod.array(zod.object({
  "id": zod.number(),
  "community_id": zod.number(),
  "flair_title": zod.string(),
  "text_color": zod.string().describe('Hex color code for the text of the flair'),
  "background_color": zod.string().describe('Hex color code for the background of the flair'),
  "blur_images": zod.boolean(),
  "ap_id": zod.string().nullable().describe('Legacy tags that existed prior to 1.2 and some tags for remote communities might not have a defined ap_id')
})).optional()
}),
  "discussion_languages": zod.array(zod.number())
})

/**
 * @summary Edit community.
 */
export const putApiAlphaCommunityBody = zod.object({
  "community_id": zod.number(),
  "title": zod.string().optional(),
  "banner_url": zod.string().nullish(),
  "description": zod.string().optional(),
  "discussion_languages": zod.array(zod.number()).optional(),
  "icon_url": zod.string().nullish(),
  "local_only": zod.boolean().optional(),
  "nsfw": zod.boolean().optional(),
  "restricted_to_mods": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "rules": zod.string().optional()
})

export const putApiAlphaCommunityResponse = zod.object({
  "community_view": zod.object({
  "activity_alert": zod.boolean(),
  "blocked": zod.boolean(),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "id": zod.number(),
  "post_count": zod.number(),
  "post_reply_count": zod.number(),
  "published": zod.string(),
  "subscriptions_count": zod.number(),
  "total_subscriptions_count": zod.number(),
  "active_daily": zod.number().optional(),
  "active_weekly": zod.number().optional(),
  "active_monthly": zod.number().optional(),
  "active_6monthly": zod.number().optional()
}),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending']),
  "flair_list": zod.array(zod.object({
  "id": zod.number(),
  "community_id": zod.number(),
  "flair_title": zod.string(),
  "text_color": zod.string().describe('Hex color code for the text of the flair'),
  "background_color": zod.string().describe('Hex color code for the background of the flair'),
  "blur_images": zod.boolean(),
  "ap_id": zod.string().nullable().describe('Legacy tags that existed prior to 1.2 and some tags for remote communities might not have a defined ap_id')
})).optional()
}),
  "discussion_languages": zod.array(zod.number())
})

/**
 * @summary List communities, with various filters.
 */
export const getApiAlphaCommunityListQueryParams = zod.object({
  "limit": zod.number().optional(),
  "page": zod.number().optional(),
  "show_nsfw": zod.boolean().optional(),
  "sort": zod.enum(['Hot', 'Top', 'New', 'Old', 'Active', 'TopAll', 'TopPosts', 'TopSubscribers', 'NewFederated', 'OldFederated']).optional(),
  "type_": zod.enum(['All', 'Local', 'Subscribed', 'Moderating', 'ModeratorView']).optional()
})

export const getApiAlphaCommunityListResponse = zod.object({
  "communities": zod.array(zod.object({
  "activity_alert": zod.boolean(),
  "blocked": zod.boolean(),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "id": zod.number(),
  "post_count": zod.number(),
  "post_reply_count": zod.number(),
  "published": zod.string(),
  "subscriptions_count": zod.number(),
  "total_subscriptions_count": zod.number(),
  "active_daily": zod.number().optional(),
  "active_weekly": zod.number().optional(),
  "active_monthly": zod.number().optional(),
  "active_6monthly": zod.number().optional()
}),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending']),
  "flair_list": zod.array(zod.object({
  "id": zod.number(),
  "community_id": zod.number(),
  "flair_title": zod.string(),
  "text_color": zod.string().describe('Hex color code for the text of the flair'),
  "background_color": zod.string().describe('Hex color code for the background of the flair'),
  "blur_images": zod.boolean(),
  "ap_id": zod.string().nullable().describe('Legacy tags that existed prior to 1.2 and some tags for remote communities might not have a defined ap_id')
})).optional()
})),
  "next_page": zod.string().nullish()
})

/**
 * @summary Follow / subscribe to a community.
 */
export const postApiAlphaCommunityFollowBody = zod.object({
  "community_id": zod.number(),
  "follow": zod.boolean()
})

export const postApiAlphaCommunityFollowResponse = zod.object({
  "community_view": zod.object({
  "activity_alert": zod.boolean(),
  "blocked": zod.boolean(),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "id": zod.number(),
  "post_count": zod.number(),
  "post_reply_count": zod.number(),
  "published": zod.string(),
  "subscriptions_count": zod.number(),
  "total_subscriptions_count": zod.number(),
  "active_daily": zod.number().optional(),
  "active_weekly": zod.number().optional(),
  "active_monthly": zod.number().optional(),
  "active_6monthly": zod.number().optional()
}),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending']),
  "flair_list": zod.array(zod.object({
  "id": zod.number(),
  "community_id": zod.number(),
  "flair_title": zod.string(),
  "text_color": zod.string().describe('Hex color code for the text of the flair'),
  "background_color": zod.string().describe('Hex color code for the background of the flair'),
  "blur_images": zod.boolean(),
  "ap_id": zod.string().nullable().describe('Legacy tags that existed prior to 1.2 and some tags for remote communities might not have a defined ap_id')
})).optional()
}),
  "discussion_languages": zod.array(zod.number())
})

/**
 * @summary Leave all communities and feeds for which the user is not a moderator or owner.
 */
export const postApiAlphaCommunityLeaveAllResponseCommunityBlocksItemPersonExtraFieldsMax = 4;

export const postApiAlphaCommunityLeaveAllResponseCommunityBlocksItemPersonNoteMax = 50;

export const postApiAlphaCommunityLeaveAllResponseFollowsItemFollowerExtraFieldsMax = 4;

export const postApiAlphaCommunityLeaveAllResponseFollowsItemFollowerNoteMax = 50;

export const postApiAlphaCommunityLeaveAllResponseInstanceBlocksItemPersonExtraFieldsMax = 4;

export const postApiAlphaCommunityLeaveAllResponseInstanceBlocksItemPersonNoteMax = 50;

export const postApiAlphaCommunityLeaveAllResponseLocalUserViewPersonExtraFieldsMax = 4;

export const postApiAlphaCommunityLeaveAllResponseLocalUserViewPersonNoteMax = 50;

export const postApiAlphaCommunityLeaveAllResponseModeratesItemModeratorExtraFieldsMax = 4;

export const postApiAlphaCommunityLeaveAllResponseModeratesItemModeratorNoteMax = 50;

export const postApiAlphaCommunityLeaveAllResponsePersonBlocksItemPersonExtraFieldsMax = 4;

export const postApiAlphaCommunityLeaveAllResponsePersonBlocksItemPersonNoteMax = 50;

export const postApiAlphaCommunityLeaveAllResponsePersonBlocksItemTargetExtraFieldsMax = 4;

export const postApiAlphaCommunityLeaveAllResponsePersonBlocksItemTargetNoteMax = 50;



export const postApiAlphaCommunityLeaveAllResponse = zod.object({
  "community_blocks": zod.array(zod.object({
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}).optional(),
  "person": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommunityLeaveAllResponseCommunityBlocksItemPersonExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommunityLeaveAllResponseCommunityBlocksItemPersonNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}).optional()
})),
  "discussion_languages": zod.array(zod.object({
  "code": zod.string().optional(),
  "id": zod.number().optional(),
  "name": zod.string().optional()
})),
  "follows": zod.array(zod.object({
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "follower": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommunityLeaveAllResponseFollowsItemFollowerExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommunityLeaveAllResponseFollowsItemFollowerNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
})
})),
  "instance_blocks": zod.array(zod.object({
  "instance": zod.object({
  "domain": zod.string(),
  "id": zod.number(),
  "published": zod.string(),
  "software": zod.string().optional(),
  "updated": zod.string().optional(),
  "version": zod.string().optional()
}),
  "person": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommunityLeaveAllResponseInstanceBlocksItemPersonExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommunityLeaveAllResponseInstanceBlocksItemPersonNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
})
})),
  "local_user_view": zod.object({
  "counts": zod.object({
  "comment_count": zod.number(),
  "person_id": zod.number(),
  "post_count": zod.number()
}),
  "local_user": zod.object({
  "accept_private_messages": zod.enum(['None', 'Local', 'Trusted', 'All']).describe('Accept private messages from nobody, local users only, \"trusted\" instances, or any instance'),
  "bot_visibility": zod.enum(['Show', 'Blur', 'Hide', 'Transparent']),
  "ai_visibility": zod.enum(['Show', 'Hide', 'Label', 'Transparent']),
  "community_keyword_filter": zod.array(zod.string()).optional().describe('Filter out communities with these words in their name'),
  "default_comment_sort_type": zod.enum(['Hot', 'Top', 'TopAll', 'New', 'Old', 'Controversial']),
  "default_listing_type": zod.enum(['All', 'Local', 'Subscribed', 'Popular', 'Moderating', 'ModeratorView']),
  "default_sort_type": zod.enum(['Active', 'Hot', 'New', 'Top', 'TopHour', 'TopSixHour', 'TopTwelveHour', 'TopDay', 'TopWeek', 'TopMonth', 'TopThreeMonths', 'TopSixMonths', 'TopNineMonths', 'TopYear', 'TopAll', 'Scaled', 'Old', 'Relevance', 'TopPosts', 'TopSubscribers', 'NewFederated', 'OldFederated']).optional(),
  "email_unread": zod.boolean().describe('Receive email about missed notifications (if set up by local admin)'),
  "federate_votes": zod.boolean().describe('If false, votes are only counted on local instance instead of federated remotely'),
  "feed_auto_follow": zod.boolean().describe('Automatically follow communities in a subscribed feed'),
  "feed_auto_leave": zod.boolean().describe('Automatically leave communities when unsubscribing from a feed. Does not impact communities joined outside of a feed auto-follow.'),
  "hide_low_quality": zod.boolean().describe('Hide posts from communities marked as low-quality by the local instance admin'),
  "indexable": zod.boolean().describe('If posts can show up in search results'),
  "newsletter": zod.boolean().describe('Subscribe to the email newsletter that the local instance admin can send'),
  "nsfl_visibility": zod.enum(['Show', 'Blur', 'Hide', 'Transparent']),
  "nsfw_visibility": zod.enum(['Show', 'Blur', 'Hide', 'Transparent']),
  "reply_collapse_threshold": zod.number().describe('Collapse replies with a score at or below this level'),
  "reply_hide_threshold": zod.number().describe('Hide replies with a score at or below this level'),
  "searchable": zod.boolean().describe('If profile shows up in the user list on the instance'),
  "show_bot_accounts": zod.boolean().describe('True for any visibility option other than Hide'),
  "show_nsfl": zod.boolean().describe('True for any visibility option other than Hide'),
  "show_nsfw": zod.boolean().describe('True for any visibility option other than Hide'),
  "show_read_posts": zod.boolean(),
  "show_scores": zod.boolean()
}),
  "person": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommunityLeaveAllResponseLocalUserViewPersonExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommunityLeaveAllResponseLocalUserViewPersonNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
})
}),
  "moderates": zod.array(zod.object({
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "moderator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommunityLeaveAllResponseModeratesItemModeratorExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommunityLeaveAllResponseModeratesItemModeratorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
})
})),
  "person_blocks": zod.array(zod.object({
  "person": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommunityLeaveAllResponsePersonBlocksItemPersonExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommunityLeaveAllResponsePersonBlocksItemPersonNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "target": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommunityLeaveAllResponsePersonBlocksItemTargetExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommunityLeaveAllResponsePersonBlocksItemTargetNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
})
}))
})

/**
 * @summary Block a community.
 */
export const postApiAlphaCommunityBlockBody = zod.object({
  "block": zod.boolean(),
  "community_id": zod.number()
})

export const postApiAlphaCommunityBlockResponse = zod.object({
  "community_view": zod.object({
  "activity_alert": zod.boolean(),
  "blocked": zod.boolean(),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "id": zod.number(),
  "post_count": zod.number(),
  "post_reply_count": zod.number(),
  "published": zod.string(),
  "subscriptions_count": zod.number(),
  "total_subscriptions_count": zod.number(),
  "active_daily": zod.number().optional(),
  "active_weekly": zod.number().optional(),
  "active_monthly": zod.number().optional(),
  "active_6monthly": zod.number().optional()
}),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending']),
  "flair_list": zod.array(zod.object({
  "id": zod.number(),
  "community_id": zod.number(),
  "flair_title": zod.string(),
  "text_color": zod.string().describe('Hex color code for the text of the flair'),
  "background_color": zod.string().describe('Hex color code for the background of the flair'),
  "blur_images": zod.boolean(),
  "ap_id": zod.string().nullable().describe('Legacy tags that existed prior to 1.2 and some tags for remote communities might not have a defined ap_id')
})).optional()
}),
  "blocked": zod.boolean()
})

/**
 * @summary Subscribe to activities in a community.
 */
export const putApiAlphaCommunitySubscribeBody = zod.object({
  "community_id": zod.number(),
  "subscribe": zod.boolean()
})

export const putApiAlphaCommunitySubscribeResponse = zod.object({
  "community_view": zod.object({
  "activity_alert": zod.boolean(),
  "blocked": zod.boolean(),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "id": zod.number(),
  "post_count": zod.number(),
  "post_reply_count": zod.number(),
  "published": zod.string(),
  "subscriptions_count": zod.number(),
  "total_subscriptions_count": zod.number(),
  "active_daily": zod.number().optional(),
  "active_weekly": zod.number().optional(),
  "active_monthly": zod.number().optional(),
  "active_6monthly": zod.number().optional()
}),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending']),
  "flair_list": zod.array(zod.object({
  "id": zod.number(),
  "community_id": zod.number(),
  "flair_title": zod.string(),
  "text_color": zod.string().describe('Hex color code for the text of the flair'),
  "background_color": zod.string().describe('Hex color code for the background of the flair'),
  "blur_images": zod.boolean(),
  "ap_id": zod.string().nullable().describe('Legacy tags that existed prior to 1.2 and some tags for remote communities might not have a defined ap_id')
})).optional()
}),
  "discussion_languages": zod.array(zod.number())
})

/**
 * @summary Delete a community.
 */
export const postApiAlphaCommunityDeleteBody = zod.object({
  "community_id": zod.number(),
  "deleted": zod.boolean()
})

export const postApiAlphaCommunityDeleteResponse = zod.object({
  "community_view": zod.object({
  "activity_alert": zod.boolean(),
  "blocked": zod.boolean(),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "id": zod.number(),
  "post_count": zod.number(),
  "post_reply_count": zod.number(),
  "published": zod.string(),
  "subscriptions_count": zod.number(),
  "total_subscriptions_count": zod.number(),
  "active_daily": zod.number().optional(),
  "active_weekly": zod.number().optional(),
  "active_monthly": zod.number().optional(),
  "active_6monthly": zod.number().optional()
}),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending']),
  "flair_list": zod.array(zod.object({
  "id": zod.number(),
  "community_id": zod.number(),
  "flair_title": zod.string(),
  "text_color": zod.string().describe('Hex color code for the text of the flair'),
  "background_color": zod.string().describe('Hex color code for the background of the flair'),
  "blur_images": zod.boolean(),
  "ap_id": zod.string().nullable().describe('Legacy tags that existed prior to 1.2 and some tags for remote communities might not have a defined ap_id')
})).optional()
}),
  "discussion_languages": zod.array(zod.number())
})

/**
 * @summary Add or remove a moderator for your community.
 */
export const postApiAlphaCommunityModBody = zod.object({
  "added": zod.boolean(),
  "community_id": zod.number(),
  "person_id": zod.number()
})

export const postApiAlphaCommunityModResponseModeratorsItemModeratorExtraFieldsMax = 4;

export const postApiAlphaCommunityModResponseModeratorsItemModeratorNoteMax = 50;



export const postApiAlphaCommunityModResponse = zod.object({
  "moderators": zod.array(zod.object({
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "moderator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommunityModResponseModeratorsItemModeratorExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommunityModResponseModeratorsItemModeratorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
})
}))
})

/**
 * @summary Get the list of banned users for a community.
 */
export const getApiAlphaCommunityModerateBansQueryLimitDefault = 10;export const getApiAlphaCommunityModerateBansQueryPageDefault = 1;

export const getApiAlphaCommunityModerateBansQueryParams = zod.object({
  "community_id": zod.number(),
  "limit": zod.number().default(getApiAlphaCommunityModerateBansQueryLimitDefault),
  "page": zod.number().default(getApiAlphaCommunityModerateBansQueryPageDefault)
})

export const getApiAlphaCommunityModerateBansResponseItemsItemBannedByExtraFieldsMax = 4;

export const getApiAlphaCommunityModerateBansResponseItemsItemBannedByNoteMax = 50;

export const getApiAlphaCommunityModerateBansResponseItemsItemBannedUserExtraFieldsMax = 4;

export const getApiAlphaCommunityModerateBansResponseItemsItemBannedUserNoteMax = 50;



export const getApiAlphaCommunityModerateBansResponse = zod.object({
  "items": zod.array(zod.object({
  "banned_by": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(getApiAlphaCommunityModerateBansResponseItemsItemBannedByExtraFieldsMax).optional(),
  "note": zod.string().max(getApiAlphaCommunityModerateBansResponseItemsItemBannedByNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}).optional(),
  "banned_user": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(getApiAlphaCommunityModerateBansResponseItemsItemBannedUserExtraFieldsMax).optional(),
  "note": zod.string().max(getApiAlphaCommunityModerateBansResponseItemsItemBannedUserNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}).optional(),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}).optional(),
  "expired": zod.boolean().optional(),
  "expired_at": zod.string().nullish(),
  "expires_at": zod.string().nullish(),
  "reason": zod.string().optional()
})).optional(),
  "next_page": zod.string().nullish()
})

/**
 * @summary Unban a user from a community.
 */
export const putApiAlphaCommunityModerateUnbanBody = zod.object({
  "community_id": zod.number(),
  "user_id": zod.number()
})

export const putApiAlphaCommunityModerateUnbanResponseBannedByExtraFieldsMax = 4;

export const putApiAlphaCommunityModerateUnbanResponseBannedByNoteMax = 50;

export const putApiAlphaCommunityModerateUnbanResponseBannedUserExtraFieldsMax = 4;

export const putApiAlphaCommunityModerateUnbanResponseBannedUserNoteMax = 50;



export const putApiAlphaCommunityModerateUnbanResponse = zod.object({
  "banned_by": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(putApiAlphaCommunityModerateUnbanResponseBannedByExtraFieldsMax).optional(),
  "note": zod.string().max(putApiAlphaCommunityModerateUnbanResponseBannedByNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}).optional(),
  "banned_user": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(putApiAlphaCommunityModerateUnbanResponseBannedUserExtraFieldsMax).optional(),
  "note": zod.string().max(putApiAlphaCommunityModerateUnbanResponseBannedUserNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}).optional(),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}).optional(),
  "expired": zod.boolean().optional(),
  "expired_at": zod.string().nullish(),
  "expires_at": zod.string().nullish(),
  "reason": zod.string().optional()
})

/**
 * @summary Ban a user from a community.
 */
export const postApiAlphaCommunityModerateBanBody = zod.object({
  "community_id": zod.number(),
  "reason": zod.string(),
  "user_id": zod.number(),
  "expires_at": zod.string().optional(),
  "permanent": zod.boolean().optional()
})

export const postApiAlphaCommunityModerateBanResponseBannedByExtraFieldsMax = 4;

export const postApiAlphaCommunityModerateBanResponseBannedByNoteMax = 50;

export const postApiAlphaCommunityModerateBanResponseBannedUserExtraFieldsMax = 4;

export const postApiAlphaCommunityModerateBanResponseBannedUserNoteMax = 50;



export const postApiAlphaCommunityModerateBanResponse = zod.object({
  "banned_by": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommunityModerateBanResponseBannedByExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommunityModerateBanResponseBannedByNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}).optional(),
  "banned_user": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommunityModerateBanResponseBannedUserExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommunityModerateBanResponseBannedUserNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}).optional(),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}).optional(),
  "expired": zod.boolean().optional(),
  "expired_at": zod.string().nullish(),
  "expires_at": zod.string().nullish(),
  "reason": zod.string().optional()
})

/**
 * @summary Mark or unmark a post as NSFW.
 */
export const postApiAlphaCommunityModeratePostNsfwBody = zod.object({
  "post_id": zod.number(),
  "nsfw_status": zod.boolean()
})

export const postApiAlphaCommunityModeratePostNsfwResponseCreatorExtraFieldsMax = 4;

export const postApiAlphaCommunityModeratePostNsfwResponseCreatorNoteMax = 50;

export const postApiAlphaCommunityModeratePostNsfwResponsePostEventMaxAttendeesDefault = 0;export const postApiAlphaCommunityModeratePostNsfwResponsePostEventParticipantCountDefault = 0;export const postApiAlphaCommunityModeratePostNsfwResponsePostEventFullDefault = false;export const postApiAlphaCommunityModeratePostNsfwResponsePostEventAnonymousParticipationDefault = false;export const postApiAlphaCommunityModeratePostNsfwResponsePostEventOnlineDefault = false;export const postApiAlphaCommunityModeratePostNsfwResponsePostEventEventFeeAmountDefault = 0;export const postApiAlphaCommunityModeratePostNsfwResponsePostPollLocalOnlyDefault = false;export const postApiAlphaCommunityModeratePostNsfwResponsePostPollChoicesItemNumVotesDefault = 0;export const postApiAlphaCommunityModeratePostNsfwResponsePostPollChoicesMax = 10;



export const postApiAlphaCommunityModeratePostNsfwResponse = zod.object({
  "banned_from_community": zod.boolean(),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "comments": zod.number(),
  "downvotes": zod.number(),
  "newest_comment_time": zod.string(),
  "post_id": zod.number(),
  "published": zod.string(),
  "score": zod.number(),
  "upvotes": zod.number(),
  "cross_posts": zod.number()
}),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommunityModeratePostNsfwResponseCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommunityModeratePostNsfwResponseCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "creator_banned_from_community": zod.boolean(),
  "creator_is_admin": zod.boolean(),
  "creator_is_moderator": zod.boolean(),
  "hidden": zod.boolean(),
  "post": zod.object({
  "ap_id": zod.string(),
  "community_id": zod.number(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "locked": zod.boolean(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "sticky": zod.boolean(),
  "instance_sticky": zod.boolean(),
  "title": zod.string(),
  "user_id": zod.number(),
  "alt_text": zod.string().optional(),
  "body": zod.string().optional(),
  "small_thumbnail_url": zod.string().optional(),
  "thumbnail_url": zod.string().optional(),
  "updated": zod.string().optional(),
  "url": zod.string().optional(),
  "image_details": zod.object({
  "width": zod.number().optional(),
  "height": zod.number().optional()
}).optional(),
  "cross_posts": zod.array(zod.object({
  "post_id": zod.number().optional(),
  "reply_count": zod.number().optional(),
  "community_name": zod.string().optional()
})).optional(),
  "post_type": zod.enum(['Link', 'Discussion', 'Image', 'Video', 'Poll', 'Event']),
  "tags": zod.string().nullish(),
  "flair": zod.string().nullish(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish(),
  "event": zod.object({
  "start": zod.string(),
  "end": zod.string().optional(),
  "timezone": zod.string().optional(),
  "max_attendees": zod.number().optional(),
  "participant_count": zod.number().optional(),
  "full": zod.boolean().optional(),
  "online_link": zod.string().nullish(),
  "join_mode": zod.string().optional().describe('free, restricted, external, invite'),
  "external_participation_url": zod.string().nullish(),
  "anonymous_participation": zod.boolean().optional(),
  "online": zod.boolean().optional(),
  "buy_tickets_link": zod.string().nullish(),
  "event_fee_currency": zod.string().optional(),
  "event_fee_amount": zod.number().optional(),
  "location": zod.record(zod.string(), zod.unknown()).nullish().describe('JSON object containing location details')
}).optional(),
  "poll": zod.object({
  "end_poll": zod.string().optional(),
  "mode": zod.enum(['single', 'multiple']).describe('single or multiple - determines whether people can vote for one or multiple options'),
  "local_only": zod.boolean().optional(),
  "latest_vote": zod.string().optional(),
  "choices": zod.array(zod.object({
  "id": zod.number(),
  "choice_text": zod.string(),
  "sort_order": zod.number(),
  "num_votes": zod.number().optional().describe('Value is ignored when creating\/editing a poll')
})).max(postApiAlphaCommunityModeratePostNsfwResponsePostPollChoicesMax),
  "my_votes": zod.array(zod.number()).optional()
}).optional()
}),
  "read": zod.boolean(),
  "saved": zod.boolean(),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending']),
  "unread_comments": zod.number(),
  "activity_alert": zod.boolean().optional(),
  "alt_text": zod.string().optional(),
  "my_vote": zod.number().optional(),
  "flair_list": zod.array(zod.object({
  "id": zod.number(),
  "community_id": zod.number(),
  "flair_title": zod.string(),
  "text_color": zod.string().describe('Hex color code for the text of the flair'),
  "background_color": zod.string().describe('Hex color code for the background of the flair'),
  "blur_images": zod.boolean(),
  "ap_id": zod.string().nullable().describe('Legacy tags that existed prior to 1.2 and some tags for remote communities might not have a defined ap_id')
})).optional().describe('See also the simpler \'flair\' on post which can be used when editing'),
  "can_auth_user_moderate": zod.boolean().optional()
})

/**
 * @summary Create a new post flair in the community
 */
export const postApiAlphaCommunityFlairBodyTextColorDefault = "#000000";export const postApiAlphaCommunityFlairBodyBackgroundColorDefault = "#DEDDDA";export const postApiAlphaCommunityFlairBodyBlurImagesDefault = false;

export const postApiAlphaCommunityFlairBody = zod.object({
  "community_id": zod.number(),
  "flair_title": zod.string(),
  "text_color": zod.string().default(postApiAlphaCommunityFlairBodyTextColorDefault).describe('Hex color code for the text of the flair.'),
  "background_color": zod.string().default(postApiAlphaCommunityFlairBodyBackgroundColorDefault).describe('Hex color code for the background of the flair.'),
  "blur_images": zod.boolean().optional()
})

export const postApiAlphaCommunityFlairResponse = zod.object({
  "id": zod.number(),
  "community_id": zod.number(),
  "flair_title": zod.string(),
  "text_color": zod.string().describe('Hex color code for the text of the flair'),
  "background_color": zod.string().describe('Hex color code for the background of the flair'),
  "blur_images": zod.boolean(),
  "ap_id": zod.string().nullable().describe('Legacy tags that existed prior to 1.2 and some tags for remote communities might not have a defined ap_id')
})

/**
 * @summary Edit an existing post flair in the community
 */
export const putApiAlphaCommunityFlairBody = zod.object({
  "flair_id": zod.number(),
  "flair_title": zod.string().optional(),
  "text_color": zod.string().optional().describe('Hex color code for the text of the flair.'),
  "background_color": zod.string().optional().describe('Hex color code for the background of the flair.'),
  "blur_images": zod.boolean().optional()
})

export const putApiAlphaCommunityFlairResponse = zod.object({
  "id": zod.number(),
  "community_id": zod.number(),
  "flair_title": zod.string(),
  "text_color": zod.string().describe('Hex color code for the text of the flair'),
  "background_color": zod.string().describe('Hex color code for the background of the flair'),
  "blur_images": zod.boolean(),
  "ap_id": zod.string().nullable().describe('Legacy tags that existed prior to 1.2 and some tags for remote communities might not have a defined ap_id')
})

/**
 * @summary Delete a post flair in a community
 */
export const postApiAlphaCommunityFlairDeleteBody = zod.object({
  "flair_id": zod.number()
})

export const postApiAlphaCommunityFlairDeleteResponseModeratorsItemModeratorExtraFieldsMax = 4;

export const postApiAlphaCommunityFlairDeleteResponseModeratorsItemModeratorNoteMax = 50;



export const postApiAlphaCommunityFlairDeleteResponse = zod.object({
  "community_view": zod.object({
  "activity_alert": zod.boolean(),
  "blocked": zod.boolean(),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "id": zod.number(),
  "post_count": zod.number(),
  "post_reply_count": zod.number(),
  "published": zod.string(),
  "subscriptions_count": zod.number(),
  "total_subscriptions_count": zod.number(),
  "active_daily": zod.number().optional(),
  "active_weekly": zod.number().optional(),
  "active_monthly": zod.number().optional(),
  "active_6monthly": zod.number().optional()
}),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending']),
  "flair_list": zod.array(zod.object({
  "id": zod.number(),
  "community_id": zod.number(),
  "flair_title": zod.string(),
  "text_color": zod.string().describe('Hex color code for the text of the flair'),
  "background_color": zod.string().describe('Hex color code for the background of the flair'),
  "blur_images": zod.boolean(),
  "ap_id": zod.string().nullable().describe('Legacy tags that existed prior to 1.2 and some tags for remote communities might not have a defined ap_id')
})).optional()
}),
  "discussion_languages": zod.array(zod.number()),
  "moderators": zod.array(zod.object({
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "moderator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommunityFlairDeleteResponseModeratorsItemModeratorExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommunityFlairDeleteResponseModeratorsItemModeratorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
})
})),
  "site": zod.object({
  "actor_id": zod.string(),
  "announcement_md": zod.string().optional().describe('The banner at the top of the home page'),
  "announcement": zod.string().optional().describe('The banner at the top of the home page'),
  "name": zod.string(),
  "all_languages": zod.array(zod.object({
  "code": zod.string().optional(),
  "id": zod.number().optional(),
  "name": zod.string().optional()
})).optional(),
  "description": zod.string().optional(),
  "enable_downvotes": zod.boolean().optional(),
  "icon": zod.string().nullish(),
  "registration_mode": zod.enum(['Closed', 'RequireApplication', 'Open']).optional(),
  "sidebar": zod.string().optional(),
  "sidebar_md": zod.string().optional(),
  "user_count": zod.number().optional()
}).optional()
})

