/**
 * Generated by orval
 * Do not edit manually.
 */
import type {
  GetApiAlphaTopicListParams,
  TopicListResponse
} from '../../schemas';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary Get list of topics
 */
export const getGetApiAlphaTopicListUrl = (params?: GetApiAlphaTopicListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/topic/list?${stringifiedParams}` : `/api/alpha/topic/list`
}

export const getApiAlphaTopicList = async (params?: GetApiAlphaTopicListParams, options?: RequestInit): Promise<TopicListResponse> => {
  
  return customFetch<TopicListResponse>(getGetApiAlphaTopicListUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


