/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type {
  DefaultError,
  DomainBlockRequest,
  DomainBlockResponse,
  GetApiAlphaUserMediaParams,
  GetApiAlphaUserMentionsParams,
  GetApiAlphaUserNotificationsParams,
  GetApiAlphaUserParams,
  GetApiAlphaUserRepliesParams,
  GetUserResponse,
  UnprocessableEntityResponse,
  UserBanRequest,
  UserBanResponse,
  UserBlockRequest,
  UserBlockResponse,
  UserLoginRequest,
  UserLoginResponse,
  UserMarkAllNotifsReadResponse,
  UserMarkAllReadResponse,
  UserMeResponse,
  UserMediaResponse,
  UserMentionsResponse,
  UserNotificationItemView,
  UserNotificationStateRequest,
  UserNotificationsCountResponse,
  UserNotificationsResponse,
  UserRepliesResponse,
  UserSaveSettingsRequest,
  UserSaveSettingsResponse,
  UserSetFlairRequest,
  UserSetFlairResponse,
  UserSetNoteRequest,
  UserSetNoteResponse,
  UserSubscribeRequest,
  UserSubscribeResponse,
  UserUnbanRequest,
  UserUnreadCountsResponse
} from '../../schemas';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary Block or unblock a domain
 */
export type postApiAlphaDomainBlockResponse200 = {
  data: DomainBlockResponse
  status: 200
}

export type postApiAlphaDomainBlockResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaDomainBlockResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaDomainBlockResponseSuccess = (postApiAlphaDomainBlockResponse200) & {
  headers: Headers;
};
export type postApiAlphaDomainBlockResponseError = (postApiAlphaDomainBlockResponse400 | postApiAlphaDomainBlockResponse422) & {
  headers: Headers;
};

export type postApiAlphaDomainBlockResponse = (postApiAlphaDomainBlockResponseSuccess | postApiAlphaDomainBlockResponseError)

export const getPostApiAlphaDomainBlockUrl = () => {


  

  return `/api/alpha/domain/block`
}

export const postApiAlphaDomainBlock = async (domainBlockRequest: DomainBlockRequest, options?: RequestInit): Promise<postApiAlphaDomainBlockResponse> => {
  
  return customFetch<postApiAlphaDomainBlockResponse>(getPostApiAlphaDomainBlockUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      domainBlockRequest,)
  }
);}


/**
 * @summary Get the details for a person
 */
export type getApiAlphaUserResponse200 = {
  data: GetUserResponse
  status: 200
}

export type getApiAlphaUserResponse400 = {
  data: DefaultError
  status: 400
}

export type getApiAlphaUserResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type getApiAlphaUserResponseSuccess = (getApiAlphaUserResponse200) & {
  headers: Headers;
};
export type getApiAlphaUserResponseError = (getApiAlphaUserResponse400 | getApiAlphaUserResponse422) & {
  headers: Headers;
};

export type getApiAlphaUserResponse = (getApiAlphaUserResponseSuccess | getApiAlphaUserResponseError)

export const getGetApiAlphaUserUrl = (params?: GetApiAlphaUserParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/user?${stringifiedParams}` : `/api/alpha/user`
}

export const getApiAlphaUser = async (params?: GetApiAlphaUserParams, options?: RequestInit): Promise<getApiAlphaUserResponse> => {
  
  return customFetch<getApiAlphaUserResponse>(getGetApiAlphaUserUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get the details for the current user
 */
export type getApiAlphaUserMeResponse200 = {
  data: UserMeResponse
  status: 200
}

export type getApiAlphaUserMeResponse400 = {
  data: DefaultError
  status: 400
}
    
export type getApiAlphaUserMeResponseSuccess = (getApiAlphaUserMeResponse200) & {
  headers: Headers;
};
export type getApiAlphaUserMeResponseError = (getApiAlphaUserMeResponse400) & {
  headers: Headers;
};

export type getApiAlphaUserMeResponse = (getApiAlphaUserMeResponseSuccess | getApiAlphaUserMeResponseError)

export const getGetApiAlphaUserMeUrl = () => {


  

  return `/api/alpha/user/me`
}

export const getApiAlphaUserMe = async ( options?: RequestInit): Promise<getApiAlphaUserMeResponse> => {
  
  return customFetch<getApiAlphaUserMeResponse>(getGetApiAlphaUserMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Log into PieFed
 */
export type postApiAlphaUserLoginResponse200 = {
  data: UserLoginResponse
  status: 200
}

export type postApiAlphaUserLoginResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaUserLoginResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type postApiAlphaUserLoginResponse429 = {
  data: DefaultError
  status: 429
}
    
export type postApiAlphaUserLoginResponseSuccess = (postApiAlphaUserLoginResponse200) & {
  headers: Headers;
};
export type postApiAlphaUserLoginResponseError = (postApiAlphaUserLoginResponse400 | postApiAlphaUserLoginResponse422 | postApiAlphaUserLoginResponse429) & {
  headers: Headers;
};

export type postApiAlphaUserLoginResponse = (postApiAlphaUserLoginResponseSuccess | postApiAlphaUserLoginResponseError)

export const getPostApiAlphaUserLoginUrl = () => {


  

  return `/api/alpha/user/login`
}

export const postApiAlphaUserLogin = async (userLoginRequest: UserLoginRequest, options?: RequestInit): Promise<postApiAlphaUserLoginResponse> => {
  
  return customFetch<postApiAlphaUserLoginResponse>(getPostApiAlphaUserLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userLoginRequest,)
  }
);}


/**
 * @summary Get your unread counts
 */
export type getApiAlphaUserUnreadCountResponse200 = {
  data: UserUnreadCountsResponse
  status: 200
}

export type getApiAlphaUserUnreadCountResponse400 = {
  data: DefaultError
  status: 400
}
    
export type getApiAlphaUserUnreadCountResponseSuccess = (getApiAlphaUserUnreadCountResponse200) & {
  headers: Headers;
};
export type getApiAlphaUserUnreadCountResponseError = (getApiAlphaUserUnreadCountResponse400) & {
  headers: Headers;
};

export type getApiAlphaUserUnreadCountResponse = (getApiAlphaUserUnreadCountResponseSuccess | getApiAlphaUserUnreadCountResponseError)

export const getGetApiAlphaUserUnreadCountUrl = () => {


  

  return `/api/alpha/user/unread_count`
}

export const getApiAlphaUserUnreadCount = async ( options?: RequestInit): Promise<getApiAlphaUserUnreadCountResponse> => {
  
  return customFetch<getApiAlphaUserUnreadCountResponse>(getGetApiAlphaUserUnreadCountUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get comment replies
 */
export type getApiAlphaUserRepliesResponse200 = {
  data: UserRepliesResponse
  status: 200
}

export type getApiAlphaUserRepliesResponse400 = {
  data: DefaultError
  status: 400
}

export type getApiAlphaUserRepliesResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type getApiAlphaUserRepliesResponseSuccess = (getApiAlphaUserRepliesResponse200) & {
  headers: Headers;
};
export type getApiAlphaUserRepliesResponseError = (getApiAlphaUserRepliesResponse400 | getApiAlphaUserRepliesResponse422) & {
  headers: Headers;
};

export type getApiAlphaUserRepliesResponse = (getApiAlphaUserRepliesResponseSuccess | getApiAlphaUserRepliesResponseError)

export const getGetApiAlphaUserRepliesUrl = (params?: GetApiAlphaUserRepliesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/user/replies?${stringifiedParams}` : `/api/alpha/user/replies`
}

export const getApiAlphaUserReplies = async (params?: GetApiAlphaUserRepliesParams, options?: RequestInit): Promise<getApiAlphaUserRepliesResponse> => {
  
  return customFetch<getApiAlphaUserRepliesResponse>(getGetApiAlphaUserRepliesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get mentions of your account made in comments
 */
export type getApiAlphaUserMentionsResponse200 = {
  data: UserMentionsResponse
  status: 200
}

export type getApiAlphaUserMentionsResponse400 = {
  data: DefaultError
  status: 400
}

export type getApiAlphaUserMentionsResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type getApiAlphaUserMentionsResponseSuccess = (getApiAlphaUserMentionsResponse200) & {
  headers: Headers;
};
export type getApiAlphaUserMentionsResponseError = (getApiAlphaUserMentionsResponse400 | getApiAlphaUserMentionsResponse422) & {
  headers: Headers;
};

export type getApiAlphaUserMentionsResponse = (getApiAlphaUserMentionsResponseSuccess | getApiAlphaUserMentionsResponseError)

export const getGetApiAlphaUserMentionsUrl = (params?: GetApiAlphaUserMentionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/user/mentions?${stringifiedParams}` : `/api/alpha/user/mentions`
}

export const getApiAlphaUserMentions = async (params?: GetApiAlphaUserMentionsParams, options?: RequestInit): Promise<getApiAlphaUserMentionsResponse> => {
  
  return customFetch<getApiAlphaUserMentionsResponse>(getGetApiAlphaUserMentionsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get media the current user has uploaded
 */
export type getApiAlphaUserMediaResponse200 = {
  data: UserMediaResponse
  status: 200
}

export type getApiAlphaUserMediaResponse400 = {
  data: DefaultError
  status: 400
}

export type getApiAlphaUserMediaResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type getApiAlphaUserMediaResponseSuccess = (getApiAlphaUserMediaResponse200) & {
  headers: Headers;
};
export type getApiAlphaUserMediaResponseError = (getApiAlphaUserMediaResponse400 | getApiAlphaUserMediaResponse422) & {
  headers: Headers;
};

export type getApiAlphaUserMediaResponse = (getApiAlphaUserMediaResponseSuccess | getApiAlphaUserMediaResponseError)

export const getGetApiAlphaUserMediaUrl = (params?: GetApiAlphaUserMediaParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/user/media?${stringifiedParams}` : `/api/alpha/user/media`
}

export const getApiAlphaUserMedia = async (params?: GetApiAlphaUserMediaParams, options?: RequestInit): Promise<getApiAlphaUserMediaResponse> => {
  
  return customFetch<getApiAlphaUserMediaResponse>(getGetApiAlphaUserMediaUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Block or unblock a person
 */
export type postApiAlphaUserBlockResponse200 = {
  data: UserBlockResponse
  status: 200
}

export type postApiAlphaUserBlockResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaUserBlockResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaUserBlockResponseSuccess = (postApiAlphaUserBlockResponse200) & {
  headers: Headers;
};
export type postApiAlphaUserBlockResponseError = (postApiAlphaUserBlockResponse400 | postApiAlphaUserBlockResponse422) & {
  headers: Headers;
};

export type postApiAlphaUserBlockResponse = (postApiAlphaUserBlockResponseSuccess | postApiAlphaUserBlockResponseError)

export const getPostApiAlphaUserBlockUrl = () => {


  

  return `/api/alpha/user/block`
}

export const postApiAlphaUserBlock = async (userBlockRequest: UserBlockRequest, options?: RequestInit): Promise<postApiAlphaUserBlockResponse> => {
  
  return customFetch<postApiAlphaUserBlockResponse>(getPostApiAlphaUserBlockUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userBlockRequest,)
  }
);}


/**
 * @summary Mark all notifications and messages as read
 */
export type postApiAlphaUserMarkAllAsReadResponse200 = {
  data: UserMarkAllReadResponse
  status: 200
}

export type postApiAlphaUserMarkAllAsReadResponse400 = {
  data: DefaultError
  status: 400
}
    
export type postApiAlphaUserMarkAllAsReadResponseSuccess = (postApiAlphaUserMarkAllAsReadResponse200) & {
  headers: Headers;
};
export type postApiAlphaUserMarkAllAsReadResponseError = (postApiAlphaUserMarkAllAsReadResponse400) & {
  headers: Headers;
};

export type postApiAlphaUserMarkAllAsReadResponse = (postApiAlphaUserMarkAllAsReadResponseSuccess | postApiAlphaUserMarkAllAsReadResponseError)

export const getPostApiAlphaUserMarkAllAsReadUrl = () => {


  

  return `/api/alpha/user/mark_all_as_read`
}

export const postApiAlphaUserMarkAllAsRead = async ( options?: RequestInit): Promise<postApiAlphaUserMarkAllAsReadResponse> => {
  
  return customFetch<postApiAlphaUserMarkAllAsReadResponse>(getPostApiAlphaUserMarkAllAsReadUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Subscribe or unsubscribe to activites of another user
 */
export type putApiAlphaUserSubscribeResponse200 = {
  data: UserSubscribeResponse
  status: 200
}

export type putApiAlphaUserSubscribeResponse400 = {
  data: DefaultError
  status: 400
}

export type putApiAlphaUserSubscribeResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type putApiAlphaUserSubscribeResponseSuccess = (putApiAlphaUserSubscribeResponse200) & {
  headers: Headers;
};
export type putApiAlphaUserSubscribeResponseError = (putApiAlphaUserSubscribeResponse400 | putApiAlphaUserSubscribeResponse422) & {
  headers: Headers;
};

export type putApiAlphaUserSubscribeResponse = (putApiAlphaUserSubscribeResponseSuccess | putApiAlphaUserSubscribeResponseError)

export const getPutApiAlphaUserSubscribeUrl = () => {


  

  return `/api/alpha/user/subscribe`
}

export const putApiAlphaUserSubscribe = async (userSubscribeRequest: UserSubscribeRequest, options?: RequestInit): Promise<putApiAlphaUserSubscribeResponse> => {
  
  return customFetch<putApiAlphaUserSubscribeResponse>(getPutApiAlphaUserSubscribeUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userSubscribeRequest,)
  }
);}


/**
 * @summary Save your user settings
 */
export type putApiAlphaUserSaveUserSettingsResponse200 = {
  data: UserSaveSettingsResponse
  status: 200
}

export type putApiAlphaUserSaveUserSettingsResponse400 = {
  data: DefaultError
  status: 400
}

export type putApiAlphaUserSaveUserSettingsResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type putApiAlphaUserSaveUserSettingsResponseSuccess = (putApiAlphaUserSaveUserSettingsResponse200) & {
  headers: Headers;
};
export type putApiAlphaUserSaveUserSettingsResponseError = (putApiAlphaUserSaveUserSettingsResponse400 | putApiAlphaUserSaveUserSettingsResponse422) & {
  headers: Headers;
};

export type putApiAlphaUserSaveUserSettingsResponse = (putApiAlphaUserSaveUserSettingsResponseSuccess | putApiAlphaUserSaveUserSettingsResponseError)

export const getPutApiAlphaUserSaveUserSettingsUrl = () => {


  

  return `/api/alpha/user/save_user_settings`
}

export const putApiAlphaUserSaveUserSettings = async (userSaveSettingsRequest: UserSaveSettingsRequest, options?: RequestInit): Promise<putApiAlphaUserSaveUserSettingsResponse> => {
  
  return customFetch<putApiAlphaUserSaveUserSettingsResponse>(getPutApiAlphaUserSaveUserSettingsUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userSaveSettingsRequest,)
  }
);}


/**
 * @summary Get your user notifications (not all notification types supported yet)
 */
export type getApiAlphaUserNotificationsResponse200 = {
  data: UserNotificationsResponse
  status: 200
}

export type getApiAlphaUserNotificationsResponse400 = {
  data: DefaultError
  status: 400
}

export type getApiAlphaUserNotificationsResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type getApiAlphaUserNotificationsResponseSuccess = (getApiAlphaUserNotificationsResponse200) & {
  headers: Headers;
};
export type getApiAlphaUserNotificationsResponseError = (getApiAlphaUserNotificationsResponse400 | getApiAlphaUserNotificationsResponse422) & {
  headers: Headers;
};

export type getApiAlphaUserNotificationsResponse = (getApiAlphaUserNotificationsResponseSuccess | getApiAlphaUserNotificationsResponseError)

export const getGetApiAlphaUserNotificationsUrl = (params: GetApiAlphaUserNotificationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/user/notifications?${stringifiedParams}` : `/api/alpha/user/notifications`
}

export const getApiAlphaUserNotifications = async (params: GetApiAlphaUserNotificationsParams, options?: RequestInit): Promise<getApiAlphaUserNotificationsResponse> => {
  
  return customFetch<getApiAlphaUserNotificationsResponse>(getGetApiAlphaUserNotificationsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Set the read status of a given notification (not all notification types supported yet)
 */
export type putApiAlphaUserNotificationStateResponse200 = {
  data: UserNotificationItemView
  status: 200
}

export type putApiAlphaUserNotificationStateResponse400 = {
  data: DefaultError
  status: 400
}

export type putApiAlphaUserNotificationStateResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type putApiAlphaUserNotificationStateResponseSuccess = (putApiAlphaUserNotificationStateResponse200) & {
  headers: Headers;
};
export type putApiAlphaUserNotificationStateResponseError = (putApiAlphaUserNotificationStateResponse400 | putApiAlphaUserNotificationStateResponse422) & {
  headers: Headers;
};

export type putApiAlphaUserNotificationStateResponse = (putApiAlphaUserNotificationStateResponseSuccess | putApiAlphaUserNotificationStateResponseError)

export const getPutApiAlphaUserNotificationStateUrl = () => {


  

  return `/api/alpha/user/notification_state`
}

export const putApiAlphaUserNotificationState = async (userNotificationStateRequest: UserNotificationStateRequest, options?: RequestInit): Promise<putApiAlphaUserNotificationStateResponse> => {
  
  return customFetch<putApiAlphaUserNotificationStateResponse>(getPutApiAlphaUserNotificationStateUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userNotificationStateRequest,)
  }
);}


/**
 * @summary Get user unread notifications count
 */
export type getApiAlphaUserNotificationsCountResponse200 = {
  data: UserNotificationsCountResponse
  status: 200
}

export type getApiAlphaUserNotificationsCountResponse400 = {
  data: DefaultError
  status: 400
}
    
export type getApiAlphaUserNotificationsCountResponseSuccess = (getApiAlphaUserNotificationsCountResponse200) & {
  headers: Headers;
};
export type getApiAlphaUserNotificationsCountResponseError = (getApiAlphaUserNotificationsCountResponse400) & {
  headers: Headers;
};

export type getApiAlphaUserNotificationsCountResponse = (getApiAlphaUserNotificationsCountResponseSuccess | getApiAlphaUserNotificationsCountResponseError)

export const getGetApiAlphaUserNotificationsCountUrl = () => {


  

  return `/api/alpha/user/notifications_count`
}

export const getApiAlphaUserNotificationsCount = async ( options?: RequestInit): Promise<getApiAlphaUserNotificationsCountResponse> => {
  
  return customFetch<getApiAlphaUserNotificationsCountResponse>(getGetApiAlphaUserNotificationsCountUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Mark all notifications as read
 */
export type putApiAlphaUserMarkAllNotificationsReadResponse200 = {
  data: UserMarkAllNotifsReadResponse
  status: 200
}

export type putApiAlphaUserMarkAllNotificationsReadResponse400 = {
  data: DefaultError
  status: 400
}
    
export type putApiAlphaUserMarkAllNotificationsReadResponseSuccess = (putApiAlphaUserMarkAllNotificationsReadResponse200) & {
  headers: Headers;
};
export type putApiAlphaUserMarkAllNotificationsReadResponseError = (putApiAlphaUserMarkAllNotificationsReadResponse400) & {
  headers: Headers;
};

export type putApiAlphaUserMarkAllNotificationsReadResponse = (putApiAlphaUserMarkAllNotificationsReadResponseSuccess | putApiAlphaUserMarkAllNotificationsReadResponseError)

export const getPutApiAlphaUserMarkAllNotificationsReadUrl = () => {


  

  return `/api/alpha/user/mark_all_notifications_read`
}

export const putApiAlphaUserMarkAllNotificationsRead = async ( options?: RequestInit): Promise<putApiAlphaUserMarkAllNotificationsReadResponse> => {
  
  return customFetch<putApiAlphaUserMarkAllNotificationsReadResponse>(getPutApiAlphaUserMarkAllNotificationsReadUrl(),
  {      
    ...options,
    method: 'PUT'
    
    
  }
);}


/**
 * @summary Verify username/password credentials
 */
export type postApiAlphaUserVerifyCredentialsResponse200 = {
  data: void
  status: 200
}

export type postApiAlphaUserVerifyCredentialsResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaUserVerifyCredentialsResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaUserVerifyCredentialsResponseSuccess = (postApiAlphaUserVerifyCredentialsResponse200) & {
  headers: Headers;
};
export type postApiAlphaUserVerifyCredentialsResponseError = (postApiAlphaUserVerifyCredentialsResponse400 | postApiAlphaUserVerifyCredentialsResponse422) & {
  headers: Headers;
};

export type postApiAlphaUserVerifyCredentialsResponse = (postApiAlphaUserVerifyCredentialsResponseSuccess | postApiAlphaUserVerifyCredentialsResponseError)

export const getPostApiAlphaUserVerifyCredentialsUrl = () => {


  

  return `/api/alpha/user/verify_credentials`
}

export const postApiAlphaUserVerifyCredentials = async (userLoginRequest: UserLoginRequest, options?: RequestInit): Promise<postApiAlphaUserVerifyCredentialsResponse> => {
  
  return customFetch<postApiAlphaUserVerifyCredentialsResponse>(getPostApiAlphaUserVerifyCredentialsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userLoginRequest,)
  }
);}


/**
 * @summary Set your flair for a community
 */
export type postApiAlphaUserSetFlairResponse200 = {
  data: UserSetFlairResponse
  status: 200
}

export type postApiAlphaUserSetFlairResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaUserSetFlairResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaUserSetFlairResponseSuccess = (postApiAlphaUserSetFlairResponse200) & {
  headers: Headers;
};
export type postApiAlphaUserSetFlairResponseError = (postApiAlphaUserSetFlairResponse400 | postApiAlphaUserSetFlairResponse422) & {
  headers: Headers;
};

export type postApiAlphaUserSetFlairResponse = (postApiAlphaUserSetFlairResponseSuccess | postApiAlphaUserSetFlairResponseError)

export const getPostApiAlphaUserSetFlairUrl = () => {


  

  return `/api/alpha/user/set_flair`
}

export const postApiAlphaUserSetFlair = async (userSetFlairRequest: UserSetFlairRequest, options?: RequestInit): Promise<postApiAlphaUserSetFlairResponse> => {
  
  return customFetch<postApiAlphaUserSetFlairResponse>(getPostApiAlphaUserSetFlairUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userSetFlairRequest,)
  }
);}


/**
 * @summary Set a note for a user
 */
export type postApiAlphaUserNoteResponse200 = {
  data: UserSetNoteResponse
  status: 200
}

export type postApiAlphaUserNoteResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaUserNoteResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaUserNoteResponseSuccess = (postApiAlphaUserNoteResponse200) & {
  headers: Headers;
};
export type postApiAlphaUserNoteResponseError = (postApiAlphaUserNoteResponse400 | postApiAlphaUserNoteResponse422) & {
  headers: Headers;
};

export type postApiAlphaUserNoteResponse = (postApiAlphaUserNoteResponseSuccess | postApiAlphaUserNoteResponseError)

export const getPostApiAlphaUserNoteUrl = () => {


  

  return `/api/alpha/user/note`
}

export const postApiAlphaUserNote = async (userSetNoteRequest: UserSetNoteRequest, options?: RequestInit): Promise<postApiAlphaUserNoteResponse> => {
  
  return customFetch<postApiAlphaUserNoteResponse>(getPostApiAlphaUserNoteUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userSetNoteRequest,)
  }
);}


/**
 * @summary Ban a user
 */
export type postApiAlphaUserBanResponse200 = {
  data: UserBanResponse
  status: 200
}

export type postApiAlphaUserBanResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaUserBanResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaUserBanResponseSuccess = (postApiAlphaUserBanResponse200) & {
  headers: Headers;
};
export type postApiAlphaUserBanResponseError = (postApiAlphaUserBanResponse400 | postApiAlphaUserBanResponse422) & {
  headers: Headers;
};

export type postApiAlphaUserBanResponse = (postApiAlphaUserBanResponseSuccess | postApiAlphaUserBanResponseError)

export const getPostApiAlphaUserBanUrl = () => {


  

  return `/api/alpha/user/ban`
}

export const postApiAlphaUserBan = async (userBanRequest: UserBanRequest, options?: RequestInit): Promise<postApiAlphaUserBanResponse> => {
  
  return customFetch<postApiAlphaUserBanResponse>(getPostApiAlphaUserBanUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userBanRequest,)
  }
);}


/**
 * @summary Unban a user
 */
export type postApiAlphaUserUnbanResponse200 = {
  data: UserBanResponse
  status: 200
}

export type postApiAlphaUserUnbanResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaUserUnbanResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaUserUnbanResponseSuccess = (postApiAlphaUserUnbanResponse200) & {
  headers: Headers;
};
export type postApiAlphaUserUnbanResponseError = (postApiAlphaUserUnbanResponse400 | postApiAlphaUserUnbanResponse422) & {
  headers: Headers;
};

export type postApiAlphaUserUnbanResponse = (postApiAlphaUserUnbanResponseSuccess | postApiAlphaUserUnbanResponseError)

export const getPostApiAlphaUserUnbanUrl = () => {


  

  return `/api/alpha/user/unban`
}

export const postApiAlphaUserUnban = async (userUnbanRequest: UserUnbanRequest, options?: RequestInit): Promise<postApiAlphaUserUnbanResponse> => {
  
  return customFetch<postApiAlphaUserUnbanResponse>(getPostApiAlphaUserUnbanUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userUnbanRequest,)
  }
);}


