/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type {
  DefaultError,
  GetApiAlphaAdminRegistrationApplicationListParams,
  GetRegistrationListResponse,
  RegistrationApproveRequest,
  UnprocessableEntityResponse
} from '../../schemas';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary Get the list of applications ready for admin review
 */
export type getApiAlphaAdminRegistrationApplicationListResponse200 = {
  data: GetRegistrationListResponse
  status: 200
}

export type getApiAlphaAdminRegistrationApplicationListResponse400 = {
  data: DefaultError
  status: 400
}

export type getApiAlphaAdminRegistrationApplicationListResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type getApiAlphaAdminRegistrationApplicationListResponseSuccess = (getApiAlphaAdminRegistrationApplicationListResponse200) & {
  headers: Headers;
};
export type getApiAlphaAdminRegistrationApplicationListResponseError = (getApiAlphaAdminRegistrationApplicationListResponse400 | getApiAlphaAdminRegistrationApplicationListResponse422) & {
  headers: Headers;
};

export type getApiAlphaAdminRegistrationApplicationListResponse = (getApiAlphaAdminRegistrationApplicationListResponseSuccess | getApiAlphaAdminRegistrationApplicationListResponseError)

export const getGetApiAlphaAdminRegistrationApplicationListUrl = (params?: GetApiAlphaAdminRegistrationApplicationListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/admin/registration_application/list?${stringifiedParams}` : `/api/alpha/admin/registration_application/list`
}

export const getApiAlphaAdminRegistrationApplicationList = async (params?: GetApiAlphaAdminRegistrationApplicationListParams, options?: RequestInit): Promise<getApiAlphaAdminRegistrationApplicationListResponse> => {
  
  return customFetch<getApiAlphaAdminRegistrationApplicationListResponse>(getGetApiAlphaAdminRegistrationApplicationListUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Approve or deny a registration
 */
export type putApiAlphaAdminRegistrationApplicationApproveResponse200 = {
  data: void
  status: 200
}

export type putApiAlphaAdminRegistrationApplicationApproveResponse400 = {
  data: DefaultError
  status: 400
}

export type putApiAlphaAdminRegistrationApplicationApproveResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type putApiAlphaAdminRegistrationApplicationApproveResponseSuccess = (putApiAlphaAdminRegistrationApplicationApproveResponse200) & {
  headers: Headers;
};
export type putApiAlphaAdminRegistrationApplicationApproveResponseError = (putApiAlphaAdminRegistrationApplicationApproveResponse400 | putApiAlphaAdminRegistrationApplicationApproveResponse422) & {
  headers: Headers;
};

export type putApiAlphaAdminRegistrationApplicationApproveResponse = (putApiAlphaAdminRegistrationApplicationApproveResponseSuccess | putApiAlphaAdminRegistrationApplicationApproveResponseError)

export const getPutApiAlphaAdminRegistrationApplicationApproveUrl = () => {


  

  return `/api/alpha/admin/registration_application/approve`
}

export const putApiAlphaAdminRegistrationApplicationApprove = async (registrationApproveRequest: RegistrationApproveRequest, options?: RequestInit): Promise<putApiAlphaAdminRegistrationApplicationApproveResponse> => {
  
  return customFetch<putApiAlphaAdminRegistrationApplicationApproveResponse>(getPutApiAlphaAdminRegistrationApplicationApproveUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registrationApproveRequest,)
  }
);}


