/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type {
  GetApiAlphaAdminRegistrationApplicationListParams,
  GetRegistrationListResponse,
  RegistrationApproveRequest
} from '../../schemas';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary Get the list of applications ready for admin review
 */
export const getGetApiAlphaAdminRegistrationApplicationListUrl = (params?: GetApiAlphaAdminRegistrationApplicationListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/admin/registration_application/list?${stringifiedParams}` : `/api/alpha/admin/registration_application/list`
}

export const getApiAlphaAdminRegistrationApplicationList = async (params?: GetApiAlphaAdminRegistrationApplicationListParams, options?: RequestInit): Promise<GetRegistrationListResponse> => {
  
  return customFetch<GetRegistrationListResponse>(getGetApiAlphaAdminRegistrationApplicationListUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Approve or deny a registration
 */
export const getPutApiAlphaAdminRegistrationApplicationApproveUrl = () => {


  

  return `/api/alpha/admin/registration_application/approve`
}

export const putApiAlphaAdminRegistrationApplicationApprove = async (registrationApproveRequest: RegistrationApproveRequest, options?: RequestInit): Promise<void> => {
  
  return customFetch<void>(getPutApiAlphaAdminRegistrationApplicationApproveUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registrationApproveRequest,)
  }
);}


