/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { AdminPurgeComment } from './adminPurgeComment';
import type { Person } from './person';
import type { Post } from './post';

export interface AdminPurgeCommentView {
  admin_purge_comment: AdminPurgeComment;
  admin?: Person;
  post: Post;
}
