/**
 * Generated by orval
 * Do not edit manually.
 */
import type { AdminPurgePost } from './adminPurgePost';
import type { Person } from './person';
import type { Community } from './community';

export interface AdminPurgePostView {
  admin_purge_post: AdminPurgePost;
  admin?: Person;
  community: Community;
}
