/**
 * Generated by orval
 * Do not edit manually.
 */
import type { AdminPurgeCommunityReason } from './adminPurgeCommunityReason';

export interface AdminPurgeCommunity {
  id: number;
  admin_person_id: number;
  reason?: AdminPurgeCommunityReason;
  when_: string;
}
