/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { AdminPurgePostCommunityId } from './adminPurgePostCommunityId';
import type { AdminPurgePostReason } from './adminPurgePostReason';

export interface AdminPurgePost {
  id: number;
  admin_person_id: number;
  community_id: AdminPurgePostCommunityId;
  reason?: AdminPurgePostReason;
  when_: string;
}
