/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { AdminPurgePersonReason } from './adminPurgePersonReason';

export interface AdminPurgePerson {
  id: number;
  admin_person_id: number;
  reason?: AdminPurgePersonReason;
  when_: string;
}
