/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { AdminPurgeCommentReason } from './adminPurgeCommentReason';

export interface AdminPurgeComment {
  id: number;
  admin_person_id: number;
  post_id: number;
  reason?: AdminPurgeCommentReason;
  when_: string;
}
