/**
 * Generated by orval
 * Do not edit manually.
 */
import type { AdminPurgeCommunity } from './adminPurgeCommunity';
import type { Person } from './person';

export interface AdminPurgeCommunityView {
  admin_purge_community: AdminPurgeCommunity;
  admin?: Person;
}
