/**
 * Generated by orval
 * Do not edit manually.
 */
import type { AdminPurgePerson } from './adminPurgePerson';
import type { Person } from './person';

export interface AdminPurgePersonView {
  admin_purge_person: AdminPurgePerson;
  admin?: Person;
}
