/**
 * Generated by orval
 * Do not edit manually.
 */
import type { CommunityView } from './communityView';

export interface BlockCommunityResponse {
  community_view: CommunityView;
  blocked: boolean;
}
