/**
 * Generated by orval
 * Do not edit manually.
 */

export interface CommentAggregates {
  child_count: number;
  comment_id: number;
  downvotes: number;
  published: string;
  score: number;
  upvotes: number;
}
