/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

/**
 * Legacy tags that existed prior to 1.2 and some tags for remote communities might not have a defined ap_id
 */
export type CommunityFlairCreateResponseApId = string | null;
