/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export interface CommentReply {
  id: number;
  comment_id: number;
  published: string;
  read: boolean;
  recipient_id: number;
}
