/**
 * Generated by orval
 * Do not edit manually.
 */

export type CommentReplyViewSubscribed = typeof CommentReplyViewSubscribed[keyof typeof CommentReplyViewSubscribed];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommentReplyViewSubscribed = {
  Subscribed: 'Subscribed',
  NotSubscribed: 'NotSubscribed',
  Pending: 'Pending',
} as const;
