/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export interface CommunityAggregates {
  id: number;
  post_count: number;
  post_reply_count: number;
  published: string;
  subscriptions_count: number;
  total_subscriptions_count: number;
  active_daily?: number;
  active_weekly?: number;
  active_monthly?: number;
  active_6monthly?: number;
}
