/**
 * Generated by orval
 * Do not edit manually.
 */
import type { Community } from './community';
import type { CommunityAggregates } from './communityAggregates';
import type { CommunityViewSubscribed } from './communityViewSubscribed';
import type { CommunityFlair } from './communityFlair';

export interface CommunityView {
  activity_alert: boolean;
  blocked: boolean;
  community: Community;
  counts: CommunityAggregates;
  subscribed: CommunityViewSubscribed;
  flair_list?: CommunityFlair[];
}
