/**
 * Generated by orval
 * Do not edit manually.
 */
import type { CommunityModerationBanItem } from './communityModerationBanItem';
import type { CommunityModerationBansListResponseNextPage } from './communityModerationBansListResponseNextPage';

export interface CommunityModerationBansListResponse {
  items?: CommunityModerationBanItem[];
  next_page?: CommunityModerationBansListResponseNextPage;
}
