/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { Person } from './person';
import type { Community } from './community';
import type { CommunityModerationBanItemExpiredAt } from './communityModerationBanItemExpiredAt';
import type { CommunityModerationBanItemExpiresAt } from './communityModerationBanItemExpiresAt';

export interface CommunityModerationBanItem {
  banned_by?: Person;
  banned_user?: Person;
  community?: Community;
  expired?: boolean;
  expired_at?: CommunityModerationBanItemExpiredAt;
  expires_at?: CommunityModerationBanItemExpiresAt;
  reason?: string;
}
