/**
 * Generated by orval
 * Do not edit manually.
 */
import type { Community } from './community';
import type { Person } from './person';

export interface CommunityFollowerView {
  community: Community;
  follower: Person;
}
