/**
 * Generated by orval
 * Do not edit manually.
 */

export interface CommunityModerationBanRequest {
  community_id: number;
  reason: string;
  user_id: number;
  expires_at?: string;
  permanent?: boolean;
}
