/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { Community } from './community';
import type { Person } from './person';

export interface CommunityBlockView {
  community?: Community;
  person?: Person;
}
