/**
 * Generated by orval
 * Do not edit manually.
 */

export type CommunityViewSubscribed = typeof CommunityViewSubscribed[keyof typeof CommunityViewSubscribed];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommunityViewSubscribed = {
  Subscribed: 'Subscribed',
  NotSubscribed: 'NotSubscribed',
  Pending: 'Pending',
} as const;
