/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export interface CommunityFlairEditRequest {
  flair_id: number;
  flair_title?: string;
  /** Hex color code for the text of the flair. */
  text_color?: string;
  /** Hex color code for the background of the flair. */
  background_color?: string;
  blur_images?: boolean;
}
