/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export interface CommentReport {
  id: number;
  creator_id: number;
  comment_id: number;
  original_comment_text?: string;
  reason?: string;
  resolved: boolean;
  published: string;
  updated?: string;
}
