/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { CommunityModerationBanItem } from './communityModerationBanItem';
import type { CommunityModerationBansListResponseNextPage } from './communityModerationBansListResponseNextPage';

export interface CommunityModerationBansListResponse {
  items?: CommunityModerationBanItem[];
  next_page?: CommunityModerationBansListResponseNextPage;
}
