/**
 * Generated by orval
 * Do not edit manually.
 */
import type { Comment } from './comment';
import type { Community } from './community';
import type { CommentAggregates } from './commentAggregates';
import type { Person } from './person';
import type { Post } from './post';
import type { CommentReportViewSubscribed } from './commentReportViewSubscribed';
import type { CommentReport } from './commentReport';

export interface CommentReportView {
  activity_alert: boolean;
  banned_from_community: boolean;
  comment: Comment;
  community: Community;
  counts: CommentAggregates;
  creator: Person;
  creator_banned_from_community: boolean;
  creator_blocked: boolean;
  creator_is_admin: boolean;
  creator_is_moderator: boolean;
  post: Post;
  saved: boolean;
  /** Indicates whether auth'ed user is subscribed to the community this comment is in or not. */
  subscribed: CommentReportViewSubscribed;
  my_vote?: number;
  can_auth_user_moderate?: boolean;
  comment_report: CommentReport;
  comment_creator: Person;
}
