/**
 * Generated by orval
 * Do not edit manually.
 */
import type { CommentEmojiReactions } from './commentEmojiReactions';

export interface Comment {
  ap_id: string;
  body: string;
  deleted: boolean;
  id: number;
  language_id: number;
  local: boolean;
  path: string;
  post_id: number;
  published: string;
  removed: boolean;
  user_id: number;
  distinguished?: boolean;
  updated?: string;
  locked?: boolean;
  answer?: boolean;
  emoji_reactions?: CommentEmojiReactions;
  [key: string]: unknown;
 }
