/**
 * Generated by orval
 * Do not edit manually.
 */

/**
 * Indicates whether auth'ed user is subscribed to the community this comment is in or not.
 */
export type CommentViewSubscribed = typeof CommentViewSubscribed[keyof typeof CommentViewSubscribed];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommentViewSubscribed = {
  Subscribed: 'Subscribed',
  NotSubscribed: 'NotSubscribed',
  Pending: 'Pending',
} as const;
