/**
 * Generated by orval
 * Do not edit manually.
 */
import type { Comment } from './comment';
import type { CommentReply } from './commentReply';
import type { Community } from './community';
import type { CommentAggregates } from './commentAggregates';
import type { Person } from './person';
import type { Post } from './post';
import type { CommentReplyViewSubscribed } from './commentReplyViewSubscribed';

export interface CommentReplyView {
  activity_alert: boolean;
  comment: Comment;
  comment_reply: CommentReply;
  community: Community;
  counts: CommentAggregates;
  creator: Person;
  creator_banned_from_community: boolean;
  creator_blocked: boolean;
  creator_is_admin: boolean;
  creator_is_moderator: boolean;
  my_vote: number;
  post: Post;
  recipient: Person;
  saved: boolean;
  subscribed: CommentReplyViewSubscribed;
}
