/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export type CommunityViewSubscribed = typeof CommunityViewSubscribed[keyof typeof CommunityViewSubscribed];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommunityViewSubscribed = {
  Subscribed: 'Subscribed',
  NotSubscribed: 'NotSubscribed',
  Pending: 'Pending',
} as const;
