/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { CommunityView } from './communityView';
import type { CommunityModeratorView } from './communityModeratorView';
import type { Site } from './site';

export interface CommunityFlairDeleteResponse {
  community_view: CommunityView;
  discussion_languages: number[];
  moderators: CommunityModeratorView[];
  site?: Site;
}
