/**
 * Generated by orval
 * Do not edit manually.
 */
import type { CommunityFlairEditResponseApId } from './communityFlairEditResponseApId';

export interface CommunityFlairEditResponse {
  id: number;
  community_id: number;
  flair_title: string;
  /** Hex color code for the text of the flair */
  text_color: string;
  /** Hex color code for the background of the flair */
  background_color: string;
  blur_images: boolean;
  /** Legacy tags that existed prior to 1.2 and some tags for remote communities might not have a defined ap_id */
  ap_id: CommunityFlairEditResponseApId;
}
