/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { CreatePostRequestEvent } from './createPostRequestEvent';
import type { CreatePostRequestPoll } from './createPostRequestPoll';

export interface CreatePostRequest {
  title: string;
  community_id: number;
  /** Will be used for image posts or link posts that point to images */
  alt_text?: string;
  body?: string;
  url?: string;
  nsfw?: boolean;
  ai_generated?: boolean;
  language_id?: number;
  event?: CreatePostRequestEvent;
  poll?: CreatePostRequestPoll;
}
