/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { CreateCommunityRequestBannerUrl } from './createCommunityRequestBannerUrl';
import type { CreateCommunityRequestIconUrl } from './createCommunityRequestIconUrl';

export interface CreateCommunityRequest {
  name: string;
  title: string;
  banner_url?: CreateCommunityRequestBannerUrl;
  description?: string;
  discussion_languages?: number[];
  icon_url?: CreateCommunityRequestIconUrl;
  local_only?: boolean;
  nsfw?: boolean;
  question_answer?: boolean;
  restricted_to_mods?: boolean;
  rules?: string;
}
