/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { EditCommunityRequestBannerUrl } from './editCommunityRequestBannerUrl';
import type { EditCommunityRequestIconUrl } from './editCommunityRequestIconUrl';

export interface EditCommunityRequest {
  community_id: number;
  title?: string;
  banner_url?: EditCommunityRequestBannerUrl;
  description?: string;
  discussion_languages?: number[];
  icon_url?: EditCommunityRequestIconUrl;
  local_only?: boolean;
  nsfw?: boolean;
  restricted_to_mods?: boolean;
  question_answer?: boolean;
  rules?: string;
}
