/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { EditFeedRequestIconUrl } from './editFeedRequestIconUrl';
import type { EditFeedRequestBannerUrl } from './editFeedRequestBannerUrl';
import type { EditFeedRequestParentFeedId } from './editFeedRequestParentFeedId';

export interface EditFeedRequest {
  feed_id: number;
  /** URL-safe name/slug for the feed */
  url?: string;
  title?: string;
  description?: string;
  icon_url?: EditFeedRequestIconUrl;
  banner_url?: EditFeedRequestBannerUrl;
  nsfw?: boolean;
  nsfl?: boolean;
  public?: boolean;
  /** Newline-separated list of community ap_ids; omit to keep existing communities */
  communities?: string;
  is_instance_feed?: boolean;
  show_child_posts?: boolean;
  parent_feed_id?: EditFeedRequestParentFeedId;
}
