/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export interface EditCommentRequest {
  body: string;
  comment_id: number;
  language_id?: number;
  /** Visibly mark reply as from a moderator in the web UI */
  distinguished?: boolean;
}
