/**
 * Generated by orval
 * Do not edit manually.
 */
import type { EditPostRequestAltText } from './editPostRequestAltText';
import type { EditPostRequestUrl } from './editPostRequestUrl';
import type { EditPostRequestEvent } from './editPostRequestEvent';
import type { EditPostRequestPoll } from './editPostRequestPoll';
import type { EditPostRequestTags } from './editPostRequestTags';
import type { EditPostRequestFlair } from './editPostRequestFlair';

export interface EditPostRequest {
  post_id: number;
  /** Pass null to remove the existing alt text */
  alt_text?: EditPostRequestAltText;
  title?: string;
  body?: string;
  /** Pass value of null to remove the post url */
  url?: EditPostRequestUrl;
  nsfw?: boolean;
  language_id?: number;
  event?: EditPostRequestEvent;
  poll?: EditPostRequestPoll;
  /** Hashtags, separated by commas with no hash character */
  tags?: EditPostRequestTags;
  /** Flair, separated by commas with no hash character */
  flair?: EditPostRequestFlair;
}
