/**
 * Generated by orval
 * Do not edit manually.
 */
import type { ErrorErrors } from './errorErrors';

export interface Error {
  /** Error code */
  code?: number;
  /** Error name */
  status?: string;
  /** Error message */
  message?: string;
  /** Errors */
  errors?: ErrorErrors;
}
