/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export type FeaturePostRequestFeatureType = typeof FeaturePostRequestFeatureType[keyof typeof FeaturePostRequestFeatureType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FeaturePostRequestFeatureType = {
  Community: 'Community',
  Local: 'Local',
} as const;
