/**
 * Generated by orval
 * Do not edit manually.
 */
import type { FeaturePostRequestFeatureType } from './featurePostRequestFeatureType';

export interface FeaturePostRequest {
  post_id: number;
  featured: boolean;
  feature_type?: FeaturePostRequestFeatureType;
}
