/**
 * Generated by orval
 * Do not edit manually.
 */
import type { InstanceWithoutFederationState } from './instanceWithoutFederationState';

export interface FederatedInstancesView {
  allowed: InstanceWithoutFederationState[];
  blocked: InstanceWithoutFederationState[];
  linked: InstanceWithoutFederationState[];
}
