/**
 * Generated by orval
 * Do not edit manually.
 */
import type { Community } from './community';
import type { FeedViewBanner } from './feedViewBanner';
import type { FeedViewDescription } from './feedViewDescription';
import type { FeedViewDescriptionHtml } from './feedViewDescriptionHtml';
import type { FeedViewIcon } from './feedViewIcon';
import type { FeedViewParentFeedId } from './feedViewParentFeedId';

export interface FeedView {
  actor_id: string;
  ap_domain: string;
  /** Always empty list for resolve_object endpoint */
  children: FeedView[];
  /** Always empty list for resolve_object endpoint */
  communities: Community[];
  communities_count: number;
  id: number;
  is_instance_feed: boolean;
  local: boolean;
  name: string;
  nsfl: boolean;
  nsfw: boolean;
  /** Is the authorized user the creator of the feed? */
  owner: boolean;
  public: boolean;
  published: string;
  show_posts_from_children: boolean;
  subscribed: boolean;
  subscriptions_count: number;
  title: string;
  updated: string;
  /** user_id of the feed creator/owner */
  user_id: number;
  banner?: FeedViewBanner;
  description?: FeedViewDescription;
  description_html?: FeedViewDescriptionHtml;
  icon?: FeedViewIcon;
  parent_feed_id?: FeedViewParentFeedId;
}
