/**
 * Generated by orval
 * Do not edit manually.
 */

export type GetApiAlphaCommunityListSort = typeof GetApiAlphaCommunityListSort[keyof typeof GetApiAlphaCommunityListSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiAlphaCommunityListSort = {
  Hot: 'Hot',
  Top: 'Top',
  New: 'New',
  Old: 'Old',
  Active: 'Active',
  TopAll: 'TopAll',
  TopPosts: 'TopPosts',
  TopSubscribers: 'TopSubscribers',
  NewFederated: 'NewFederated',
  OldFederated: 'OldFederated',
} as const;
