/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { GetApiAlphaUserMediaSort } from './getApiAlphaUserMediaSort';

export type GetApiAlphaUserMediaParams = {
limit?: number;
page?: number;
sort?: GetApiAlphaUserMediaSort;
unread_only?: boolean;
};
