/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { GetApiAlphaPostRepliesSort } from './getApiAlphaPostRepliesSort';

export type GetApiAlphaPostRepliesParams = {
post_id?: number;
parent_id?: number;
sort?: GetApiAlphaPostRepliesSort;
max_depth?: number;
page?: string;
limit?: number;
};
