/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export type GetApiAlphaAdminRegistrationApplicationListSort = typeof GetApiAlphaAdminRegistrationApplicationListSort[keyof typeof GetApiAlphaAdminRegistrationApplicationListSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiAlphaAdminRegistrationApplicationListSort = {
  Old: 'Old',
  New: 'New',
} as const;
