/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export type GetApiAlphaUserNotificationsStatus = typeof GetApiAlphaUserNotificationsStatus[keyof typeof GetApiAlphaUserNotificationsStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiAlphaUserNotificationsStatus = {
  All: 'All',
  Unread: 'Unread',
  Read: 'Read',
  New: 'New',
} as const;
