/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { GetApiAlphaUserNotificationsStatus } from './getApiAlphaUserNotificationsStatus';

export type GetApiAlphaUserNotificationsParams = {
status: GetApiAlphaUserNotificationsStatus;
limit?: number;
page?: number;
};
