/**
 * Generated by orval
 * Do not edit manually.
 */
import type { GetApiAlphaUserNotificationsStatus } from './getApiAlphaUserNotificationsStatus';

export type GetApiAlphaUserNotificationsParams = {
status: GetApiAlphaUserNotificationsStatus;
limit?: number;
page?: number;
};
