/**
 * Generated by orval
 * Do not edit manually.
 */

export type GetApiAlphaSearchListingType = typeof GetApiAlphaSearchListingType[keyof typeof GetApiAlphaSearchListingType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiAlphaSearchListingType = {
  All: 'All',
  Local: 'Local',
  Subscribed: 'Subscribed',
  Popular: 'Popular',
  Moderating: 'Moderating',
  ModeratorView: 'ModeratorView',
} as const;
