/**
 * Generated by orval
 * Do not edit manually.
 */
import type { GetApiAlphaAdminRegistrationApplicationListSort } from './getApiAlphaAdminRegistrationApplicationListSort';

export type GetApiAlphaAdminRegistrationApplicationListParams = {
limit?: number;
page?: number;
pending_only?: boolean;
sort?: GetApiAlphaAdminRegistrationApplicationListSort;
};
