/**
 * Generated by orval
 * Do not edit manually.
 */
import type { GetApiAlphaPostList2Sort } from './getApiAlphaPostList2Sort';
import type { GetApiAlphaPostList2Type } from './getApiAlphaPostList2Type';

export type GetApiAlphaPostList2Params = {
q?: string;
sort?: GetApiAlphaPostList2Sort;
type_?: GetApiAlphaPostList2Type;
community_name?: string;
community_id?: number;
saved_only?: boolean;
person_id?: number;
limit?: number;
page?: string;
liked_only?: boolean;
feed_id?: number;
topic_id?: number;
/**
 * Ignores a post's sticky state when sorting
 */
ignore_sticky?: boolean;
};
