/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { GetApiAlphaUserRepliesSort } from './getApiAlphaUserRepliesSort';

export type GetApiAlphaUserRepliesParams = {
limit?: number;
page?: number;
sort?: GetApiAlphaUserRepliesSort;
unread_only?: boolean;
};
