/**
 * Generated by orval
 * Do not edit manually.
 */
import type { GetApiAlphaUserMentionsSort } from './getApiAlphaUserMentionsSort';

export type GetApiAlphaUserMentionsParams = {
limit?: number;
page?: number;
sort?: GetApiAlphaUserMentionsSort;
unread_only?: boolean;
};
