/**
 * Generated by orval
 * Do not edit manually.
 */

export type GetApiAlphaSearchType = typeof GetApiAlphaSearchType[keyof typeof GetApiAlphaSearchType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiAlphaSearchType = {
  Communities: 'Communities',
  Posts: 'Posts',
  Users: 'Users',
  Url: 'Url',
  Comments: 'Comments',
} as const;
