/**
 * Generated by orval
 * Do not edit manually.
 */
import type { GetApiAlphaPostListSort } from './getApiAlphaPostListSort';
import type { GetApiAlphaPostListType } from './getApiAlphaPostListType';

export type GetApiAlphaPostListParams = {
q?: string;
sort?: GetApiAlphaPostListSort;
type_?: GetApiAlphaPostListType;
community_name?: string;
community_id?: number;
saved_only?: boolean;
person_id?: number;
limit?: number;
page?: number;
liked_only?: boolean;
feed_id?: number;
topic_id?: number;
/**
 * Ignores a post's sticky state when sorting
 */
ignore_sticky?: boolean;
};
