/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export type GetApiAlphaUserMediaSort = typeof GetApiAlphaUserMediaSort[keyof typeof GetApiAlphaUserMediaSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiAlphaUserMediaSort = {
  Hot: 'Hot',
  Top: 'Top',
  TopAll: 'TopAll',
  New: 'New',
  Old: 'Old',
  Controversial: 'Controversial',
} as const;
