/**
 * Generated by orval
 * Do not edit manually.
 */
import type { GetApiAlphaModlogType } from './getApiAlphaModlogType';

export type GetApiAlphaModlogParams = {
mod_person_id?: number;
community_id?: number;
page?: number;
limit?: number;
type_?: GetApiAlphaModlogType;
other_person_id?: number;
post_id?: number;
comment_id?: number;
};
