/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export type GetApiAlphaPostList2Sort = typeof GetApiAlphaPostList2Sort[keyof typeof GetApiAlphaPostList2Sort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiAlphaPostList2Sort = {
  Hot: 'Hot',
  Top: 'Top',
  TopHour: 'TopHour',
  TopSixHour: 'TopSixHour',
  TopTwelveHour: 'TopTwelveHour',
  TopWeek: 'TopWeek',
  TopDay: 'TopDay',
  TopMonth: 'TopMonth',
  TopThreeMonths: 'TopThreeMonths',
  TopSixMonths: 'TopSixMonths',
  TopNineMonths: 'TopNineMonths',
  TopYear: 'TopYear',
  TopAll: 'TopAll',
  New: 'New',
  Old: 'Old',
  Scaled: 'Scaled',
  Active: 'Active',
} as const;
