/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export type GetApiAlphaFeedListParams = {
/**
 * include list of communities in each feed with result
 */
include_communities?: boolean;
/**
 * only return feeds created by the authorized user
 */
mine_only?: boolean;
};
