/**
 * Generated by orval
 * Do not edit manually.
 */

export type GetApiAlphaUserMediaSort = typeof GetApiAlphaUserMediaSort[keyof typeof GetApiAlphaUserMediaSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiAlphaUserMediaSort = {
  Hot: 'Hot',
  Top: 'Top',
  TopAll: 'TopAll',
  New: 'New',
  Old: 'Old',
  Controversial: 'Controversial',
} as const;
