/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export type GetApiAlphaTopicListParams = {
/**
 * include list of communities in each topic with result
 */
include_communities?: boolean;
};
