/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { GetApiAlphaUserMentionsSort } from './getApiAlphaUserMentionsSort';

export type GetApiAlphaUserMentionsParams = {
limit?: number;
page?: number;
sort?: GetApiAlphaUserMentionsSort;
unread_only?: boolean;
};
