/**
 * Generated by orval
 * Do not edit manually.
 */

export type GetApiAlphaUserRepliesSort = typeof GetApiAlphaUserRepliesSort[keyof typeof GetApiAlphaUserRepliesSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiAlphaUserRepliesSort = {
  Hot: 'Hot',
  Top: 'Top',
  TopAll: 'TopAll',
  New: 'New',
  Old: 'Old',
  Controversial: 'Controversial',
} as const;
