/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export type GetApiAlphaSearchSort = typeof GetApiAlphaSearchSort[keyof typeof GetApiAlphaSearchSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiAlphaSearchSort = {
  Active: 'Active',
  Hot: 'Hot',
  New: 'New',
  Top: 'Top',
  TopHour: 'TopHour',
  TopSixHour: 'TopSixHour',
  TopTwelveHour: 'TopTwelveHour',
  TopDay: 'TopDay',
  TopWeek: 'TopWeek',
  TopMonth: 'TopMonth',
  TopThreeMonths: 'TopThreeMonths',
  TopSixMonths: 'TopSixMonths',
  TopNineMonths: 'TopNineMonths',
  TopYear: 'TopYear',
  TopAll: 'TopAll',
  Scaled: 'Scaled',
  Old: 'Old',
  Relevance: 'Relevance',
  TopPosts: 'TopPosts',
  TopSubscribers: 'TopSubscribers',
  NewFederated: 'NewFederated',
  OldFederated: 'OldFederated',
} as const;
