/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export type GetApiAlphaPostListType = typeof GetApiAlphaPostListType[keyof typeof GetApiAlphaPostListType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiAlphaPostListType = {
  All: 'All',
  Local: 'Local',
  Subscribed: 'Subscribed',
  Popular: 'Popular',
  Moderating: 'Moderating',
  ModeratorView: 'ModeratorView',
} as const;
