/**
 * Generated by orval
 * Do not edit manually.
 */
import type { GetApiAlphaUserRepliesSort } from './getApiAlphaUserRepliesSort';

export type GetApiAlphaUserRepliesParams = {
limit?: number;
page?: number;
sort?: GetApiAlphaUserRepliesSort;
unread_only?: boolean;
};
