/**
 * Generated by orval
 * Do not edit manually.
 */

export type GetApiAlphaPostListSort = typeof GetApiAlphaPostListSort[keyof typeof GetApiAlphaPostListSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiAlphaPostListSort = {
  Hot: 'Hot',
  Top: 'Top',
  TopHour: 'TopHour',
  TopSixHour: 'TopSixHour',
  TopTwelveHour: 'TopTwelveHour',
  TopWeek: 'TopWeek',
  TopDay: 'TopDay',
  TopMonth: 'TopMonth',
  TopThreeMonths: 'TopThreeMonths',
  TopSixMonths: 'TopSixMonths',
  TopNineMonths: 'TopNineMonths',
  TopYear: 'TopYear',
  TopAll: 'TopAll',
  New: 'New',
  Old: 'Old',
  Scaled: 'Scaled',
  Active: 'Active',
} as const;
