/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export type GetApiAlphaUserRepliesSort = typeof GetApiAlphaUserRepliesSort[keyof typeof GetApiAlphaUserRepliesSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiAlphaUserRepliesSort = {
  Hot: 'Hot',
  Top: 'Top',
  TopAll: 'TopAll',
  New: 'New',
  Old: 'Old',
  Controversial: 'Controversial',
} as const;
