/**
 * Generated by orval
 * Do not edit manually.
 */
import type { GetApiAlphaUserSort } from './getApiAlphaUserSort';

export type GetApiAlphaUserParams = {
/**
 * One of either person_id or username must be specified
 */
person_id?: number;
/**
 * One of either person_id or username must be specified
 */
username?: string;
sort?: GetApiAlphaUserSort;
page?: number;
limit?: number;
/**
 * Limit posts/comments to just a single community
 */
community_id?: number;
saved_only?: boolean;
include_content?: boolean;
};
