/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export type GetApiAlphaCommunityListType = typeof GetApiAlphaCommunityListType[keyof typeof GetApiAlphaCommunityListType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiAlphaCommunityListType = {
  All: 'All',
  Local: 'Local',
  Subscribed: 'Subscribed',
  Moderating: 'Moderating',
  ModeratorView: 'ModeratorView',
} as const;
