/**
 * Generated by orval
 * Do not edit manually.
 */

export type GetApiAlphaUserNotificationsStatus = typeof GetApiAlphaUserNotificationsStatus[keyof typeof GetApiAlphaUserNotificationsStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiAlphaUserNotificationsStatus = {
  All: 'All',
  Unread: 'Unread',
  Read: 'Read',
  New: 'New',
} as const;
