/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { CommentView } from './commentView';

export interface GetCommentResponse {
  comment_view: CommentView;
}
