/**
 * Generated by orval
 * Do not edit manually.
 */
import type { CommentReportView } from './commentReportView';

export interface GetCommentReportResponse {
  comment_report_view: CommentReportView;
}
