/**
 * Generated by orval
 * Do not edit manually.
 */
import type { FederatedInstancesView } from './federatedInstancesView';

export interface GetFederatedInstancesResponse {
  federated_instances?: FederatedInstancesView;
}
