/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { ModRemovePostView } from './modRemovePostView';
import type { ModLockPostView } from './modLockPostView';
import type { ModFeaturePostView } from './modFeaturePostView';
import type { ModRemoveCommentView } from './modRemoveCommentView';
import type { ModRemoveCommunityView } from './modRemoveCommunityView';
import type { ModBanFromCommunityView } from './modBanFromCommunityView';
import type { ModBanView } from './modBanView';
import type { ModAddCommunityView } from './modAddCommunityView';
import type { ModTransferCommunityView } from './modTransferCommunityView';
import type { ModAddView } from './modAddView';
import type { AdminPurgePersonView } from './adminPurgePersonView';
import type { AdminPurgeCommunityView } from './adminPurgeCommunityView';
import type { AdminPurgePostView } from './adminPurgePostView';
import type { AdminPurgeCommentView } from './adminPurgeCommentView';
import type { ModHideCommunityView } from './modHideCommunityView';

export interface GetModLogResponse {
  removed_posts: ModRemovePostView[];
  locked_posts: ModLockPostView[];
  featured_posts: ModFeaturePostView[];
  removed_comments: ModRemoveCommentView[];
  removed_communities: ModRemoveCommunityView[];
  banned_from_community: ModBanFromCommunityView[];
  banned: ModBanView[];
  added_to_community: ModAddCommunityView[];
  transferred_to_community: ModTransferCommunityView[];
  added: ModAddView[];
  admin_purged_persons: AdminPurgePersonView[];
  admin_purged_communities: AdminPurgeCommunityView[];
  admin_purged_posts: AdminPurgePostView[];
  admin_purged_comments: AdminPurgeCommentView[];
  hidden_communities: ModHideCommunityView[];
}
