/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { PostView } from './postView';
import type { CommunityView } from './communityView';
import type { CommunityModeratorView } from './communityModeratorView';

export interface GetPostResponse {
  post_view: PostView;
  community_view?: CommunityView;
  moderators?: CommunityModeratorView[];
  cross_posts?: PostView[];
}
