/**
 * Generated by orval
 * Do not edit manually.
 */
import type { PostReplyView } from './postReplyView';
import type { GetPostRepliesResponseNextPage } from './getPostRepliesResponseNextPage';

export interface GetPostRepliesResponse {
  comments?: PostReplyView[];
  next_page?: GetPostRepliesResponseNextPage;
}
