/**
 * Generated by orval
 * Do not edit manually.
 */

export interface GetSiteInstanceChooserSearchResponseItem {
  id: number;
  name: string;
  domain: string;
  elevator_pitch: string;
  description: string;
  about: string;
  sidebar: string;
  logo_url: string;
  maturity: string;
  tos_url: string;
  uptime: string;
  mau: number;
  can_make_communities: boolean;
  newbie_friendly: boolean;
  defederation: string[];
  trusts: string[];
  registration_mode: string;
  language: string;
  monthsmonitored: number;
}
