/**
 * Generated by orval
 * Do not edit manually.
 */
import type { GetSiteInstanceChooserSearchResponseItem } from './getSiteInstanceChooserSearchResponseItem';

export interface GetSiteInstanceChooserSearchResponse {
  result: GetSiteInstanceChooserSearchResponseItem[];
}
