/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { PersonView } from './personView';
import type { Site } from './site';
import type { MyUserInfo } from './myUserInfo';

export interface GetSiteResponse {
  admins: PersonView[];
  site: Site;
  version: string;
  my_user?: MyUserInfo;
}
