/**
 * Generated by orval
 * Do not edit manually.
 */
import type { CommentView } from './commentView';
import type { CommunityModeratorView } from './communityModeratorView';
import type { PersonView } from './personView';
import type { PostView } from './postView';
import type { Site } from './site';

export interface GetUserResponse {
  comments: CommentView[];
  moderates: CommunityModeratorView[];
  person_view: PersonView;
  posts: PostView[];
  site?: Site;
}
