/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export interface ImageUploadResponse {
  url: string;
  liked_only?: boolean;
  saved_only?: boolean;
  q?: string;
}
