/**
 * Generated by orval
 * Do not edit manually.
 */

export interface InstanceWithoutFederationState {
  domain: string;
  id: number;
  published: string;
  software?: string;
  updated?: string;
  version?: string;
}
