/**
 * Generated by orval
 * Do not edit manually.
 */

export interface LikeCommentRequest {
  comment_id: number;
  /** -1 to downvote, 1 to upvote, 0 to revert previous vote */
  score: number;
  /** private votes are not federated to other instances */
  private?: boolean;
  emoji?: string;
}
