/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export interface LikeCommentRequest {
  comment_id: number;
  /** -1 to downvote, 1 to upvote, 0 to revert previous vote */
  score: number;
  /** private votes are not federated to other instances */
  private?: boolean;
  emoji?: string;
}
