/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { CommentLikeView } from './commentLikeView';
import type { ListCommentLikesResponseNextPage } from './listCommentLikesResponseNextPage';

export interface ListCommentLikesResponse {
  comment_likes: CommentLikeView[];
  next_page?: ListCommentLikesResponseNextPage;
}
