/**
 * Generated by orval
 * Do not edit manually.
 */
import type { PostLikeView } from './postLikeView';
import type { ListPostLikesResponseNextPage } from './listPostLikesResponseNextPage';

export interface ListPostLikesResponse {
  post_likes: PostLikeView[];
  next_page?: ListPostLikesResponseNextPage;
}
