/**
 * Generated by orval
 * Do not edit manually.
 */
import type { CommunityView } from './communityView';
import type { ListCommunitiesResponseNextPage } from './listCommunitiesResponseNextPage';

export interface ListCommunitiesResponse {
  communities: CommunityView[];
  next_page?: ListCommunitiesResponseNextPage;
}
