/**
 * Generated by orval
 * Do not edit manually.
 */
import type { PrivateMessageView } from './privateMessageView';

export interface ListPrivateMessagesResponse {
  private_messages: PrivateMessageView[];
}
