/**
 * Generated by orval
 * Do not edit manually.
 */
import type { PostView } from './postView';
import type { ListPostsResponseNextPage } from './listPostsResponseNextPage';

export interface ListPostsResponse {
  posts: PostView[];
  next_page?: ListPostsResponseNextPage;
}
