/**
 * Generated by orval
 * Do not edit manually.
 */

export type LocalUserBotVisibility = typeof LocalUserBotVisibility[keyof typeof LocalUserBotVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LocalUserBotVisibility = {
  Show: 'Show',
  Blur: 'Blur',
  Hide: 'Hide',
  Transparent: 'Transparent',
} as const;
