/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export type LocalUserAiVisibility = typeof LocalUserAiVisibility[keyof typeof LocalUserAiVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LocalUserAiVisibility = {
  Show: 'Show',
  Hide: 'Hide',
  Label: 'Label',
  Transparent: 'Transparent',
} as const;
