/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { PersonAggregates } from './personAggregates';
import type { LocalUser } from './localUser';
import type { Person } from './person';

export interface LocalUserView {
  counts: PersonAggregates;
  local_user: LocalUser;
  person: Person;
}
