/**
 * Generated by orval
 * Do not edit manually.
 */

export type LocalUserNsflVisibility = typeof LocalUserNsflVisibility[keyof typeof LocalUserNsflVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LocalUserNsflVisibility = {
  Show: 'Show',
  Blur: 'Blur',
  Hide: 'Hide',
  Transparent: 'Transparent',
} as const;
