/**
 * Generated by orval
 * Do not edit manually.
 */

export type LocalUserAiVisibility = typeof LocalUserAiVisibility[keyof typeof LocalUserAiVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LocalUserAiVisibility = {
  Show: 'Show',
  Hide: 'Hide',
  Label: 'Label',
  Transparent: 'Transparent',
} as const;
