/**
 * Generated by orval
 * Do not edit manually.
 */

export type LocalUserDefaultCommentSortType = typeof LocalUserDefaultCommentSortType[keyof typeof LocalUserDefaultCommentSortType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LocalUserDefaultCommentSortType = {
  Hot: 'Hot',
  Top: 'Top',
  TopAll: 'TopAll',
  New: 'New',
  Old: 'Old',
  Controversial: 'Controversial',
} as const;
