/**
 * Generated by orval
 * Do not edit manually.
 */

export type LocalUserNsfwVisibility = typeof LocalUserNsfwVisibility[keyof typeof LocalUserNsfwVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LocalUserNsfwVisibility = {
  Show: 'Show',
  Blur: 'Blur',
  Hide: 'Hide',
  Transparent: 'Transparent',
} as const;
