/**
 * Generated by orval
 * Do not edit manually.
 */
import type { ModAddModPersonId } from './modAddModPersonId';
import type { ModAddOtherPersonId } from './modAddOtherPersonId';

export interface ModAdd {
  id: number;
  mod_person_id: ModAddModPersonId;
  other_person_id: ModAddOtherPersonId;
  removed: boolean;
  when_: string;
}
