/**
 * Generated by orval
 * Do not edit manually.
 */
import type { ModAddCommunityModPersonId } from './modAddCommunityModPersonId';
import type { ModAddCommunityOtherPersonId } from './modAddCommunityOtherPersonId';
import type { ModAddCommunityCommunityId } from './modAddCommunityCommunityId';

export interface ModAddCommunity {
  id: number;
  mod_person_id: ModAddCommunityModPersonId;
  other_person_id: ModAddCommunityOtherPersonId;
  community_id: ModAddCommunityCommunityId;
  removed: boolean;
  when_: string;
}
