/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { ModBanFromCommunity } from './modBanFromCommunity';
import type { ModBanFromCommunityViewModerator } from './modBanFromCommunityViewModerator';
import type { ModBanFromCommunityViewCommunity } from './modBanFromCommunityViewCommunity';
import type { ModBanFromCommunityViewBannedPerson } from './modBanFromCommunityViewBannedPerson';

export interface ModBanFromCommunityView {
  mod_ban_from_community: ModBanFromCommunity;
  moderator?: ModBanFromCommunityViewModerator;
  community?: ModBanFromCommunityViewCommunity;
  banned_person?: ModBanFromCommunityViewBannedPerson;
}
