/**
 * Generated by orval
 * Do not edit manually.
 */
import type { ModBan } from './modBan';
import type { ModBanViewModerator } from './modBanViewModerator';
import type { ModBanViewBannedPerson } from './modBanViewBannedPerson';

export interface ModBanView {
  mod_ban: ModBan;
  moderator?: ModBanViewModerator;
  banned_person?: ModBanViewBannedPerson;
}
