/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { ModBan } from './modBan';
import type { ModBanViewModerator } from './modBanViewModerator';
import type { ModBanViewBannedPerson } from './modBanViewBannedPerson';

export interface ModBanView {
  mod_ban: ModBan;
  moderator?: ModBanViewModerator;
  banned_person?: ModBanViewBannedPerson;
}
