/**
 * Generated by orval
 * Do not edit manually.
 */
import type { ModBanModPersonId } from './modBanModPersonId';
import type { ModBanOtherPersonId } from './modBanOtherPersonId';
import type { ModBanReason } from './modBanReason';
import type { ModBanExpires } from './modBanExpires';

export interface ModBan {
  id: number;
  mod_person_id: ModBanModPersonId;
  other_person_id: ModBanOtherPersonId;
  reason?: ModBanReason;
  banned: boolean;
  expires?: ModBanExpires;
  when_: string;
}
