/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { ModFeaturePostModPersonId } from './modFeaturePostModPersonId';
import type { ModFeaturePostPostId } from './modFeaturePostPostId';

export interface ModFeaturePost {
  id: number;
  mod_person_id: ModFeaturePostModPersonId;
  post_id: ModFeaturePostPostId;
  featured: boolean;
  is_featured_community: boolean;
  when_: string;
}
