/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { ModFeaturePost } from './modFeaturePost';
import type { ModFeaturePostViewModerator } from './modFeaturePostViewModerator';
import type { ModFeaturePostViewPost } from './modFeaturePostViewPost';
import type { ModFeaturePostViewCommunity } from './modFeaturePostViewCommunity';

export interface ModFeaturePostView {
  mod_feature_post: ModFeaturePost;
  moderator?: ModFeaturePostViewModerator;
  post?: ModFeaturePostViewPost;
  community?: ModFeaturePostViewCommunity;
}
