/**
 * Generated by orval
 * Do not edit manually.
 */
import type { ModFeaturePostModPersonId } from './modFeaturePostModPersonId';
import type { ModFeaturePostPostId } from './modFeaturePostPostId';

export interface ModFeaturePost {
  id: number;
  mod_person_id: ModFeaturePostModPersonId;
  post_id: ModFeaturePostPostId;
  featured: boolean;
  is_featured_community: boolean;
  when_: string;
}
