/**
 * Generated by orval
 * Do not edit manually.
 */
import type { ModHideCommunity } from './modHideCommunity';
import type { Person } from './person';
import type { Community } from './community';

export interface ModHideCommunityView {
  mod_hide_community: ModHideCommunity;
  admin?: Person;
  community: Community;
}
