/**
 * Generated by orval
 * Do not edit manually.
 */
import type { ModLockPostModPersonId } from './modLockPostModPersonId';
import type { ModLockPostPostId } from './modLockPostPostId';

export interface ModLockPost {
  id: number;
  mod_person_id: ModLockPostModPersonId;
  post_id: ModLockPostPostId;
  locked: boolean;
  when_: string;
}
