/**
 * Generated by orval
 * Do not edit manually.
 */
import type { ModRemovePostModPersonId } from './modRemovePostModPersonId';
import type { ModRemovePostPostId } from './modRemovePostPostId';
import type { ModRemovePostReason } from './modRemovePostReason';

export interface ModRemovePost {
  id: number;
  mod_person_id: ModRemovePostModPersonId;
  post_id: ModRemovePostPostId;
  reason?: ModRemovePostReason;
  removed: boolean;
  when_: string;
}
