/**
 * Generated by orval
 * Do not edit manually.
 */
import type { ModRemovePost } from './modRemovePost';
import type { ModRemovePostViewModerator } from './modRemovePostViewModerator';
import type { ModRemovePostViewPost } from './modRemovePostViewPost';
import type { ModRemovePostViewCommunity } from './modRemovePostViewCommunity';

export interface ModRemovePostView {
  mod_remove_post: ModRemovePost;
  moderator?: ModRemovePostViewModerator;
  post?: ModRemovePostViewPost;
  community?: ModRemovePostViewCommunity;
}
