/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { ModRemoveCommunity } from './modRemoveCommunity';
import type { ModRemoveCommunityViewModerator } from './modRemoveCommunityViewModerator';
import type { ModRemoveCommunityViewCommunity } from './modRemoveCommunityViewCommunity';

export interface ModRemoveCommunityView {
  mod_remove_community: ModRemoveCommunity;
  moderator?: ModRemoveCommunityViewModerator;
  community?: ModRemoveCommunityViewCommunity;
}
