/**
 * Generated by orval
 * Do not edit manually.
 */
import type { ModRemoveCommunityModPersonId } from './modRemoveCommunityModPersonId';
import type { ModRemoveCommunityCommunityId } from './modRemoveCommunityCommunityId';
import type { ModRemoveCommunityReason } from './modRemoveCommunityReason';

export interface ModRemoveCommunity {
  id: number;
  mod_person_id: ModRemoveCommunityModPersonId;
  community_id: ModRemoveCommunityCommunityId;
  reason?: ModRemoveCommunityReason;
  removed: boolean;
  when_: string;
}
