/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { ModRemoveComment } from './modRemoveComment';
import type { ModRemoveCommentViewModerator } from './modRemoveCommentViewModerator';
import type { ModRemoveCommentViewComment } from './modRemoveCommentViewComment';
import type { ModRemoveCommentViewCommenter } from './modRemoveCommentViewCommenter';
import type { ModRemoveCommentViewPost } from './modRemoveCommentViewPost';
import type { ModRemoveCommentViewCommunity } from './modRemoveCommentViewCommunity';

export interface ModRemoveCommentView {
  mod_remove_comment: ModRemoveComment;
  moderator?: ModRemoveCommentViewModerator;
  comment?: ModRemoveCommentViewComment;
  commenter?: ModRemoveCommentViewCommenter;
  post?: ModRemoveCommentViewPost;
  community?: ModRemoveCommentViewCommunity;
}
