/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { ModTransferCommunity } from './modTransferCommunity';
import type { ModTransferCommunityViewModerator } from './modTransferCommunityViewModerator';
import type { Community } from './community';
import type { ModTransferCommunityViewModdedPerson } from './modTransferCommunityViewModdedPerson';

export interface ModTransferCommunityView {
  mod_transfer_community: ModTransferCommunity;
  moderator?: ModTransferCommunityViewModerator;
  community: Community;
  modded_person?: ModTransferCommunityViewModdedPerson;
}
