/**
 * Generated by orval
 * Do not edit manually.
 */
import type { CommunityBlockView } from './communityBlockView';
import type { LanguageView } from './languageView';
import type { CommunityFollowerView } from './communityFollowerView';
import type { InstanceBlockView } from './instanceBlockView';
import type { LocalUserView } from './localUserView';
import type { CommunityModeratorView } from './communityModeratorView';
import type { PersonBlockView } from './personBlockView';

export interface MyUserInfo {
  community_blocks: CommunityBlockView[];
  discussion_languages: LanguageView[];
  follows: CommunityFollowerView[];
  instance_blocks: InstanceBlockView[];
  local_user_view: LocalUserView;
  moderates: CommunityModeratorView[];
  person_blocks: PersonBlockView[];
}
