/**
 * Generated by orval
 * Do not edit manually.
 */

/**
 * Pass an id of an existing extra field with null/missing/empty label or text to remove a field. Pass an id of an existing extra field with both label and text to edit an existing extra field.
 */
export type NewUserExtraFieldId = number | null;
