/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

/**
 * Pass a label and text without an id to create a new extra field.
 */
export type NewUserExtraFieldText = string | null;
