/**
 * Generated by orval
 * Do not edit manually.
 */
import type { PersonAvatar } from './personAvatar';
import type { PersonBanner } from './personBanner';
import type { UserExtraField } from './userExtraField';
import type { PersonTitle } from './personTitle';

export interface Person {
  actor_id: string;
  banned: boolean;
  bot: boolean;
  deleted: boolean;
  id: number;
  instance_id: number;
  local: boolean;
  user_name: string;
  about?: string;
  about_html?: string;
  avatar?: PersonAvatar;
  banner?: PersonBanner;
  /** @maxItems 4 */
  extra_fields?: UserExtraField[];
  /** @maxLength 50 */
  note?: string;
  flair?: string;
  published?: string;
  title?: PersonTitle;
}
