/**
 * Generated by orval
 * Do not edit manually.
 */

export interface PollVoteRequest {
  post_id: number;
  /** Must have a length of 1 for a poll in single vote mode. */
  choice_id: number[];
}
