/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export interface PollChoice {
  id: number;
  choice_text: string;
  sort_order: number;
  /** Value is ignored when creating/editing a poll */
  num_votes?: number;
}
