/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { PostSetFlairRequestFlairIdList } from './postSetFlairRequestFlairIdList';

export interface PostSetFlairRequest {
  post_id: number;
  /** A list of all the flair id to assign to the post. Either pass an empty list or null to remove flair */
  flair_id_list?: PostSetFlairRequestFlairIdList;
}
