/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { Person } from './person';

export interface PostLikeView {
  score: number;
  creator_banned_from_community: boolean;
  creator_banned: boolean;
  creator: Person;
}
