/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export type PostViewSubscribed = typeof PostViewSubscribed[keyof typeof PostViewSubscribed];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostViewSubscribed = {
  Subscribed: 'Subscribed',
  NotSubscribed: 'NotSubscribed',
  Pending: 'Pending',
} as const;
