/**
 * Generated by orval
 * Do not edit manually.
 */
import type { PostPollMode } from './postPollMode';
import type { PollChoice } from './pollChoice';

export interface PostPoll {
  end_poll?: string;
  /** single or multiple - determines whether people can vote for one or multiple options */
  mode: PostPollMode;
  local_only?: boolean;
  latest_vote?: string;
  /** @maxItems 10 */
  choices: PollChoice[];
  my_votes?: number[];
}
