/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export interface PostAggregates {
  comments: number;
  downvotes: number;
  newest_comment_time: string;
  post_id: number;
  published: string;
  score: number;
  upvotes: number;
  cross_posts: number;
}
