/**
 * Generated by orval
 * Do not edit manually.
 */
import type { PostSetFlairRequestFlairIdList } from './postSetFlairRequestFlairIdList';

export interface PostSetFlairRequest {
  post_id: number;
  /** A list of all the flair id to assign to the post. Either pass an empty list or null to remove flair */
  flair_id_list?: PostSetFlairRequestFlairIdList;
}
