/**
 * Generated by orval
 * Do not edit manually.
 */
import type { Person } from './person';

export interface PostLikeView {
  score: number;
  creator_banned_from_community: boolean;
  creator_banned: boolean;
  creator: Person;
}
