/**
 * Generated by orval
 * Do not edit manually.
 */

export type PostPostType = typeof PostPostType[keyof typeof PostPostType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostPostType = {
  Link: 'Link',
  Discussion: 'Discussion',
  Image: 'Image',
  Video: 'Video',
  Poll: 'Poll',
  Event: 'Event',
} as const;
