/**
 * Generated by orval
 * Do not edit manually.
 */

export type PostViewSubscribed = typeof PostViewSubscribed[keyof typeof PostViewSubscribed];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostViewSubscribed = {
  Subscribed: 'Subscribed',
  NotSubscribed: 'NotSubscribed',
  Pending: 'Pending',
} as const;
