/**
 * Generated by orval
 * Do not edit manually.
 */
import type { Comment } from './comment';
import type { Community } from './community';
import type { CommentAggregates } from './commentAggregates';
import type { Person } from './person';
import type { Post } from './post';
import type { PostReplyViewSubscribed } from './postReplyViewSubscribed';

export interface PostReplyView {
  activity_alert: boolean;
  banned_from_community: boolean;
  comment: Comment;
  community?: Community;
  counts: CommentAggregates;
  creator: Person;
  creator_banned_from_community: boolean;
  creator_blocked: boolean;
  creator_is_admin: boolean;
  creator_is_moderator: boolean;
  post?: Post;
  saved: boolean;
  /** Indicates whether auth'ed user is subscribed to the community this comment is in or not. */
  subscribed: PostReplyViewSubscribed;
  my_vote?: number;
  can_auth_user_moderate?: boolean;
  replies?: PostReplyView[];
}
