/**
 * Generated by orval
 * Do not edit manually.
 */
import type { Community } from './community';
import type { PostAggregates } from './postAggregates';
import type { Person } from './person';
import type { Post } from './post';
import type { PostViewSubscribed } from './postViewSubscribed';
import type { CommunityFlair } from './communityFlair';

export interface PostView {
  banned_from_community: boolean;
  community: Community;
  counts: PostAggregates;
  creator: Person;
  creator_banned_from_community: boolean;
  creator_is_admin: boolean;
  creator_is_moderator: boolean;
  hidden: boolean;
  post: Post;
  read: boolean;
  saved: boolean;
  subscribed: PostViewSubscribed;
  unread_comments: number;
  activity_alert?: boolean;
  alt_text?: string;
  my_vote?: number;
  /** See also the simpler 'flair' on post which can be used when editing */
  flair_list?: CommunityFlair[];
  can_auth_user_moderate?: boolean;
}
