/**
 * Generated by orval
 * Do not edit manually.
 */

export type PostReportViewSubscribed = typeof PostReportViewSubscribed[keyof typeof PostReportViewSubscribed];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostReportViewSubscribed = {
  Subscribed: 'Subscribed',
  NotSubscribed: 'NotSubscribed',
  Pending: 'Pending',
} as const;
