/**
 * Generated by orval
 * Do not edit manually.
 */
import type { PostEventOnlineLink } from './postEventOnlineLink';
import type { PostEventExternalParticipationUrl } from './postEventExternalParticipationUrl';
import type { PostEventBuyTicketsLink } from './postEventBuyTicketsLink';
import type { PostEventLocation } from './postEventLocation';

export interface PostEvent {
  start: string;
  end?: string;
  timezone?: string;
  max_attendees?: number;
  participant_count?: number;
  full?: boolean;
  online_link?: PostEventOnlineLink;
  /** free, restricted, external, invite */
  join_mode?: string;
  external_participation_url?: PostEventExternalParticipationUrl;
  anonymous_participation?: boolean;
  online?: boolean;
  buy_tickets_link?: PostEventBuyTicketsLink;
  event_fee_currency?: string;
  event_fee_amount?: number;
  /** JSON object containing location details */
  location?: PostEventLocation;
}
