/**
 * Generated by orval
 * Do not edit manually.
 */

/**
 * single or multiple - determines whether people can vote for one or multiple options
 */
export type PostPollMode = typeof PostPollMode[keyof typeof PostPollMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostPollMode = {
  single: 'single',
  multiple: 'multiple',
} as const;
