/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { WidthHeight } from './widthHeight';
import type { MiniCrossPosts } from './miniCrossPosts';
import type { PostPostType } from './postPostType';
import type { PostTags } from './postTags';
import type { PostFlair } from './postFlair';
import type { PostEmojiReactions } from './postEmojiReactions';
import type { PostEvent } from './postEvent';
import type { PostPoll } from './postPoll';

export interface Post {
  ap_id: string;
  community_id: number;
  deleted: boolean;
  id: number;
  language_id: number;
  local: boolean;
  locked: boolean;
  nsfw: boolean;
  ai_generated: boolean;
  published: string;
  removed: boolean;
  sticky: boolean;
  instance_sticky: boolean;
  title: string;
  user_id: number;
  alt_text?: string;
  body?: string;
  small_thumbnail_url?: string;
  thumbnail_url?: string;
  updated?: string;
  url?: string;
  image_details?: WidthHeight;
  cross_posts?: MiniCrossPosts[];
  post_type: PostPostType;
  tags?: PostTags;
  flair?: PostFlair;
  emoji_reactions?: PostEmojiReactions;
  event?: PostEvent;
  poll?: PostPoll;
}
