/**
 * Generated by orval
 * Do not edit manually.
 */

export interface PostReport {
  id: number;
  creator_id: number;
  post_id: number;
  original_post_name: string;
  original_post_body: string;
  reason: string;
  resolved: boolean;
  published?: string;
}
