/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { PostReport } from './postReport';
import type { Post } from './post';
import type { Community } from './community';
import type { Person } from './person';
import type { PostAggregates } from './postAggregates';
import type { PostReportViewSubscribed } from './postReportViewSubscribed';

export interface PostReportView {
  post_report: PostReport;
  post: Post;
  community: Community;
  creator: Person;
  post_creator: Person;
  counts: PostAggregates;
  creator_banned_from_community: boolean;
  creator_is_moderator: boolean;
  creator_is_admin: boolean;
  creator_blocked: boolean;
  subscribed: PostReportViewSubscribed;
  saved: boolean;
}
