/**
 * Generated by orval
 * Do not edit manually.
 */
import type { PrivateMessage } from './privateMessage';
import type { Person } from './person';

export interface PrivateMessageView {
  private_message: PrivateMessage;
  creator: Person;
  recipient: Person;
  conversation_id?: number;
}
