/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { PrivateMessage } from './privateMessage';
import type { Person } from './person';

export interface PrivateMessageView {
  private_message: PrivateMessage;
  creator: Person;
  recipient: Person;
  conversation_id?: number;
}
