/**
 * Generated by orval
 * Do not edit manually.
 */
import type { ReactionsUrl } from './reactionsUrl';

export interface Reactions {
  url?: ReactionsUrl;
  token?: string;
  authors?: string[];
  count?: number;
}
