/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { ReactionsUrl } from './reactionsUrl';

export interface Reactions {
  url?: ReactionsUrl;
  token?: string;
  authors?: string[];
  count?: number;
}
