/**
 * Generated by orval
 * Do not edit manually.
 */

export interface ReportPostRequest {
  post_id: number;
  reason: string;
  description?: string;
  /** Also send report to originating instance */
  report_remote?: boolean;
}
