/**
 * Generated by orval
 * Do not edit manually.
 */
import type { CommentView } from './commentView';
import type { PostView } from './postView';
import type { CommunityView } from './communityView';
import type { PersonView } from './personView';
import type { FeedView } from './feedView';

export interface ResolveObjectResponse {
  comment?: CommentView;
  post?: PostView;
  community?: CommunityView;
  person?: PersonView;
  feed?: FeedView;
}
