/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { CommentView } from './commentView';
import type { PostView } from './postView';
import type { CommunityView } from './communityView';
import type { PersonView } from './personView';
import type { FeedView } from './feedView';

export interface ResolveObjectResponse {
  comment?: CommentView;
  post?: PostView;
  community?: CommunityView;
  person?: PersonView;
  feed?: FeedView;
}
