/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { SearchResponseType } from './searchResponseType';
import type { CommunityView } from './communityView';
import type { PostView } from './postView';
import type { PersonView } from './personView';
import type { CommentView } from './commentView';

export interface SearchResponse {
  type_: SearchResponseType;
  communities: CommunityView[];
  posts: PostView[];
  users: PersonView[];
  comments: CommentView[];
}
