/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export interface SiteMetadataView {
  title?: string;
  description?: string;
  image?: string;
  embed_video_url?: string;
}
