/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export type SiteRegistrationMode = typeof SiteRegistrationMode[keyof typeof SiteRegistrationMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SiteRegistrationMode = {
  Closed: 'Closed',
  RequireApplication: 'RequireApplication',
  Open: 'Open',
} as const;
