/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { LanguageView } from './languageView';
import type { SiteIcon } from './siteIcon';
import type { SiteRegistrationMode } from './siteRegistrationMode';

export interface Site {
  actor_id: string;
  /** The banner at the top of the home page */
  announcement_md?: string;
  /** The banner at the top of the home page */
  announcement?: string;
  name: string;
  all_languages?: LanguageView[];
  description?: string;
  enable_downvotes?: boolean;
  icon?: SiteIcon;
  registration_mode?: SiteRegistrationMode;
  sidebar?: string;
  sidebar_md?: string;
  user_count?: number;
}
