/**
 * Generated by orval
 * Do not edit manually.
 */

export type SiteRegistrationMode = typeof SiteRegistrationMode[keyof typeof SiteRegistrationMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SiteRegistrationMode = {
  Closed: 'Closed',
  RequireApplication: 'RequireApplication',
  Open: 'Open',
} as const;
