/**
 * Generated by orval
 * Do not edit manually.
 */
import type { UserSetNoteRequestNote } from './userSetNoteRequestNote';

export interface UserSetNoteRequest {
  person_id: number;
  /**
   * Pass a value of null to remove existing note
   * @maxLength 50
   */
  note: UserSetNoteRequestNote;
}
