/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { UserMentionsResponseNextPage } from './userMentionsResponseNextPage';
import type { CommentReplyView } from './commentReplyView';

export interface UserMentionsResponse {
  next_page?: UserMentionsResponseNextPage;
  replies: CommentReplyView[];
}
