/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export type UserSaveSettingsRequestBotVisibility = typeof UserSaveSettingsRequestBotVisibility[keyof typeof UserSaveSettingsRequestBotVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserSaveSettingsRequestBotVisibility = {
  Show: 'Show',
  Blur: 'Blur',
  Hide: 'Hide',
  Transparent: 'Transparent',
} as const;
