/**
 * Generated by orval
 * Do not edit manually.
 */

export type UserNotificationsResponseStatus = typeof UserNotificationsResponseStatus[keyof typeof UserNotificationsResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserNotificationsResponseStatus = {
  All: 'All',
  Unread: 'Unread',
  Read: 'Read',
  New: 'New',
} as const;
