/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { UserSaveSettingsRequestAcceptPrivateMessages } from './userSaveSettingsRequestAcceptPrivateMessages';
import type { UserSaveSettingsRequestAvatar } from './userSaveSettingsRequestAvatar';
import type { UserSaveSettingsRequestBotVisibility } from './userSaveSettingsRequestBotVisibility';
import type { UserSaveSettingsRequestCommunityKeywordFilter } from './userSaveSettingsRequestCommunityKeywordFilter';
import type { UserSaveSettingsRequestCover } from './userSaveSettingsRequestCover';
import type { UserSaveSettingsRequestDefaultCommentSortType } from './userSaveSettingsRequestDefaultCommentSortType';
import type { UserSaveSettingsRequestDefaultSortType } from './userSaveSettingsRequestDefaultSortType';
import type { NewUserExtraField } from './newUserExtraField';
import type { UserSaveSettingsRequestNsflVisibility } from './userSaveSettingsRequestNsflVisibility';
import type { UserSaveSettingsRequestNsfwVisibility } from './userSaveSettingsRequestNsfwVisibility';
import type { UserSaveSettingsRequestGenaiVisibility } from './userSaveSettingsRequestGenaiVisibility';

export interface UserSaveSettingsRequest {
  /** Accept private messages from nobody, local users only, "trusted" instances, or any instance */
  accept_private_messages?: UserSaveSettingsRequestAcceptPrivateMessages;
  /** Pass a null value to remove the image */
  avatar?: UserSaveSettingsRequestAvatar;
  bio?: string;
  /** This user is a bot */
  bot?: boolean;
  bot_visibility?: UserSaveSettingsRequestBotVisibility;
  /** Filter out communities with these words in their name. Pass null to remove any filters. */
  community_keyword_filter?: UserSaveSettingsRequestCommunityKeywordFilter;
  /** Pass a null value to remove the image */
  cover?: UserSaveSettingsRequestCover;
  default_comment_sort_type?: UserSaveSettingsRequestDefaultCommentSortType;
  default_sort_type?: UserSaveSettingsRequestDefaultSortType;
  /** Receive email about missed notifications (if set up by local admin) */
  email_unread?: boolean;
  /** A user can't have more than four total extra fields. */
  extra_fields?: NewUserExtraField[];
  /** If false, votes are only counted on local instance instead of federated remotely */
  federate_votes?: boolean;
  /** Automatically follow communities in a subscribed feed */
  feed_auto_follow?: boolean;
  /** Automatically leave communities when unsubscribing from a feed. Does not impact communities joined outside of a feed auto-follow. */
  feed_auto_leave?: boolean;
  /** Hide posts from communities marked as low-quality by the local instance admin */
  hide_low_quality?: boolean;
  /** If posts can show up in search results */
  indexable?: boolean;
  /** Subscribe to the email newsletter that the local instance admin can send */
  newsletter?: boolean;
  /** Overrides the show_nsfl field if provided */
  nsfl_visibility?: UserSaveSettingsRequestNsflVisibility;
  /** Overrides the show_nsfw field if provided */
  nsfw_visibility?: UserSaveSettingsRequestNsfwVisibility;
  /** Overrides the show_genai field if provided */
  genai_visibility?: UserSaveSettingsRequestGenaiVisibility;
  /** Collapse replies with a score at or below this level */
  reply_collapse_threshold?: number;
  /** Hide replies with a score at or below this level */
  reply_hide_threshold?: number;
  show_nsfw?: boolean;
  show_nsfl?: boolean;
  show_read_posts?: boolean;
  /** If profile shows up in the user list on the instance */
  searchable?: boolean;
}
