/**
 * Generated by orval
 * Do not edit manually.
 */

export type UserSaveSettingsRequestDefaultCommentSortType = typeof UserSaveSettingsRequestDefaultCommentSortType[keyof typeof UserSaveSettingsRequestDefaultCommentSortType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserSaveSettingsRequestDefaultCommentSortType = {
  Hot: 'Hot',
  Top: 'Top',
  New: 'New',
  Old: 'Old',
} as const;
