/**
 * Generated by orval
 * Do not edit manually.
 */

/**
 * Overrides the show_genai field if provided
 */
export type UserSaveSettingsRequestGenaiVisibility = typeof UserSaveSettingsRequestGenaiVisibility[keyof typeof UserSaveSettingsRequestGenaiVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserSaveSettingsRequestGenaiVisibility = {
  Show: 'Show',
  Hide: 'Hide',
  Label: 'Label',
  Transparent: 'Transparent',
} as const;
