/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

/**
 * Pass a value of null to remove existing note
 * @maxLength 50
 */
export type UserSetNoteRequestNote = string | null;
