/**
 * Generated by orval
 * Do not edit manually.
 */
import type { UserRepliesResponseNextPage } from './userRepliesResponseNextPage';
import type { CommentReplyView } from './commentReplyView';

export interface UserRepliesResponse {
  next_page?: UserRepliesResponseNextPage;
  replies: CommentReplyView[];
}
