/**
 * Generated by orval
 * Do not edit manually.
 */
import type { UserNotificationsCounts } from './userNotificationsCounts';
import type { UserNotificationItemView } from './userNotificationItemView';
import type { UserNotificationsResponseStatus } from './userNotificationsResponseStatus';
import type { UserNotificationsResponseNextPage } from './userNotificationsResponseNextPage';

export interface UserNotificationsResponse {
  counts: UserNotificationsCounts;
  items: UserNotificationItemView[];
  status: UserNotificationsResponseStatus;
  username: string;
  next_page?: UserNotificationsResponseNextPage;
}
