/**
 * Generated by orval
 * Do not edit manually.
 */
import type { CommentReplyView } from './commentReplyView';

export interface UserMarkAllReadResponse {
  /** Should be empty list */
  replies: CommentReplyView[];
}
