/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

/**
 * Overrides the show_genai field if provided
 */
export type UserSaveSettingsRequestGenaiVisibility = typeof UserSaveSettingsRequestGenaiVisibility[keyof typeof UserSaveSettingsRequestGenaiVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserSaveSettingsRequestGenaiVisibility = {
  Show: 'Show',
  Hide: 'Hide',
  Label: 'Label',
  Transparent: 'Transparent',
} as const;
