/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { PersonView } from './personView';

export interface UserBlockResponse {
  blocked: boolean;
  person_view: PersonView;
}
