/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type { UserBanRequestBanIpAddress } from './userBanRequestBanIpAddress';
import type { UserBanRequestPurgeContent } from './userBanRequestPurgeContent';
import type { UserBanRequestReason } from './userBanRequestReason';

export interface UserBanRequest {
  person_id: number;
  ban_ip_address: UserBanRequestBanIpAddress;
  purge_content: UserBanRequestPurgeContent;
  /**
   * Note to add to modlog
   * @maxLength 50
   */
  reason: UserBanRequestReason;
}
