/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export type UserSaveSettingsRequestDefaultSortType = typeof UserSaveSettingsRequestDefaultSortType[keyof typeof UserSaveSettingsRequestDefaultSortType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserSaveSettingsRequestDefaultSortType = {
  Hot: 'Hot',
  Top: 'Top',
  New: 'New',
  Active: 'Active',
  Old: 'Old',
  Scaled: 'Scaled',
} as const;
