/**
 * Generated by orval
 * Do not edit manually.
 */

/**
 * Overrides the show_nsfl field if provided
 */
export type UserSaveSettingsRequestNsflVisibility = typeof UserSaveSettingsRequestNsflVisibility[keyof typeof UserSaveSettingsRequestNsflVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserSaveSettingsRequestNsflVisibility = {
  Show: 'Show',
  Blur: 'Blur',
  Hide: 'Hide',
  Transparent: 'Transparent',
} as const;
