/**
 * Generated by orval
 * Do not edit manually.
 */

export type UserSaveSettingsRequestBotVisibility = typeof UserSaveSettingsRequestBotVisibility[keyof typeof UserSaveSettingsRequestBotVisibility];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserSaveSettingsRequestBotVisibility = {
  Show: 'Show',
  Blur: 'Blur',
  Hide: 'Hide',
  Transparent: 'Transparent',
} as const;
