/**
 * Generated by orval
 * Do not edit manually.
 */
import type { Person } from './person';
import type { UserNotificationItemViewStatus } from './userNotificationItemViewStatus';
import type { Comment } from './comment';
import type { CommentView } from './commentView';
import type { Community } from './community';
import type { PostView } from './postView';

export interface UserNotificationItemView {
  /** returned for all notif types */
  author: Person;
  /** returned for all notif types */
  notif_body: string;
  /** returned for all notif types */
  notif_id: number;
  /** returned for all notif types */
  notif_subtype: string;
  /** returned for all notif types */
  notif_type: number;
  /** returned for all notif types */
  status: UserNotificationItemViewStatus;
  /** returned for notif_types: 3, 4, 6 (comment_mention subtype) */
  comment?: Comment;
  /** returned for notif_types: 3, 4, 6 (comment_mention subtype) */
  comment_view?: CommentView;
  /** returned for notif_types: 3, 4, 6 (comment_mention subtype) */
  comment_id?: number;
  /** returned for notif_type 1 */
  community?: Community;
  /** returned for notif_types: 0, 1, 2, 3, 4, 5, 6 (post_mention subtype) */
  post?: PostView;
  /** returned for notif_types: 0, 1, 2, 3, 4, 5, 6 (post_mention subtype) */
  post_id?: number;
}
