/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export type UserRegistrationStatus = typeof UserRegistrationStatus[keyof typeof UserRegistrationStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRegistrationStatus = {
  approved: 'approved',
  awaiting_review: 'awaiting review',
} as const;
