/**
 * Generated by orval
 * Do not edit manually.
 */

export interface UserNotificationStateRequest {
  notif_id: number;
  /** true sets notification as read, false marks it unread */
  read_state: boolean;
}
