/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */

export type UserSaveSettingsRequestDefaultCommentSortType = typeof UserSaveSettingsRequestDefaultCommentSortType[keyof typeof UserSaveSettingsRequestDefaultCommentSortType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserSaveSettingsRequestDefaultCommentSortType = {
  Hot: 'Hot',
  Top: 'Top',
  New: 'New',
  Old: 'Old',
} as const;
