/**
 * Generated by orval
 * Do not edit manually.
 */
import type {
  GetApiAlphaModlogParams,
  GetApiAlphaResolveObjectParams,
  GetApiAlphaSearchParams,
  GetApiAlphaSuggestCompletionParams,
  GetFederatedInstancesResponse,
  GetModLogResponse,
  GetSuggestCompletionResponse,
  ResolveObjectResponse,
  SearchResponse
} from '../../schemas';

import { customFetch } from '../../mutator/custom-fetch';

/**
 * @summary Search PieFed.
 */
export const getGetApiAlphaSearchUrl = (params: GetApiAlphaSearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/search?${stringifiedParams}` : `/api/alpha/search`
}

export const getApiAlphaSearch = async (params: GetApiAlphaSearchParams, options?: RequestInit): Promise<SearchResponse> => {
  
  return customFetch<SearchResponse>(getGetApiAlphaSearchUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Fetch a non-local / federated object.
 */
export const getGetApiAlphaResolveObjectUrl = (params: GetApiAlphaResolveObjectParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/resolve_object?${stringifiedParams}` : `/api/alpha/resolve_object`
}

export const getApiAlphaResolveObject = async (params: GetApiAlphaResolveObjectParams, options?: RequestInit): Promise<ResolveObjectResponse> => {
  
  return customFetch<ResolveObjectResponse>(getGetApiAlphaResolveObjectUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Fetch federated instances.
 */
export const getGetApiAlphaFederatedInstancesUrl = () => {


  

  return `/api/alpha/federated_instances`
}

export const getApiAlphaFederatedInstances = async ( options?: RequestInit): Promise<GetFederatedInstancesResponse> => {
  
  return customFetch<GetFederatedInstancesResponse>(getGetApiAlphaFederatedInstancesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Suggest people and communities while users type.
 */
export const getGetApiAlphaSuggestCompletionUrl = (params?: GetApiAlphaSuggestCompletionParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/suggest_completion?${stringifiedParams}` : `/api/alpha/suggest_completion`
}

export const getApiAlphaSuggestCompletion = async (params?: GetApiAlphaSuggestCompletionParams, options?: RequestInit): Promise<GetSuggestCompletionResponse> => {
  
  return customFetch<GetSuggestCompletionResponse>(getGetApiAlphaSuggestCompletionUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get modlog.
 */
export const getGetApiAlphaModlogUrl = (params?: GetApiAlphaModlogParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/modlog?${stringifiedParams}` : `/api/alpha/modlog`
}

export const getApiAlphaModlog = async (params?: GetApiAlphaModlogParams, options?: RequestInit): Promise<GetModLogResponse> => {
  
  return customFetch<GetModLogResponse>(getGetApiAlphaModlogUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


