/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type {
  DefaultError,
  GetApiAlphaModlogParams,
  GetApiAlphaResolveObjectParams,
  GetApiAlphaSearchParams,
  GetApiAlphaSuggestCompletionParams,
  GetFederatedInstancesResponse,
  GetModLogResponse,
  GetSuggestCompletionResponse,
  ResolveObjectResponse,
  SearchResponse,
  UnprocessableEntityResponse
} from '../../schemas';


/**
 * @summary Search PieFed.
 */
export type getApiAlphaSearchResponse200 = {
  data: SearchResponse
  status: 200
}

export type getApiAlphaSearchResponse400 = {
  data: DefaultError
  status: 400
}

export type getApiAlphaSearchResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type getApiAlphaSearchResponseSuccess = (getApiAlphaSearchResponse200) & {
  headers: Headers;
};
export type getApiAlphaSearchResponseError = (getApiAlphaSearchResponse400 | getApiAlphaSearchResponse422) & {
  headers: Headers;
};

export type getApiAlphaSearchResponse = (getApiAlphaSearchResponseSuccess | getApiAlphaSearchResponseError)

export const getGetApiAlphaSearchUrl = (params: GetApiAlphaSearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/search?${stringifiedParams}` : `/api/alpha/search`
}

export const getApiAlphaSearch = async (params: GetApiAlphaSearchParams, options?: RequestInit): Promise<getApiAlphaSearchResponse> => {
  
  const res = await fetch(getGetApiAlphaSearchUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiAlphaSearchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiAlphaSearchResponse
}


/**
 * @summary Fetch a non-local / federated object.
 */
export type getApiAlphaResolveObjectResponse200 = {
  data: ResolveObjectResponse
  status: 200
}

export type getApiAlphaResolveObjectResponse400 = {
  data: DefaultError
  status: 400
}

export type getApiAlphaResolveObjectResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type getApiAlphaResolveObjectResponseSuccess = (getApiAlphaResolveObjectResponse200) & {
  headers: Headers;
};
export type getApiAlphaResolveObjectResponseError = (getApiAlphaResolveObjectResponse400 | getApiAlphaResolveObjectResponse422) & {
  headers: Headers;
};

export type getApiAlphaResolveObjectResponse = (getApiAlphaResolveObjectResponseSuccess | getApiAlphaResolveObjectResponseError)

export const getGetApiAlphaResolveObjectUrl = (params: GetApiAlphaResolveObjectParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/resolve_object?${stringifiedParams}` : `/api/alpha/resolve_object`
}

export const getApiAlphaResolveObject = async (params: GetApiAlphaResolveObjectParams, options?: RequestInit): Promise<getApiAlphaResolveObjectResponse> => {
  
  const res = await fetch(getGetApiAlphaResolveObjectUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiAlphaResolveObjectResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiAlphaResolveObjectResponse
}


/**
 * @summary Fetch federated instances.
 */
export type getApiAlphaFederatedInstancesResponse200 = {
  data: GetFederatedInstancesResponse
  status: 200
}

export type getApiAlphaFederatedInstancesResponse400 = {
  data: DefaultError
  status: 400
}
    
export type getApiAlphaFederatedInstancesResponseSuccess = (getApiAlphaFederatedInstancesResponse200) & {
  headers: Headers;
};
export type getApiAlphaFederatedInstancesResponseError = (getApiAlphaFederatedInstancesResponse400) & {
  headers: Headers;
};

export type getApiAlphaFederatedInstancesResponse = (getApiAlphaFederatedInstancesResponseSuccess | getApiAlphaFederatedInstancesResponseError)

export const getGetApiAlphaFederatedInstancesUrl = () => {


  

  return `/api/alpha/federated_instances`
}

export const getApiAlphaFederatedInstances = async ( options?: RequestInit): Promise<getApiAlphaFederatedInstancesResponse> => {
  
  const res = await fetch(getGetApiAlphaFederatedInstancesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiAlphaFederatedInstancesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiAlphaFederatedInstancesResponse
}


/**
 * @summary Suggest people and communities while users type.
 */
export type getApiAlphaSuggestCompletionResponse200 = {
  data: GetSuggestCompletionResponse
  status: 200
}

export type getApiAlphaSuggestCompletionResponse400 = {
  data: DefaultError
  status: 400
}

export type getApiAlphaSuggestCompletionResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type getApiAlphaSuggestCompletionResponseSuccess = (getApiAlphaSuggestCompletionResponse200) & {
  headers: Headers;
};
export type getApiAlphaSuggestCompletionResponseError = (getApiAlphaSuggestCompletionResponse400 | getApiAlphaSuggestCompletionResponse422) & {
  headers: Headers;
};

export type getApiAlphaSuggestCompletionResponse = (getApiAlphaSuggestCompletionResponseSuccess | getApiAlphaSuggestCompletionResponseError)

export const getGetApiAlphaSuggestCompletionUrl = (params?: GetApiAlphaSuggestCompletionParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/suggest_completion?${stringifiedParams}` : `/api/alpha/suggest_completion`
}

export const getApiAlphaSuggestCompletion = async (params?: GetApiAlphaSuggestCompletionParams, options?: RequestInit): Promise<getApiAlphaSuggestCompletionResponse> => {
  
  const res = await fetch(getGetApiAlphaSuggestCompletionUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiAlphaSuggestCompletionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiAlphaSuggestCompletionResponse
}


/**
 * @summary Get modlog.
 */
export type getApiAlphaModlogResponse200 = {
  data: GetModLogResponse
  status: 200
}

export type getApiAlphaModlogResponse400 = {
  data: DefaultError
  status: 400
}

export type getApiAlphaModlogResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type getApiAlphaModlogResponse429 = {
  data: DefaultError
  status: 429
}
    
export type getApiAlphaModlogResponseSuccess = (getApiAlphaModlogResponse200) & {
  headers: Headers;
};
export type getApiAlphaModlogResponseError = (getApiAlphaModlogResponse400 | getApiAlphaModlogResponse422 | getApiAlphaModlogResponse429) & {
  headers: Headers;
};

export type getApiAlphaModlogResponse = (getApiAlphaModlogResponseSuccess | getApiAlphaModlogResponseError)

export const getGetApiAlphaModlogUrl = (params?: GetApiAlphaModlogParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/modlog?${stringifiedParams}` : `/api/alpha/modlog`
}

export const getApiAlphaModlog = async (params?: GetApiAlphaModlogParams, options?: RequestInit): Promise<getApiAlphaModlogResponse> => {
  
  const res = await fetch(getGetApiAlphaModlogUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiAlphaModlogResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiAlphaModlogResponse
}


