/**
 * Generated by orval
 * Do not edit manually.
 */
import * as zod from 'zod';


/**
 * @summary Upload a general image.
 */
export const postApiAlphaUploadImageBody = zod.object({
  "file": zod.instanceof(File)
})

export const postApiAlphaUploadImageResponse = zod.object({
  "url": zod.string(),
  "liked_only": zod.boolean().optional(),
  "saved_only": zod.boolean().optional(),
  "q": zod.string().optional()
})

/**
 * @summary Upload a community image.
 */
export const postApiAlphaUploadCommunityImageBody = zod.object({
  "file": zod.instanceof(File)
})

export const postApiAlphaUploadCommunityImageResponse = zod.object({
  "url": zod.string(),
  "liked_only": zod.boolean().optional(),
  "saved_only": zod.boolean().optional(),
  "q": zod.string().optional()
})

/**
 * @summary Upload a user image.
 */
export const postApiAlphaUploadUserImageBody = zod.object({
  "file": zod.instanceof(File)
})

export const postApiAlphaUploadUserImageResponse = zod.object({
  "url": zod.string(),
  "liked_only": zod.boolean().optional(),
  "saved_only": zod.boolean().optional(),
  "q": zod.string().optional()
})

/**
 * @summary Delete a user image.
 */
export const postApiAlphaImageDeleteBody = zod.object({
  "file": zod.string()
})

export const postApiAlphaImageDeleteResponse = zod.object({
  "result": zod.string()
})

