/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import type {
  CreateFeedRequest,
  DefaultError,
  DeleteFeedRequest,
  EditFeedRequest,
  FeedListResponse,
  FeedView,
  FollowFeedRequest,
  GetApiAlphaFeedListParams,
  GetApiAlphaFeedParams,
  UnprocessableEntityResponse
} from '../../schemas';


/**
 * @summary Get a feed
 */
export type getApiAlphaFeedResponse200 = {
  data: FeedView
  status: 200
}

export type getApiAlphaFeedResponse400 = {
  data: DefaultError
  status: 400
}

export type getApiAlphaFeedResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type getApiAlphaFeedResponseSuccess = (getApiAlphaFeedResponse200) & {
  headers: Headers;
};
export type getApiAlphaFeedResponseError = (getApiAlphaFeedResponse400 | getApiAlphaFeedResponse422) & {
  headers: Headers;
};

export type getApiAlphaFeedResponse = (getApiAlphaFeedResponseSuccess | getApiAlphaFeedResponseError)

export const getGetApiAlphaFeedUrl = (params?: GetApiAlphaFeedParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/feed?${stringifiedParams}` : `/api/alpha/feed`
}

export const getApiAlphaFeed = async (params?: GetApiAlphaFeedParams, options?: RequestInit): Promise<getApiAlphaFeedResponse> => {
  
  const res = await fetch(getGetApiAlphaFeedUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiAlphaFeedResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiAlphaFeedResponse
}


/**
 * @summary Create a new feed.
 */
export type postApiAlphaFeedResponse200 = {
  data: FeedView
  status: 200
}

export type postApiAlphaFeedResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaFeedResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}

export type postApiAlphaFeedResponse429 = {
  data: DefaultError
  status: 429
}
    
export type postApiAlphaFeedResponseSuccess = (postApiAlphaFeedResponse200) & {
  headers: Headers;
};
export type postApiAlphaFeedResponseError = (postApiAlphaFeedResponse400 | postApiAlphaFeedResponse422 | postApiAlphaFeedResponse429) & {
  headers: Headers;
};

export type postApiAlphaFeedResponse = (postApiAlphaFeedResponseSuccess | postApiAlphaFeedResponseError)

export const getPostApiAlphaFeedUrl = () => {


  

  return `/api/alpha/feed`
}

export const postApiAlphaFeed = async (createFeedRequest: CreateFeedRequest, options?: RequestInit): Promise<postApiAlphaFeedResponse> => {
  
  const res = await fetch(getPostApiAlphaFeedUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createFeedRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAlphaFeedResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAlphaFeedResponse
}


/**
 * @summary Edit feed.
 */
export type putApiAlphaFeedResponse200 = {
  data: FeedView
  status: 200
}

export type putApiAlphaFeedResponse400 = {
  data: DefaultError
  status: 400
}

export type putApiAlphaFeedResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type putApiAlphaFeedResponseSuccess = (putApiAlphaFeedResponse200) & {
  headers: Headers;
};
export type putApiAlphaFeedResponseError = (putApiAlphaFeedResponse400 | putApiAlphaFeedResponse422) & {
  headers: Headers;
};

export type putApiAlphaFeedResponse = (putApiAlphaFeedResponseSuccess | putApiAlphaFeedResponseError)

export const getPutApiAlphaFeedUrl = () => {


  

  return `/api/alpha/feed`
}

export const putApiAlphaFeed = async (editFeedRequest: EditFeedRequest, options?: RequestInit): Promise<putApiAlphaFeedResponse> => {
  
  const res = await fetch(getPutApiAlphaFeedUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      editFeedRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: putApiAlphaFeedResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as putApiAlphaFeedResponse
}


/**
 * @summary Get list of feeds
 */
export type getApiAlphaFeedListResponse200 = {
  data: FeedListResponse
  status: 200
}

export type getApiAlphaFeedListResponse400 = {
  data: DefaultError
  status: 400
}

export type getApiAlphaFeedListResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type getApiAlphaFeedListResponseSuccess = (getApiAlphaFeedListResponse200) & {
  headers: Headers;
};
export type getApiAlphaFeedListResponseError = (getApiAlphaFeedListResponse400 | getApiAlphaFeedListResponse422) & {
  headers: Headers;
};

export type getApiAlphaFeedListResponse = (getApiAlphaFeedListResponseSuccess | getApiAlphaFeedListResponseError)

export const getGetApiAlphaFeedListUrl = (params?: GetApiAlphaFeedListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alpha/feed/list?${stringifiedParams}` : `/api/alpha/feed/list`
}

export const getApiAlphaFeedList = async (params?: GetApiAlphaFeedListParams, options?: RequestInit): Promise<getApiAlphaFeedListResponse> => {
  
  const res = await fetch(getGetApiAlphaFeedListUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiAlphaFeedListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiAlphaFeedListResponse
}


/**
 * @summary Follow / subscribe / leave / unsubscribe to a feed.
 */
export type postApiAlphaFeedFollowResponse200 = {
  data: FeedView
  status: 200
}

export type postApiAlphaFeedFollowResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaFeedFollowResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaFeedFollowResponseSuccess = (postApiAlphaFeedFollowResponse200) & {
  headers: Headers;
};
export type postApiAlphaFeedFollowResponseError = (postApiAlphaFeedFollowResponse400 | postApiAlphaFeedFollowResponse422) & {
  headers: Headers;
};

export type postApiAlphaFeedFollowResponse = (postApiAlphaFeedFollowResponseSuccess | postApiAlphaFeedFollowResponseError)

export const getPostApiAlphaFeedFollowUrl = () => {


  

  return `/api/alpha/feed/follow`
}

export const postApiAlphaFeedFollow = async (followFeedRequest: FollowFeedRequest, options?: RequestInit): Promise<postApiAlphaFeedFollowResponse> => {
  
  const res = await fetch(getPostApiAlphaFeedFollowUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      followFeedRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAlphaFeedFollowResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAlphaFeedFollowResponse
}


/**
 * @summary Delete a feed.
 */
export type postApiAlphaFeedDeleteResponse200 = {
  data: FeedView
  status: 200
}

export type postApiAlphaFeedDeleteResponse400 = {
  data: DefaultError
  status: 400
}

export type postApiAlphaFeedDeleteResponse422 = {
  data: UnprocessableEntityResponse
  status: 422
}
    
export type postApiAlphaFeedDeleteResponseSuccess = (postApiAlphaFeedDeleteResponse200) & {
  headers: Headers;
};
export type postApiAlphaFeedDeleteResponseError = (postApiAlphaFeedDeleteResponse400 | postApiAlphaFeedDeleteResponse422) & {
  headers: Headers;
};

export type postApiAlphaFeedDeleteResponse = (postApiAlphaFeedDeleteResponseSuccess | postApiAlphaFeedDeleteResponseError)

export const getPostApiAlphaFeedDeleteUrl = () => {


  

  return `/api/alpha/feed/delete`
}

export const postApiAlphaFeedDelete = async (deleteFeedRequest: DeleteFeedRequest, options?: RequestInit): Promise<postApiAlphaFeedDeleteResponse> => {
  
  const res = await fetch(getPostApiAlphaFeedDeleteUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      deleteFeedRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiAlphaFeedDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiAlphaFeedDeleteResponse
}


