/**
 * Generated by orval
 * Do not edit manually.
 */
import * as zod from 'zod';


/**
 * @summary List private messages.
 */
export const getApiAlphaPrivateMessageListQueryParams = zod.object({
  "page": zod.number().optional(),
  "limit": zod.number().optional(),
  "unread_only": zod.boolean().optional()
})

export const getApiAlphaPrivateMessageListResponsePrivateMessagesItemCreatorExtraFieldsMax = 4;

export const getApiAlphaPrivateMessageListResponsePrivateMessagesItemCreatorNoteMax = 50;

export const getApiAlphaPrivateMessageListResponsePrivateMessagesItemRecipientExtraFieldsMax = 4;

export const getApiAlphaPrivateMessageListResponsePrivateMessagesItemRecipientNoteMax = 50;



export const getApiAlphaPrivateMessageListResponse = zod.object({
  "private_messages": zod.array(zod.object({
  "private_message": zod.object({
  "id": zod.number(),
  "creator_id": zod.number(),
  "recipient_id": zod.number(),
  "content": zod.string(),
  "deleted": zod.boolean(),
  "read": zod.boolean(),
  "published": zod.string(),
  "ap_id": zod.string(),
  "local": zod.boolean()
}),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(getApiAlphaPrivateMessageListResponsePrivateMessagesItemCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(getApiAlphaPrivateMessageListResponsePrivateMessagesItemCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "recipient": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(getApiAlphaPrivateMessageListResponsePrivateMessagesItemRecipientExtraFieldsMax).optional(),
  "note": zod.string().max(getApiAlphaPrivateMessageListResponsePrivateMessagesItemRecipientNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "conversation_id": zod.number().optional()
}))
})

/**
 * @summary Get conversation with a specific person.
 */
export const getApiAlphaPrivateMessageConversationQueryPageDefault = 1;export const getApiAlphaPrivateMessageConversationQueryLimitDefault = 10;

export const getApiAlphaPrivateMessageConversationQueryParams = zod.object({
  "person_id": zod.number().optional().describe('One of either person_id or conversation_id must be specified'),
  "conversation_id": zod.number().optional().describe('One of either person_id or conversation_id must be specified'),
  "page": zod.number().default(getApiAlphaPrivateMessageConversationQueryPageDefault),
  "limit": zod.number().default(getApiAlphaPrivateMessageConversationQueryLimitDefault)
})

export const getApiAlphaPrivateMessageConversationResponsePrivateMessagesItemCreatorExtraFieldsMax = 4;

export const getApiAlphaPrivateMessageConversationResponsePrivateMessagesItemCreatorNoteMax = 50;

export const getApiAlphaPrivateMessageConversationResponsePrivateMessagesItemRecipientExtraFieldsMax = 4;

export const getApiAlphaPrivateMessageConversationResponsePrivateMessagesItemRecipientNoteMax = 50;



export const getApiAlphaPrivateMessageConversationResponse = zod.object({
  "private_messages": zod.array(zod.object({
  "private_message": zod.object({
  "id": zod.number(),
  "creator_id": zod.number(),
  "recipient_id": zod.number(),
  "content": zod.string(),
  "deleted": zod.boolean(),
  "read": zod.boolean(),
  "published": zod.string(),
  "ap_id": zod.string(),
  "local": zod.boolean()
}),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(getApiAlphaPrivateMessageConversationResponsePrivateMessagesItemCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(getApiAlphaPrivateMessageConversationResponsePrivateMessagesItemCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "recipient": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(getApiAlphaPrivateMessageConversationResponsePrivateMessagesItemRecipientExtraFieldsMax).optional(),
  "note": zod.string().max(getApiAlphaPrivateMessageConversationResponsePrivateMessagesItemRecipientNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "conversation_id": zod.number().optional()
}))
})

/**
 * @summary Leave a conversation
 */
export const postApiAlphaPrivateMessageConversationLeaveBody = zod.object({
  "conversation_id": zod.number()
})

/**
 * @summary Create a new private message.
 */
export const postApiAlphaPrivateMessageBody = zod.object({
  "content": zod.string(),
  "recipient_id": zod.number()
})

export const postApiAlphaPrivateMessageResponsePrivateMessageViewCreatorExtraFieldsMax = 4;

export const postApiAlphaPrivateMessageResponsePrivateMessageViewCreatorNoteMax = 50;

export const postApiAlphaPrivateMessageResponsePrivateMessageViewRecipientExtraFieldsMax = 4;

export const postApiAlphaPrivateMessageResponsePrivateMessageViewRecipientNoteMax = 50;



export const postApiAlphaPrivateMessageResponse = zod.object({
  "private_message_view": zod.object({
  "private_message": zod.object({
  "id": zod.number(),
  "creator_id": zod.number(),
  "recipient_id": zod.number(),
  "content": zod.string(),
  "deleted": zod.boolean(),
  "read": zod.boolean(),
  "published": zod.string(),
  "ap_id": zod.string(),
  "local": zod.boolean()
}),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaPrivateMessageResponsePrivateMessageViewCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaPrivateMessageResponsePrivateMessageViewCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "recipient": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaPrivateMessageResponsePrivateMessageViewRecipientExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaPrivateMessageResponsePrivateMessageViewRecipientNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "conversation_id": zod.number().optional()
})
})

/**
 * @summary Edit a private message.
 */
export const putApiAlphaPrivateMessageBody = zod.object({
  "private_message_id": zod.number(),
  "content": zod.string()
})

export const putApiAlphaPrivateMessageResponsePrivateMessageViewCreatorExtraFieldsMax = 4;

export const putApiAlphaPrivateMessageResponsePrivateMessageViewCreatorNoteMax = 50;

export const putApiAlphaPrivateMessageResponsePrivateMessageViewRecipientExtraFieldsMax = 4;

export const putApiAlphaPrivateMessageResponsePrivateMessageViewRecipientNoteMax = 50;



export const putApiAlphaPrivateMessageResponse = zod.object({
  "private_message_view": zod.object({
  "private_message": zod.object({
  "id": zod.number(),
  "creator_id": zod.number(),
  "recipient_id": zod.number(),
  "content": zod.string(),
  "deleted": zod.boolean(),
  "read": zod.boolean(),
  "published": zod.string(),
  "ap_id": zod.string(),
  "local": zod.boolean()
}),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(putApiAlphaPrivateMessageResponsePrivateMessageViewCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(putApiAlphaPrivateMessageResponsePrivateMessageViewCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "recipient": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(putApiAlphaPrivateMessageResponsePrivateMessageViewRecipientExtraFieldsMax).optional(),
  "note": zod.string().max(putApiAlphaPrivateMessageResponsePrivateMessageViewRecipientNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "conversation_id": zod.number().optional()
})
})

/**
 * @summary Mark a private message as read or unread.
 */
export const postApiAlphaPrivateMessageMarkAsReadBody = zod.object({
  "private_message_id": zod.number(),
  "read": zod.boolean()
})

export const postApiAlphaPrivateMessageMarkAsReadResponsePrivateMessageViewCreatorExtraFieldsMax = 4;

export const postApiAlphaPrivateMessageMarkAsReadResponsePrivateMessageViewCreatorNoteMax = 50;

export const postApiAlphaPrivateMessageMarkAsReadResponsePrivateMessageViewRecipientExtraFieldsMax = 4;

export const postApiAlphaPrivateMessageMarkAsReadResponsePrivateMessageViewRecipientNoteMax = 50;



export const postApiAlphaPrivateMessageMarkAsReadResponse = zod.object({
  "private_message_view": zod.object({
  "private_message": zod.object({
  "id": zod.number(),
  "creator_id": zod.number(),
  "recipient_id": zod.number(),
  "content": zod.string(),
  "deleted": zod.boolean(),
  "read": zod.boolean(),
  "published": zod.string(),
  "ap_id": zod.string(),
  "local": zod.boolean()
}),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaPrivateMessageMarkAsReadResponsePrivateMessageViewCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaPrivateMessageMarkAsReadResponsePrivateMessageViewCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "recipient": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaPrivateMessageMarkAsReadResponsePrivateMessageViewRecipientExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaPrivateMessageMarkAsReadResponsePrivateMessageViewRecipientNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "conversation_id": zod.number().optional()
})
})

/**
 * @summary Delete or restore a private message.
 */
export const postApiAlphaPrivateMessageDeleteBody = zod.object({
  "private_message_id": zod.number(),
  "deleted": zod.boolean()
})

export const postApiAlphaPrivateMessageDeleteResponsePrivateMessageViewCreatorExtraFieldsMax = 4;

export const postApiAlphaPrivateMessageDeleteResponsePrivateMessageViewCreatorNoteMax = 50;

export const postApiAlphaPrivateMessageDeleteResponsePrivateMessageViewRecipientExtraFieldsMax = 4;

export const postApiAlphaPrivateMessageDeleteResponsePrivateMessageViewRecipientNoteMax = 50;



export const postApiAlphaPrivateMessageDeleteResponse = zod.object({
  "private_message_view": zod.object({
  "private_message": zod.object({
  "id": zod.number(),
  "creator_id": zod.number(),
  "recipient_id": zod.number(),
  "content": zod.string(),
  "deleted": zod.boolean(),
  "read": zod.boolean(),
  "published": zod.string(),
  "ap_id": zod.string(),
  "local": zod.boolean()
}),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaPrivateMessageDeleteResponsePrivateMessageViewCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaPrivateMessageDeleteResponsePrivateMessageViewCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "recipient": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaPrivateMessageDeleteResponsePrivateMessageViewRecipientExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaPrivateMessageDeleteResponsePrivateMessageViewRecipientNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "conversation_id": zod.number().optional()
})
})

/**
 * @summary Report a private message.
 */
export const postApiAlphaPrivateMessageReportBody = zod.object({
  "private_message_id": zod.number(),
  "reason": zod.string()
})

export const postApiAlphaPrivateMessageReportResponsePrivateMessageViewCreatorExtraFieldsMax = 4;

export const postApiAlphaPrivateMessageReportResponsePrivateMessageViewCreatorNoteMax = 50;

export const postApiAlphaPrivateMessageReportResponsePrivateMessageViewRecipientExtraFieldsMax = 4;

export const postApiAlphaPrivateMessageReportResponsePrivateMessageViewRecipientNoteMax = 50;



export const postApiAlphaPrivateMessageReportResponse = zod.object({
  "private_message_view": zod.object({
  "private_message": zod.object({
  "id": zod.number(),
  "creator_id": zod.number(),
  "recipient_id": zod.number(),
  "content": zod.string(),
  "deleted": zod.boolean(),
  "read": zod.boolean(),
  "published": zod.string(),
  "ap_id": zod.string(),
  "local": zod.boolean()
}),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaPrivateMessageReportResponsePrivateMessageViewCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaPrivateMessageReportResponsePrivateMessageViewCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "recipient": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaPrivateMessageReportResponsePrivateMessageViewRecipientExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaPrivateMessageReportResponsePrivateMessageViewRecipientNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "conversation_id": zod.number().optional()
})
})

