/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import * as zod from 'zod';


/**
 * @summary Get the list of applications ready for admin review
 */
export const getApiAlphaAdminRegistrationApplicationListQueryLimitDefault = 30;export const getApiAlphaAdminRegistrationApplicationListQueryPageDefault = 1;export const getApiAlphaAdminRegistrationApplicationListQueryPendingOnlyDefault = true;export const getApiAlphaAdminRegistrationApplicationListQuerySortDefault = "New";

export const getApiAlphaAdminRegistrationApplicationListQueryParams = zod.object({
  "limit": zod.number().default(getApiAlphaAdminRegistrationApplicationListQueryLimitDefault),
  "page": zod.number().default(getApiAlphaAdminRegistrationApplicationListQueryPageDefault),
  "pending_only": zod.boolean().default(getApiAlphaAdminRegistrationApplicationListQueryPendingOnlyDefault),
  "sort": zod.enum(['Old', 'New']).default(getApiAlphaAdminRegistrationApplicationListQuerySortDefault)
})

export const getApiAlphaAdminRegistrationApplicationListResponseRegistrationsItemApprovedByExtraFieldsMax = 4;

export const getApiAlphaAdminRegistrationApplicationListResponseRegistrationsItemApprovedByNoteMax = 50;



export const getApiAlphaAdminRegistrationApplicationListResponse = zod.object({
  "registrations": zod.array(zod.object({
  "answer": zod.string().nullable(),
  "applied_at": zod.string().optional(),
  "country_code": zod.string().optional(),
  "email": zod.string().nullable(),
  "ip_address": zod.string().nullable(),
  "throwaway_email": zod.boolean().optional(),
  "user_id": zod.number(),
  "user_name": zod.string(),
  "status": zod.enum(['approved', 'awaiting review']),
  "approved_by": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(getApiAlphaAdminRegistrationApplicationListResponseRegistrationsItemApprovedByExtraFieldsMax).optional(),
  "note": zod.string().max(getApiAlphaAdminRegistrationApplicationListResponseRegistrationsItemApprovedByNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}).optional(),
  "approved_at": zod.string().optional(),
  "referrer": zod.string().optional()
}))
})

/**
 * @summary Approve or deny a registration
 */
export const putApiAlphaAdminRegistrationApplicationApproveBody = zod.object({
  "approve": zod.boolean(),
  "user_id": zod.number()
})

