/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * PieFed 1.6 Alpha API
 * OpenAPI spec version: alpha 1.6
 */
import * as zod from 'zod';


/**
 * @summary List comments, with various filters.
 */
export const getApiAlphaCommentListQueryLimitDefault = 10;export const getApiAlphaCommentListQueryPageDefault = 1;export const getApiAlphaCommentListQuerySortDefault = "New";

export const getApiAlphaCommentListQueryParams = zod.object({
  "limit": zod.number().default(getApiAlphaCommentListQueryLimitDefault),
  "page": zod.number().default(getApiAlphaCommentListQueryPageDefault),
  "sort": zod.enum(['Hot', 'Top', 'TopAll', 'New', 'Old', 'Controversial']).default(getApiAlphaCommentListQuerySortDefault),
  "liked_only": zod.boolean().optional(),
  "saved_only": zod.boolean().optional(),
  "person_id": zod.number().optional(),
  "community_id": zod.number().optional(),
  "post_id": zod.number().optional(),
  "parent_id": zod.number().optional(),
  "max_depth": zod.number().optional(),
  "depth_first": zod.boolean().optional().describe('guarantee parent comments are on the same page as any fetched comments')
})

export const getApiAlphaCommentListResponseCommentsItemCreatorExtraFieldsMax = 4;

export const getApiAlphaCommentListResponseCommentsItemCreatorNoteMax = 50;

export const getApiAlphaCommentListResponseCommentsItemPostEventMaxAttendeesDefault = 0;export const getApiAlphaCommentListResponseCommentsItemPostEventParticipantCountDefault = 0;export const getApiAlphaCommentListResponseCommentsItemPostEventFullDefault = false;export const getApiAlphaCommentListResponseCommentsItemPostEventAnonymousParticipationDefault = false;export const getApiAlphaCommentListResponseCommentsItemPostEventOnlineDefault = false;export const getApiAlphaCommentListResponseCommentsItemPostEventEventFeeAmountDefault = 0;export const getApiAlphaCommentListResponseCommentsItemPostPollLocalOnlyDefault = false;export const getApiAlphaCommentListResponseCommentsItemPostPollChoicesItemNumVotesDefault = 0;export const getApiAlphaCommentListResponseCommentsItemPostPollChoicesMax = 10;



export const getApiAlphaCommentListResponse = zod.object({
  "comments": zod.array(zod.object({
  "activity_alert": zod.boolean(),
  "banned_from_community": zod.boolean(),
  "comment": zod.object({
  "ap_id": zod.string(),
  "body": zod.string(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "path": zod.string(),
  "post_id": zod.number(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "user_id": zod.number(),
  "distinguished": zod.boolean().optional(),
  "updated": zod.string().optional(),
  "locked": zod.boolean().optional(),
  "answer": zod.boolean().optional(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish()
}),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "child_count": zod.number(),
  "comment_id": zod.number(),
  "downvotes": zod.number(),
  "published": zod.string(),
  "score": zod.number(),
  "upvotes": zod.number()
}),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(getApiAlphaCommentListResponseCommentsItemCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(getApiAlphaCommentListResponseCommentsItemCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "creator_banned_from_community": zod.boolean(),
  "creator_blocked": zod.boolean(),
  "creator_is_admin": zod.boolean(),
  "creator_is_moderator": zod.boolean(),
  "post": zod.object({
  "ap_id": zod.string(),
  "community_id": zod.number(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "locked": zod.boolean(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "sticky": zod.boolean(),
  "instance_sticky": zod.boolean(),
  "title": zod.string(),
  "user_id": zod.number(),
  "alt_text": zod.string().optional(),
  "body": zod.string().optional(),
  "small_thumbnail_url": zod.string().optional(),
  "thumbnail_url": zod.string().optional(),
  "updated": zod.string().optional(),
  "url": zod.string().optional(),
  "image_details": zod.object({
  "width": zod.number().optional(),
  "height": zod.number().optional()
}).optional(),
  "cross_posts": zod.array(zod.object({
  "post_id": zod.number().optional(),
  "reply_count": zod.number().optional(),
  "community_name": zod.string().optional()
})).optional(),
  "post_type": zod.enum(['Link', 'Discussion', 'Image', 'Video', 'Poll', 'Event']),
  "tags": zod.string().nullish(),
  "flair": zod.string().nullish(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish(),
  "event": zod.object({
  "start": zod.string(),
  "end": zod.string().optional(),
  "timezone": zod.string().optional(),
  "max_attendees": zod.number().optional(),
  "participant_count": zod.number().optional(),
  "full": zod.boolean().optional(),
  "online_link": zod.string().nullish(),
  "join_mode": zod.string().optional().describe('free, restricted, external, invite'),
  "external_participation_url": zod.string().nullish(),
  "anonymous_participation": zod.boolean().optional(),
  "online": zod.boolean().optional(),
  "buy_tickets_link": zod.string().nullish(),
  "event_fee_currency": zod.string().optional(),
  "event_fee_amount": zod.number().optional(),
  "location": zod.record(zod.string(), zod.unknown()).nullish().describe('JSON object containing location details')
}).optional(),
  "poll": zod.object({
  "end_poll": zod.string().optional(),
  "mode": zod.enum(['single', 'multiple']).describe('single or multiple - determines whether people can vote for one or multiple options'),
  "local_only": zod.boolean().optional(),
  "latest_vote": zod.string().optional(),
  "choices": zod.array(zod.object({
  "id": zod.number(),
  "choice_text": zod.string(),
  "sort_order": zod.number(),
  "num_votes": zod.number().optional().describe('Value is ignored when creating\/editing a poll')
})).max(getApiAlphaCommentListResponseCommentsItemPostPollChoicesMax),
  "my_votes": zod.array(zod.number()).optional()
}).optional()
}),
  "saved": zod.boolean(),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending']).describe('Indicates whether auth\'ed user is subscribed to the community this comment is in or not.'),
  "my_vote": zod.number().optional(),
  "can_auth_user_moderate": zod.boolean().optional()
})),
  "next_page": zod.string().nullish()
})

/**
 * @summary Like / vote on a comment.
 */
export const postApiAlphaCommentLikeBodyPrivateDefault = false;

export const postApiAlphaCommentLikeBody = zod.object({
  "comment_id": zod.number(),
  "score": zod.number().describe('-1 to downvote, 1 to upvote, 0 to revert previous vote'),
  "private": zod.boolean().optional().describe('private votes are not federated to other instances'),
  "emoji": zod.string().optional()
})

export const postApiAlphaCommentLikeResponseCommentViewCreatorExtraFieldsMax = 4;

export const postApiAlphaCommentLikeResponseCommentViewCreatorNoteMax = 50;

export const postApiAlphaCommentLikeResponseCommentViewPostEventMaxAttendeesDefault = 0;export const postApiAlphaCommentLikeResponseCommentViewPostEventParticipantCountDefault = 0;export const postApiAlphaCommentLikeResponseCommentViewPostEventFullDefault = false;export const postApiAlphaCommentLikeResponseCommentViewPostEventAnonymousParticipationDefault = false;export const postApiAlphaCommentLikeResponseCommentViewPostEventOnlineDefault = false;export const postApiAlphaCommentLikeResponseCommentViewPostEventEventFeeAmountDefault = 0;export const postApiAlphaCommentLikeResponseCommentViewPostPollLocalOnlyDefault = false;export const postApiAlphaCommentLikeResponseCommentViewPostPollChoicesItemNumVotesDefault = 0;export const postApiAlphaCommentLikeResponseCommentViewPostPollChoicesMax = 10;



export const postApiAlphaCommentLikeResponse = zod.object({
  "comment_view": zod.object({
  "activity_alert": zod.boolean(),
  "banned_from_community": zod.boolean(),
  "comment": zod.object({
  "ap_id": zod.string(),
  "body": zod.string(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "path": zod.string(),
  "post_id": zod.number(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "user_id": zod.number(),
  "distinguished": zod.boolean().optional(),
  "updated": zod.string().optional(),
  "locked": zod.boolean().optional(),
  "answer": zod.boolean().optional(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish()
}),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "child_count": zod.number(),
  "comment_id": zod.number(),
  "downvotes": zod.number(),
  "published": zod.string(),
  "score": zod.number(),
  "upvotes": zod.number()
}),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommentLikeResponseCommentViewCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommentLikeResponseCommentViewCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "creator_banned_from_community": zod.boolean(),
  "creator_blocked": zod.boolean(),
  "creator_is_admin": zod.boolean(),
  "creator_is_moderator": zod.boolean(),
  "post": zod.object({
  "ap_id": zod.string(),
  "community_id": zod.number(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "locked": zod.boolean(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "sticky": zod.boolean(),
  "instance_sticky": zod.boolean(),
  "title": zod.string(),
  "user_id": zod.number(),
  "alt_text": zod.string().optional(),
  "body": zod.string().optional(),
  "small_thumbnail_url": zod.string().optional(),
  "thumbnail_url": zod.string().optional(),
  "updated": zod.string().optional(),
  "url": zod.string().optional(),
  "image_details": zod.object({
  "width": zod.number().optional(),
  "height": zod.number().optional()
}).optional(),
  "cross_posts": zod.array(zod.object({
  "post_id": zod.number().optional(),
  "reply_count": zod.number().optional(),
  "community_name": zod.string().optional()
})).optional(),
  "post_type": zod.enum(['Link', 'Discussion', 'Image', 'Video', 'Poll', 'Event']),
  "tags": zod.string().nullish(),
  "flair": zod.string().nullish(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish(),
  "event": zod.object({
  "start": zod.string(),
  "end": zod.string().optional(),
  "timezone": zod.string().optional(),
  "max_attendees": zod.number().optional(),
  "participant_count": zod.number().optional(),
  "full": zod.boolean().optional(),
  "online_link": zod.string().nullish(),
  "join_mode": zod.string().optional().describe('free, restricted, external, invite'),
  "external_participation_url": zod.string().nullish(),
  "anonymous_participation": zod.boolean().optional(),
  "online": zod.boolean().optional(),
  "buy_tickets_link": zod.string().nullish(),
  "event_fee_currency": zod.string().optional(),
  "event_fee_amount": zod.number().optional(),
  "location": zod.record(zod.string(), zod.unknown()).nullish().describe('JSON object containing location details')
}).optional(),
  "poll": zod.object({
  "end_poll": zod.string().optional(),
  "mode": zod.enum(['single', 'multiple']).describe('single or multiple - determines whether people can vote for one or multiple options'),
  "local_only": zod.boolean().optional(),
  "latest_vote": zod.string().optional(),
  "choices": zod.array(zod.object({
  "id": zod.number(),
  "choice_text": zod.string(),
  "sort_order": zod.number(),
  "num_votes": zod.number().optional().describe('Value is ignored when creating\/editing a poll')
})).max(postApiAlphaCommentLikeResponseCommentViewPostPollChoicesMax),
  "my_votes": zod.array(zod.number()).optional()
}).optional()
}),
  "saved": zod.boolean(),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending']).describe('Indicates whether auth\'ed user is subscribed to the community this comment is in or not.'),
  "my_vote": zod.number().optional(),
  "can_auth_user_moderate": zod.boolean().optional()
})
})

/**
 * @summary Save a comment.
 */
export const putApiAlphaCommentSaveBody = zod.object({
  "comment_id": zod.number(),
  "save": zod.boolean()
})

export const putApiAlphaCommentSaveResponseCommentViewCreatorExtraFieldsMax = 4;

export const putApiAlphaCommentSaveResponseCommentViewCreatorNoteMax = 50;

export const putApiAlphaCommentSaveResponseCommentViewPostEventMaxAttendeesDefault = 0;export const putApiAlphaCommentSaveResponseCommentViewPostEventParticipantCountDefault = 0;export const putApiAlphaCommentSaveResponseCommentViewPostEventFullDefault = false;export const putApiAlphaCommentSaveResponseCommentViewPostEventAnonymousParticipationDefault = false;export const putApiAlphaCommentSaveResponseCommentViewPostEventOnlineDefault = false;export const putApiAlphaCommentSaveResponseCommentViewPostEventEventFeeAmountDefault = 0;export const putApiAlphaCommentSaveResponseCommentViewPostPollLocalOnlyDefault = false;export const putApiAlphaCommentSaveResponseCommentViewPostPollChoicesItemNumVotesDefault = 0;export const putApiAlphaCommentSaveResponseCommentViewPostPollChoicesMax = 10;



export const putApiAlphaCommentSaveResponse = zod.object({
  "comment_view": zod.object({
  "activity_alert": zod.boolean(),
  "banned_from_community": zod.boolean(),
  "comment": zod.object({
  "ap_id": zod.string(),
  "body": zod.string(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "path": zod.string(),
  "post_id": zod.number(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "user_id": zod.number(),
  "distinguished": zod.boolean().optional(),
  "updated": zod.string().optional(),
  "locked": zod.boolean().optional(),
  "answer": zod.boolean().optional(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish()
}),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "child_count": zod.number(),
  "comment_id": zod.number(),
  "downvotes": zod.number(),
  "published": zod.string(),
  "score": zod.number(),
  "upvotes": zod.number()
}),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(putApiAlphaCommentSaveResponseCommentViewCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(putApiAlphaCommentSaveResponseCommentViewCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "creator_banned_from_community": zod.boolean(),
  "creator_blocked": zod.boolean(),
  "creator_is_admin": zod.boolean(),
  "creator_is_moderator": zod.boolean(),
  "post": zod.object({
  "ap_id": zod.string(),
  "community_id": zod.number(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "locked": zod.boolean(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "sticky": zod.boolean(),
  "instance_sticky": zod.boolean(),
  "title": zod.string(),
  "user_id": zod.number(),
  "alt_text": zod.string().optional(),
  "body": zod.string().optional(),
  "small_thumbnail_url": zod.string().optional(),
  "thumbnail_url": zod.string().optional(),
  "updated": zod.string().optional(),
  "url": zod.string().optional(),
  "image_details": zod.object({
  "width": zod.number().optional(),
  "height": zod.number().optional()
}).optional(),
  "cross_posts": zod.array(zod.object({
  "post_id": zod.number().optional(),
  "reply_count": zod.number().optional(),
  "community_name": zod.string().optional()
})).optional(),
  "post_type": zod.enum(['Link', 'Discussion', 'Image', 'Video', 'Poll', 'Event']),
  "tags": zod.string().nullish(),
  "flair": zod.string().nullish(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish(),
  "event": zod.object({
  "start": zod.string(),
  "end": zod.string().optional(),
  "timezone": zod.string().optional(),
  "max_attendees": zod.number().optional(),
  "participant_count": zod.number().optional(),
  "full": zod.boolean().optional(),
  "online_link": zod.string().nullish(),
  "join_mode": zod.string().optional().describe('free, restricted, external, invite'),
  "external_participation_url": zod.string().nullish(),
  "anonymous_participation": zod.boolean().optional(),
  "online": zod.boolean().optional(),
  "buy_tickets_link": zod.string().nullish(),
  "event_fee_currency": zod.string().optional(),
  "event_fee_amount": zod.number().optional(),
  "location": zod.record(zod.string(), zod.unknown()).nullish().describe('JSON object containing location details')
}).optional(),
  "poll": zod.object({
  "end_poll": zod.string().optional(),
  "mode": zod.enum(['single', 'multiple']).describe('single or multiple - determines whether people can vote for one or multiple options'),
  "local_only": zod.boolean().optional(),
  "latest_vote": zod.string().optional(),
  "choices": zod.array(zod.object({
  "id": zod.number(),
  "choice_text": zod.string(),
  "sort_order": zod.number(),
  "num_votes": zod.number().optional().describe('Value is ignored when creating\/editing a poll')
})).max(putApiAlphaCommentSaveResponseCommentViewPostPollChoicesMax),
  "my_votes": zod.array(zod.number()).optional()
}).optional()
}),
  "saved": zod.boolean(),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending']).describe('Indicates whether auth\'ed user is subscribed to the community this comment is in or not.'),
  "my_vote": zod.number().optional(),
  "can_auth_user_moderate": zod.boolean().optional()
})
})

/**
 * @summary Subscribe to a comment.
 */
export const putApiAlphaCommentSubscribeBody = zod.object({
  "comment_id": zod.number(),
  "subscribe": zod.boolean()
})

export const putApiAlphaCommentSubscribeResponseCommentViewCreatorExtraFieldsMax = 4;

export const putApiAlphaCommentSubscribeResponseCommentViewCreatorNoteMax = 50;

export const putApiAlphaCommentSubscribeResponseCommentViewPostEventMaxAttendeesDefault = 0;export const putApiAlphaCommentSubscribeResponseCommentViewPostEventParticipantCountDefault = 0;export const putApiAlphaCommentSubscribeResponseCommentViewPostEventFullDefault = false;export const putApiAlphaCommentSubscribeResponseCommentViewPostEventAnonymousParticipationDefault = false;export const putApiAlphaCommentSubscribeResponseCommentViewPostEventOnlineDefault = false;export const putApiAlphaCommentSubscribeResponseCommentViewPostEventEventFeeAmountDefault = 0;export const putApiAlphaCommentSubscribeResponseCommentViewPostPollLocalOnlyDefault = false;export const putApiAlphaCommentSubscribeResponseCommentViewPostPollChoicesItemNumVotesDefault = 0;export const putApiAlphaCommentSubscribeResponseCommentViewPostPollChoicesMax = 10;



export const putApiAlphaCommentSubscribeResponse = zod.object({
  "comment_view": zod.object({
  "activity_alert": zod.boolean(),
  "banned_from_community": zod.boolean(),
  "comment": zod.object({
  "ap_id": zod.string(),
  "body": zod.string(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "path": zod.string(),
  "post_id": zod.number(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "user_id": zod.number(),
  "distinguished": zod.boolean().optional(),
  "updated": zod.string().optional(),
  "locked": zod.boolean().optional(),
  "answer": zod.boolean().optional(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish()
}),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "child_count": zod.number(),
  "comment_id": zod.number(),
  "downvotes": zod.number(),
  "published": zod.string(),
  "score": zod.number(),
  "upvotes": zod.number()
}),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(putApiAlphaCommentSubscribeResponseCommentViewCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(putApiAlphaCommentSubscribeResponseCommentViewCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "creator_banned_from_community": zod.boolean(),
  "creator_blocked": zod.boolean(),
  "creator_is_admin": zod.boolean(),
  "creator_is_moderator": zod.boolean(),
  "post": zod.object({
  "ap_id": zod.string(),
  "community_id": zod.number(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "locked": zod.boolean(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "sticky": zod.boolean(),
  "instance_sticky": zod.boolean(),
  "title": zod.string(),
  "user_id": zod.number(),
  "alt_text": zod.string().optional(),
  "body": zod.string().optional(),
  "small_thumbnail_url": zod.string().optional(),
  "thumbnail_url": zod.string().optional(),
  "updated": zod.string().optional(),
  "url": zod.string().optional(),
  "image_details": zod.object({
  "width": zod.number().optional(),
  "height": zod.number().optional()
}).optional(),
  "cross_posts": zod.array(zod.object({
  "post_id": zod.number().optional(),
  "reply_count": zod.number().optional(),
  "community_name": zod.string().optional()
})).optional(),
  "post_type": zod.enum(['Link', 'Discussion', 'Image', 'Video', 'Poll', 'Event']),
  "tags": zod.string().nullish(),
  "flair": zod.string().nullish(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish(),
  "event": zod.object({
  "start": zod.string(),
  "end": zod.string().optional(),
  "timezone": zod.string().optional(),
  "max_attendees": zod.number().optional(),
  "participant_count": zod.number().optional(),
  "full": zod.boolean().optional(),
  "online_link": zod.string().nullish(),
  "join_mode": zod.string().optional().describe('free, restricted, external, invite'),
  "external_participation_url": zod.string().nullish(),
  "anonymous_participation": zod.boolean().optional(),
  "online": zod.boolean().optional(),
  "buy_tickets_link": zod.string().nullish(),
  "event_fee_currency": zod.string().optional(),
  "event_fee_amount": zod.number().optional(),
  "location": zod.record(zod.string(), zod.unknown()).nullish().describe('JSON object containing location details')
}).optional(),
  "poll": zod.object({
  "end_poll": zod.string().optional(),
  "mode": zod.enum(['single', 'multiple']).describe('single or multiple - determines whether people can vote for one or multiple options'),
  "local_only": zod.boolean().optional(),
  "latest_vote": zod.string().optional(),
  "choices": zod.array(zod.object({
  "id": zod.number(),
  "choice_text": zod.string(),
  "sort_order": zod.number(),
  "num_votes": zod.number().optional().describe('Value is ignored when creating\/editing a poll')
})).max(putApiAlphaCommentSubscribeResponseCommentViewPostPollChoicesMax),
  "my_votes": zod.array(zod.number()).optional()
}).optional()
}),
  "saved": zod.boolean(),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending']).describe('Indicates whether auth\'ed user is subscribed to the community this comment is in or not.'),
  "my_vote": zod.number().optional(),
  "can_auth_user_moderate": zod.boolean().optional()
})
})

/**
 * @summary Create a comment.
 */
export const postApiAlphaCommentBody = zod.object({
  "body": zod.string(),
  "post_id": zod.number(),
  "parent_id": zod.number().optional(),
  "language_id": zod.number().optional()
})

export const postApiAlphaCommentResponseCommentViewCreatorExtraFieldsMax = 4;

export const postApiAlphaCommentResponseCommentViewCreatorNoteMax = 50;

export const postApiAlphaCommentResponseCommentViewPostEventMaxAttendeesDefault = 0;export const postApiAlphaCommentResponseCommentViewPostEventParticipantCountDefault = 0;export const postApiAlphaCommentResponseCommentViewPostEventFullDefault = false;export const postApiAlphaCommentResponseCommentViewPostEventAnonymousParticipationDefault = false;export const postApiAlphaCommentResponseCommentViewPostEventOnlineDefault = false;export const postApiAlphaCommentResponseCommentViewPostEventEventFeeAmountDefault = 0;export const postApiAlphaCommentResponseCommentViewPostPollLocalOnlyDefault = false;export const postApiAlphaCommentResponseCommentViewPostPollChoicesItemNumVotesDefault = 0;export const postApiAlphaCommentResponseCommentViewPostPollChoicesMax = 10;



export const postApiAlphaCommentResponse = zod.object({
  "comment_view": zod.object({
  "activity_alert": zod.boolean(),
  "banned_from_community": zod.boolean(),
  "comment": zod.object({
  "ap_id": zod.string(),
  "body": zod.string(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "path": zod.string(),
  "post_id": zod.number(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "user_id": zod.number(),
  "distinguished": zod.boolean().optional(),
  "updated": zod.string().optional(),
  "locked": zod.boolean().optional(),
  "answer": zod.boolean().optional(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish()
}),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "child_count": zod.number(),
  "comment_id": zod.number(),
  "downvotes": zod.number(),
  "published": zod.string(),
  "score": zod.number(),
  "upvotes": zod.number()
}),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommentResponseCommentViewCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommentResponseCommentViewCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "creator_banned_from_community": zod.boolean(),
  "creator_blocked": zod.boolean(),
  "creator_is_admin": zod.boolean(),
  "creator_is_moderator": zod.boolean(),
  "post": zod.object({
  "ap_id": zod.string(),
  "community_id": zod.number(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "locked": zod.boolean(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "sticky": zod.boolean(),
  "instance_sticky": zod.boolean(),
  "title": zod.string(),
  "user_id": zod.number(),
  "alt_text": zod.string().optional(),
  "body": zod.string().optional(),
  "small_thumbnail_url": zod.string().optional(),
  "thumbnail_url": zod.string().optional(),
  "updated": zod.string().optional(),
  "url": zod.string().optional(),
  "image_details": zod.object({
  "width": zod.number().optional(),
  "height": zod.number().optional()
}).optional(),
  "cross_posts": zod.array(zod.object({
  "post_id": zod.number().optional(),
  "reply_count": zod.number().optional(),
  "community_name": zod.string().optional()
})).optional(),
  "post_type": zod.enum(['Link', 'Discussion', 'Image', 'Video', 'Poll', 'Event']),
  "tags": zod.string().nullish(),
  "flair": zod.string().nullish(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish(),
  "event": zod.object({
  "start": zod.string(),
  "end": zod.string().optional(),
  "timezone": zod.string().optional(),
  "max_attendees": zod.number().optional(),
  "participant_count": zod.number().optional(),
  "full": zod.boolean().optional(),
  "online_link": zod.string().nullish(),
  "join_mode": zod.string().optional().describe('free, restricted, external, invite'),
  "external_participation_url": zod.string().nullish(),
  "anonymous_participation": zod.boolean().optional(),
  "online": zod.boolean().optional(),
  "buy_tickets_link": zod.string().nullish(),
  "event_fee_currency": zod.string().optional(),
  "event_fee_amount": zod.number().optional(),
  "location": zod.record(zod.string(), zod.unknown()).nullish().describe('JSON object containing location details')
}).optional(),
  "poll": zod.object({
  "end_poll": zod.string().optional(),
  "mode": zod.enum(['single', 'multiple']).describe('single or multiple - determines whether people can vote for one or multiple options'),
  "local_only": zod.boolean().optional(),
  "latest_vote": zod.string().optional(),
  "choices": zod.array(zod.object({
  "id": zod.number(),
  "choice_text": zod.string(),
  "sort_order": zod.number(),
  "num_votes": zod.number().optional().describe('Value is ignored when creating\/editing a poll')
})).max(postApiAlphaCommentResponseCommentViewPostPollChoicesMax),
  "my_votes": zod.array(zod.number()).optional()
}).optional()
}),
  "saved": zod.boolean(),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending']).describe('Indicates whether auth\'ed user is subscribed to the community this comment is in or not.'),
  "my_vote": zod.number().optional(),
  "can_auth_user_moderate": zod.boolean().optional()
})
})

/**
 * @summary Edit a comment.
 */
export const putApiAlphaCommentBodyDistinguishedDefault = false;

export const putApiAlphaCommentBody = zod.object({
  "body": zod.string(),
  "comment_id": zod.number(),
  "language_id": zod.number().optional(),
  "distinguished": zod.boolean().optional().describe('Visibly mark reply as from a moderator in the web UI')
})

export const putApiAlphaCommentResponseCommentViewCreatorExtraFieldsMax = 4;

export const putApiAlphaCommentResponseCommentViewCreatorNoteMax = 50;

export const putApiAlphaCommentResponseCommentViewPostEventMaxAttendeesDefault = 0;export const putApiAlphaCommentResponseCommentViewPostEventParticipantCountDefault = 0;export const putApiAlphaCommentResponseCommentViewPostEventFullDefault = false;export const putApiAlphaCommentResponseCommentViewPostEventAnonymousParticipationDefault = false;export const putApiAlphaCommentResponseCommentViewPostEventOnlineDefault = false;export const putApiAlphaCommentResponseCommentViewPostEventEventFeeAmountDefault = 0;export const putApiAlphaCommentResponseCommentViewPostPollLocalOnlyDefault = false;export const putApiAlphaCommentResponseCommentViewPostPollChoicesItemNumVotesDefault = 0;export const putApiAlphaCommentResponseCommentViewPostPollChoicesMax = 10;



export const putApiAlphaCommentResponse = zod.object({
  "comment_view": zod.object({
  "activity_alert": zod.boolean(),
  "banned_from_community": zod.boolean(),
  "comment": zod.object({
  "ap_id": zod.string(),
  "body": zod.string(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "path": zod.string(),
  "post_id": zod.number(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "user_id": zod.number(),
  "distinguished": zod.boolean().optional(),
  "updated": zod.string().optional(),
  "locked": zod.boolean().optional(),
  "answer": zod.boolean().optional(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish()
}),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "child_count": zod.number(),
  "comment_id": zod.number(),
  "downvotes": zod.number(),
  "published": zod.string(),
  "score": zod.number(),
  "upvotes": zod.number()
}),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(putApiAlphaCommentResponseCommentViewCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(putApiAlphaCommentResponseCommentViewCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "creator_banned_from_community": zod.boolean(),
  "creator_blocked": zod.boolean(),
  "creator_is_admin": zod.boolean(),
  "creator_is_moderator": zod.boolean(),
  "post": zod.object({
  "ap_id": zod.string(),
  "community_id": zod.number(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "locked": zod.boolean(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "sticky": zod.boolean(),
  "instance_sticky": zod.boolean(),
  "title": zod.string(),
  "user_id": zod.number(),
  "alt_text": zod.string().optional(),
  "body": zod.string().optional(),
  "small_thumbnail_url": zod.string().optional(),
  "thumbnail_url": zod.string().optional(),
  "updated": zod.string().optional(),
  "url": zod.string().optional(),
  "image_details": zod.object({
  "width": zod.number().optional(),
  "height": zod.number().optional()
}).optional(),
  "cross_posts": zod.array(zod.object({
  "post_id": zod.number().optional(),
  "reply_count": zod.number().optional(),
  "community_name": zod.string().optional()
})).optional(),
  "post_type": zod.enum(['Link', 'Discussion', 'Image', 'Video', 'Poll', 'Event']),
  "tags": zod.string().nullish(),
  "flair": zod.string().nullish(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish(),
  "event": zod.object({
  "start": zod.string(),
  "end": zod.string().optional(),
  "timezone": zod.string().optional(),
  "max_attendees": zod.number().optional(),
  "participant_count": zod.number().optional(),
  "full": zod.boolean().optional(),
  "online_link": zod.string().nullish(),
  "join_mode": zod.string().optional().describe('free, restricted, external, invite'),
  "external_participation_url": zod.string().nullish(),
  "anonymous_participation": zod.boolean().optional(),
  "online": zod.boolean().optional(),
  "buy_tickets_link": zod.string().nullish(),
  "event_fee_currency": zod.string().optional(),
  "event_fee_amount": zod.number().optional(),
  "location": zod.record(zod.string(), zod.unknown()).nullish().describe('JSON object containing location details')
}).optional(),
  "poll": zod.object({
  "end_poll": zod.string().optional(),
  "mode": zod.enum(['single', 'multiple']).describe('single or multiple - determines whether people can vote for one or multiple options'),
  "local_only": zod.boolean().optional(),
  "latest_vote": zod.string().optional(),
  "choices": zod.array(zod.object({
  "id": zod.number(),
  "choice_text": zod.string(),
  "sort_order": zod.number(),
  "num_votes": zod.number().optional().describe('Value is ignored when creating\/editing a poll')
})).max(putApiAlphaCommentResponseCommentViewPostPollChoicesMax),
  "my_votes": zod.array(zod.number()).optional()
}).optional()
}),
  "saved": zod.boolean(),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending']).describe('Indicates whether auth\'ed user is subscribed to the community this comment is in or not.'),
  "my_vote": zod.number().optional(),
  "can_auth_user_moderate": zod.boolean().optional()
})
})

/**
 * @summary Get / fetch a comment.
 */
export const getApiAlphaCommentQueryParams = zod.object({
  "id": zod.number()
})

export const getApiAlphaCommentResponseCommentViewCreatorExtraFieldsMax = 4;

export const getApiAlphaCommentResponseCommentViewCreatorNoteMax = 50;

export const getApiAlphaCommentResponseCommentViewPostEventMaxAttendeesDefault = 0;export const getApiAlphaCommentResponseCommentViewPostEventParticipantCountDefault = 0;export const getApiAlphaCommentResponseCommentViewPostEventFullDefault = false;export const getApiAlphaCommentResponseCommentViewPostEventAnonymousParticipationDefault = false;export const getApiAlphaCommentResponseCommentViewPostEventOnlineDefault = false;export const getApiAlphaCommentResponseCommentViewPostEventEventFeeAmountDefault = 0;export const getApiAlphaCommentResponseCommentViewPostPollLocalOnlyDefault = false;export const getApiAlphaCommentResponseCommentViewPostPollChoicesItemNumVotesDefault = 0;export const getApiAlphaCommentResponseCommentViewPostPollChoicesMax = 10;



export const getApiAlphaCommentResponse = zod.object({
  "comment_view": zod.object({
  "activity_alert": zod.boolean(),
  "banned_from_community": zod.boolean(),
  "comment": zod.object({
  "ap_id": zod.string(),
  "body": zod.string(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "path": zod.string(),
  "post_id": zod.number(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "user_id": zod.number(),
  "distinguished": zod.boolean().optional(),
  "updated": zod.string().optional(),
  "locked": zod.boolean().optional(),
  "answer": zod.boolean().optional(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish()
}),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "child_count": zod.number(),
  "comment_id": zod.number(),
  "downvotes": zod.number(),
  "published": zod.string(),
  "score": zod.number(),
  "upvotes": zod.number()
}),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(getApiAlphaCommentResponseCommentViewCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(getApiAlphaCommentResponseCommentViewCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "creator_banned_from_community": zod.boolean(),
  "creator_blocked": zod.boolean(),
  "creator_is_admin": zod.boolean(),
  "creator_is_moderator": zod.boolean(),
  "post": zod.object({
  "ap_id": zod.string(),
  "community_id": zod.number(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "locked": zod.boolean(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "sticky": zod.boolean(),
  "instance_sticky": zod.boolean(),
  "title": zod.string(),
  "user_id": zod.number(),
  "alt_text": zod.string().optional(),
  "body": zod.string().optional(),
  "small_thumbnail_url": zod.string().optional(),
  "thumbnail_url": zod.string().optional(),
  "updated": zod.string().optional(),
  "url": zod.string().optional(),
  "image_details": zod.object({
  "width": zod.number().optional(),
  "height": zod.number().optional()
}).optional(),
  "cross_posts": zod.array(zod.object({
  "post_id": zod.number().optional(),
  "reply_count": zod.number().optional(),
  "community_name": zod.string().optional()
})).optional(),
  "post_type": zod.enum(['Link', 'Discussion', 'Image', 'Video', 'Poll', 'Event']),
  "tags": zod.string().nullish(),
  "flair": zod.string().nullish(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish(),
  "event": zod.object({
  "start": zod.string(),
  "end": zod.string().optional(),
  "timezone": zod.string().optional(),
  "max_attendees": zod.number().optional(),
  "participant_count": zod.number().optional(),
  "full": zod.boolean().optional(),
  "online_link": zod.string().nullish(),
  "join_mode": zod.string().optional().describe('free, restricted, external, invite'),
  "external_participation_url": zod.string().nullish(),
  "anonymous_participation": zod.boolean().optional(),
  "online": zod.boolean().optional(),
  "buy_tickets_link": zod.string().nullish(),
  "event_fee_currency": zod.string().optional(),
  "event_fee_amount": zod.number().optional(),
  "location": zod.record(zod.string(), zod.unknown()).nullish().describe('JSON object containing location details')
}).optional(),
  "poll": zod.object({
  "end_poll": zod.string().optional(),
  "mode": zod.enum(['single', 'multiple']).describe('single or multiple - determines whether people can vote for one or multiple options'),
  "local_only": zod.boolean().optional(),
  "latest_vote": zod.string().optional(),
  "choices": zod.array(zod.object({
  "id": zod.number(),
  "choice_text": zod.string(),
  "sort_order": zod.number(),
  "num_votes": zod.number().optional().describe('Value is ignored when creating\/editing a poll')
})).max(getApiAlphaCommentResponseCommentViewPostPollChoicesMax),
  "my_votes": zod.array(zod.number()).optional()
}).optional()
}),
  "saved": zod.boolean(),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending']).describe('Indicates whether auth\'ed user is subscribed to the community this comment is in or not.'),
  "my_vote": zod.number().optional(),
  "can_auth_user_moderate": zod.boolean().optional()
})
})

/**
 * @summary Delete a comment.
 */
export const postApiAlphaCommentDeleteBody = zod.object({
  "comment_id": zod.number(),
  "deleted": zod.boolean()
})

export const postApiAlphaCommentDeleteResponseCommentViewCreatorExtraFieldsMax = 4;

export const postApiAlphaCommentDeleteResponseCommentViewCreatorNoteMax = 50;

export const postApiAlphaCommentDeleteResponseCommentViewPostEventMaxAttendeesDefault = 0;export const postApiAlphaCommentDeleteResponseCommentViewPostEventParticipantCountDefault = 0;export const postApiAlphaCommentDeleteResponseCommentViewPostEventFullDefault = false;export const postApiAlphaCommentDeleteResponseCommentViewPostEventAnonymousParticipationDefault = false;export const postApiAlphaCommentDeleteResponseCommentViewPostEventOnlineDefault = false;export const postApiAlphaCommentDeleteResponseCommentViewPostEventEventFeeAmountDefault = 0;export const postApiAlphaCommentDeleteResponseCommentViewPostPollLocalOnlyDefault = false;export const postApiAlphaCommentDeleteResponseCommentViewPostPollChoicesItemNumVotesDefault = 0;export const postApiAlphaCommentDeleteResponseCommentViewPostPollChoicesMax = 10;



export const postApiAlphaCommentDeleteResponse = zod.object({
  "comment_view": zod.object({
  "activity_alert": zod.boolean(),
  "banned_from_community": zod.boolean(),
  "comment": zod.object({
  "ap_id": zod.string(),
  "body": zod.string(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "path": zod.string(),
  "post_id": zod.number(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "user_id": zod.number(),
  "distinguished": zod.boolean().optional(),
  "updated": zod.string().optional(),
  "locked": zod.boolean().optional(),
  "answer": zod.boolean().optional(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish()
}),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "child_count": zod.number(),
  "comment_id": zod.number(),
  "downvotes": zod.number(),
  "published": zod.string(),
  "score": zod.number(),
  "upvotes": zod.number()
}),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommentDeleteResponseCommentViewCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommentDeleteResponseCommentViewCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "creator_banned_from_community": zod.boolean(),
  "creator_blocked": zod.boolean(),
  "creator_is_admin": zod.boolean(),
  "creator_is_moderator": zod.boolean(),
  "post": zod.object({
  "ap_id": zod.string(),
  "community_id": zod.number(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "locked": zod.boolean(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "sticky": zod.boolean(),
  "instance_sticky": zod.boolean(),
  "title": zod.string(),
  "user_id": zod.number(),
  "alt_text": zod.string().optional(),
  "body": zod.string().optional(),
  "small_thumbnail_url": zod.string().optional(),
  "thumbnail_url": zod.string().optional(),
  "updated": zod.string().optional(),
  "url": zod.string().optional(),
  "image_details": zod.object({
  "width": zod.number().optional(),
  "height": zod.number().optional()
}).optional(),
  "cross_posts": zod.array(zod.object({
  "post_id": zod.number().optional(),
  "reply_count": zod.number().optional(),
  "community_name": zod.string().optional()
})).optional(),
  "post_type": zod.enum(['Link', 'Discussion', 'Image', 'Video', 'Poll', 'Event']),
  "tags": zod.string().nullish(),
  "flair": zod.string().nullish(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish(),
  "event": zod.object({
  "start": zod.string(),
  "end": zod.string().optional(),
  "timezone": zod.string().optional(),
  "max_attendees": zod.number().optional(),
  "participant_count": zod.number().optional(),
  "full": zod.boolean().optional(),
  "online_link": zod.string().nullish(),
  "join_mode": zod.string().optional().describe('free, restricted, external, invite'),
  "external_participation_url": zod.string().nullish(),
  "anonymous_participation": zod.boolean().optional(),
  "online": zod.boolean().optional(),
  "buy_tickets_link": zod.string().nullish(),
  "event_fee_currency": zod.string().optional(),
  "event_fee_amount": zod.number().optional(),
  "location": zod.record(zod.string(), zod.unknown()).nullish().describe('JSON object containing location details')
}).optional(),
  "poll": zod.object({
  "end_poll": zod.string().optional(),
  "mode": zod.enum(['single', 'multiple']).describe('single or multiple - determines whether people can vote for one or multiple options'),
  "local_only": zod.boolean().optional(),
  "latest_vote": zod.string().optional(),
  "choices": zod.array(zod.object({
  "id": zod.number(),
  "choice_text": zod.string(),
  "sort_order": zod.number(),
  "num_votes": zod.number().optional().describe('Value is ignored when creating\/editing a poll')
})).max(postApiAlphaCommentDeleteResponseCommentViewPostPollChoicesMax),
  "my_votes": zod.array(zod.number()).optional()
}).optional()
}),
  "saved": zod.boolean(),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending']).describe('Indicates whether auth\'ed user is subscribed to the community this comment is in or not.'),
  "my_vote": zod.number().optional(),
  "can_auth_user_moderate": zod.boolean().optional()
})
})

/**
 * @summary Report a comment.
 */
export const postApiAlphaCommentReportBodyReportRemoteDefault = true;

export const postApiAlphaCommentReportBody = zod.object({
  "comment_id": zod.number(),
  "reason": zod.string(),
  "description": zod.string().optional(),
  "report_remote": zod.boolean().default(postApiAlphaCommentReportBodyReportRemoteDefault).describe('Also send report to originating instance')
})

export const postApiAlphaCommentReportResponseCommentReportViewCreatorExtraFieldsMax = 4;

export const postApiAlphaCommentReportResponseCommentReportViewCreatorNoteMax = 50;

export const postApiAlphaCommentReportResponseCommentReportViewPostEventMaxAttendeesDefault = 0;export const postApiAlphaCommentReportResponseCommentReportViewPostEventParticipantCountDefault = 0;export const postApiAlphaCommentReportResponseCommentReportViewPostEventFullDefault = false;export const postApiAlphaCommentReportResponseCommentReportViewPostEventAnonymousParticipationDefault = false;export const postApiAlphaCommentReportResponseCommentReportViewPostEventOnlineDefault = false;export const postApiAlphaCommentReportResponseCommentReportViewPostEventEventFeeAmountDefault = 0;export const postApiAlphaCommentReportResponseCommentReportViewPostPollLocalOnlyDefault = false;export const postApiAlphaCommentReportResponseCommentReportViewPostPollChoicesItemNumVotesDefault = 0;export const postApiAlphaCommentReportResponseCommentReportViewPostPollChoicesMax = 10;

export const postApiAlphaCommentReportResponseCommentReportViewCommentCreatorExtraFieldsMax = 4;

export const postApiAlphaCommentReportResponseCommentReportViewCommentCreatorNoteMax = 50;



export const postApiAlphaCommentReportResponse = zod.object({
  "comment_report_view": zod.object({
  "activity_alert": zod.boolean(),
  "banned_from_community": zod.boolean(),
  "comment": zod.object({
  "ap_id": zod.string(),
  "body": zod.string(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "path": zod.string(),
  "post_id": zod.number(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "user_id": zod.number(),
  "distinguished": zod.boolean().optional(),
  "updated": zod.string().optional(),
  "locked": zod.boolean().optional(),
  "answer": zod.boolean().optional(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish()
}),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "child_count": zod.number(),
  "comment_id": zod.number(),
  "downvotes": zod.number(),
  "published": zod.string(),
  "score": zod.number(),
  "upvotes": zod.number()
}),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommentReportResponseCommentReportViewCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommentReportResponseCommentReportViewCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "creator_banned_from_community": zod.boolean(),
  "creator_blocked": zod.boolean(),
  "creator_is_admin": zod.boolean(),
  "creator_is_moderator": zod.boolean(),
  "post": zod.object({
  "ap_id": zod.string(),
  "community_id": zod.number(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "locked": zod.boolean(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "sticky": zod.boolean(),
  "instance_sticky": zod.boolean(),
  "title": zod.string(),
  "user_id": zod.number(),
  "alt_text": zod.string().optional(),
  "body": zod.string().optional(),
  "small_thumbnail_url": zod.string().optional(),
  "thumbnail_url": zod.string().optional(),
  "updated": zod.string().optional(),
  "url": zod.string().optional(),
  "image_details": zod.object({
  "width": zod.number().optional(),
  "height": zod.number().optional()
}).optional(),
  "cross_posts": zod.array(zod.object({
  "post_id": zod.number().optional(),
  "reply_count": zod.number().optional(),
  "community_name": zod.string().optional()
})).optional(),
  "post_type": zod.enum(['Link', 'Discussion', 'Image', 'Video', 'Poll', 'Event']),
  "tags": zod.string().nullish(),
  "flair": zod.string().nullish(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish(),
  "event": zod.object({
  "start": zod.string(),
  "end": zod.string().optional(),
  "timezone": zod.string().optional(),
  "max_attendees": zod.number().optional(),
  "participant_count": zod.number().optional(),
  "full": zod.boolean().optional(),
  "online_link": zod.string().nullish(),
  "join_mode": zod.string().optional().describe('free, restricted, external, invite'),
  "external_participation_url": zod.string().nullish(),
  "anonymous_participation": zod.boolean().optional(),
  "online": zod.boolean().optional(),
  "buy_tickets_link": zod.string().nullish(),
  "event_fee_currency": zod.string().optional(),
  "event_fee_amount": zod.number().optional(),
  "location": zod.record(zod.string(), zod.unknown()).nullish().describe('JSON object containing location details')
}).optional(),
  "poll": zod.object({
  "end_poll": zod.string().optional(),
  "mode": zod.enum(['single', 'multiple']).describe('single or multiple - determines whether people can vote for one or multiple options'),
  "local_only": zod.boolean().optional(),
  "latest_vote": zod.string().optional(),
  "choices": zod.array(zod.object({
  "id": zod.number(),
  "choice_text": zod.string(),
  "sort_order": zod.number(),
  "num_votes": zod.number().optional().describe('Value is ignored when creating\/editing a poll')
})).max(postApiAlphaCommentReportResponseCommentReportViewPostPollChoicesMax),
  "my_votes": zod.array(zod.number()).optional()
}).optional()
}),
  "saved": zod.boolean(),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending']).describe('Indicates whether auth\'ed user is subscribed to the community this comment is in or not.'),
  "my_vote": zod.number().optional(),
  "can_auth_user_moderate": zod.boolean().optional(),
  "comment_report": zod.object({
  "id": zod.number(),
  "creator_id": zod.number(),
  "comment_id": zod.number(),
  "original_comment_text": zod.string().optional(),
  "reason": zod.string().optional(),
  "resolved": zod.boolean(),
  "published": zod.string(),
  "updated": zod.string().optional()
}),
  "comment_creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommentReportResponseCommentReportViewCommentCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommentReportResponseCommentReportViewCommentCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
})
})
})

/**
 * @summary Remove a comment as a moderator.
 */
export const postApiAlphaCommentRemoveBody = zod.object({
  "comment_id": zod.number(),
  "removed": zod.boolean(),
  "reason": zod.string().optional()
})

export const postApiAlphaCommentRemoveResponseCommentViewCreatorExtraFieldsMax = 4;

export const postApiAlphaCommentRemoveResponseCommentViewCreatorNoteMax = 50;

export const postApiAlphaCommentRemoveResponseCommentViewPostEventMaxAttendeesDefault = 0;export const postApiAlphaCommentRemoveResponseCommentViewPostEventParticipantCountDefault = 0;export const postApiAlphaCommentRemoveResponseCommentViewPostEventFullDefault = false;export const postApiAlphaCommentRemoveResponseCommentViewPostEventAnonymousParticipationDefault = false;export const postApiAlphaCommentRemoveResponseCommentViewPostEventOnlineDefault = false;export const postApiAlphaCommentRemoveResponseCommentViewPostEventEventFeeAmountDefault = 0;export const postApiAlphaCommentRemoveResponseCommentViewPostPollLocalOnlyDefault = false;export const postApiAlphaCommentRemoveResponseCommentViewPostPollChoicesItemNumVotesDefault = 0;export const postApiAlphaCommentRemoveResponseCommentViewPostPollChoicesMax = 10;



export const postApiAlphaCommentRemoveResponse = zod.object({
  "comment_view": zod.object({
  "activity_alert": zod.boolean(),
  "banned_from_community": zod.boolean(),
  "comment": zod.object({
  "ap_id": zod.string(),
  "body": zod.string(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "path": zod.string(),
  "post_id": zod.number(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "user_id": zod.number(),
  "distinguished": zod.boolean().optional(),
  "updated": zod.string().optional(),
  "locked": zod.boolean().optional(),
  "answer": zod.boolean().optional(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish()
}),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "child_count": zod.number(),
  "comment_id": zod.number(),
  "downvotes": zod.number(),
  "published": zod.string(),
  "score": zod.number(),
  "upvotes": zod.number()
}),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommentRemoveResponseCommentViewCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommentRemoveResponseCommentViewCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "creator_banned_from_community": zod.boolean(),
  "creator_blocked": zod.boolean(),
  "creator_is_admin": zod.boolean(),
  "creator_is_moderator": zod.boolean(),
  "post": zod.object({
  "ap_id": zod.string(),
  "community_id": zod.number(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "locked": zod.boolean(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "sticky": zod.boolean(),
  "instance_sticky": zod.boolean(),
  "title": zod.string(),
  "user_id": zod.number(),
  "alt_text": zod.string().optional(),
  "body": zod.string().optional(),
  "small_thumbnail_url": zod.string().optional(),
  "thumbnail_url": zod.string().optional(),
  "updated": zod.string().optional(),
  "url": zod.string().optional(),
  "image_details": zod.object({
  "width": zod.number().optional(),
  "height": zod.number().optional()
}).optional(),
  "cross_posts": zod.array(zod.object({
  "post_id": zod.number().optional(),
  "reply_count": zod.number().optional(),
  "community_name": zod.string().optional()
})).optional(),
  "post_type": zod.enum(['Link', 'Discussion', 'Image', 'Video', 'Poll', 'Event']),
  "tags": zod.string().nullish(),
  "flair": zod.string().nullish(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish(),
  "event": zod.object({
  "start": zod.string(),
  "end": zod.string().optional(),
  "timezone": zod.string().optional(),
  "max_attendees": zod.number().optional(),
  "participant_count": zod.number().optional(),
  "full": zod.boolean().optional(),
  "online_link": zod.string().nullish(),
  "join_mode": zod.string().optional().describe('free, restricted, external, invite'),
  "external_participation_url": zod.string().nullish(),
  "anonymous_participation": zod.boolean().optional(),
  "online": zod.boolean().optional(),
  "buy_tickets_link": zod.string().nullish(),
  "event_fee_currency": zod.string().optional(),
  "event_fee_amount": zod.number().optional(),
  "location": zod.record(zod.string(), zod.unknown()).nullish().describe('JSON object containing location details')
}).optional(),
  "poll": zod.object({
  "end_poll": zod.string().optional(),
  "mode": zod.enum(['single', 'multiple']).describe('single or multiple - determines whether people can vote for one or multiple options'),
  "local_only": zod.boolean().optional(),
  "latest_vote": zod.string().optional(),
  "choices": zod.array(zod.object({
  "id": zod.number(),
  "choice_text": zod.string(),
  "sort_order": zod.number(),
  "num_votes": zod.number().optional().describe('Value is ignored when creating\/editing a poll')
})).max(postApiAlphaCommentRemoveResponseCommentViewPostPollChoicesMax),
  "my_votes": zod.array(zod.number()).optional()
}).optional()
}),
  "saved": zod.boolean(),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending']).describe('Indicates whether auth\'ed user is subscribed to the community this comment is in or not.'),
  "my_vote": zod.number().optional(),
  "can_auth_user_moderate": zod.boolean().optional()
})
})

/**
 * @summary Mark a comment reply as read.
 */
export const postApiAlphaCommentMarkAsReadBody = zod.object({
  "comment_reply_id": zod.number(),
  "read": zod.boolean()
})

export const postApiAlphaCommentMarkAsReadResponseCommentReplyViewCreatorExtraFieldsMax = 4;

export const postApiAlphaCommentMarkAsReadResponseCommentReplyViewCreatorNoteMax = 50;

export const postApiAlphaCommentMarkAsReadResponseCommentReplyViewPostEventMaxAttendeesDefault = 0;export const postApiAlphaCommentMarkAsReadResponseCommentReplyViewPostEventParticipantCountDefault = 0;export const postApiAlphaCommentMarkAsReadResponseCommentReplyViewPostEventFullDefault = false;export const postApiAlphaCommentMarkAsReadResponseCommentReplyViewPostEventAnonymousParticipationDefault = false;export const postApiAlphaCommentMarkAsReadResponseCommentReplyViewPostEventOnlineDefault = false;export const postApiAlphaCommentMarkAsReadResponseCommentReplyViewPostEventEventFeeAmountDefault = 0;export const postApiAlphaCommentMarkAsReadResponseCommentReplyViewPostPollLocalOnlyDefault = false;export const postApiAlphaCommentMarkAsReadResponseCommentReplyViewPostPollChoicesItemNumVotesDefault = 0;export const postApiAlphaCommentMarkAsReadResponseCommentReplyViewPostPollChoicesMax = 10;

export const postApiAlphaCommentMarkAsReadResponseCommentReplyViewRecipientExtraFieldsMax = 4;

export const postApiAlphaCommentMarkAsReadResponseCommentReplyViewRecipientNoteMax = 50;



export const postApiAlphaCommentMarkAsReadResponse = zod.object({
  "comment_reply_view": zod.object({
  "activity_alert": zod.boolean(),
  "comment": zod.object({
  "ap_id": zod.string(),
  "body": zod.string(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "path": zod.string(),
  "post_id": zod.number(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "user_id": zod.number(),
  "distinguished": zod.boolean().optional(),
  "updated": zod.string().optional(),
  "locked": zod.boolean().optional(),
  "answer": zod.boolean().optional(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish()
}),
  "comment_reply": zod.object({
  "id": zod.number(),
  "comment_id": zod.number(),
  "published": zod.string(),
  "read": zod.boolean(),
  "recipient_id": zod.number()
}),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "child_count": zod.number(),
  "comment_id": zod.number(),
  "downvotes": zod.number(),
  "published": zod.string(),
  "score": zod.number(),
  "upvotes": zod.number()
}),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommentMarkAsReadResponseCommentReplyViewCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommentMarkAsReadResponseCommentReplyViewCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "creator_banned_from_community": zod.boolean(),
  "creator_blocked": zod.boolean(),
  "creator_is_admin": zod.boolean(),
  "creator_is_moderator": zod.boolean(),
  "my_vote": zod.number(),
  "post": zod.object({
  "ap_id": zod.string(),
  "community_id": zod.number(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "locked": zod.boolean(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "sticky": zod.boolean(),
  "instance_sticky": zod.boolean(),
  "title": zod.string(),
  "user_id": zod.number(),
  "alt_text": zod.string().optional(),
  "body": zod.string().optional(),
  "small_thumbnail_url": zod.string().optional(),
  "thumbnail_url": zod.string().optional(),
  "updated": zod.string().optional(),
  "url": zod.string().optional(),
  "image_details": zod.object({
  "width": zod.number().optional(),
  "height": zod.number().optional()
}).optional(),
  "cross_posts": zod.array(zod.object({
  "post_id": zod.number().optional(),
  "reply_count": zod.number().optional(),
  "community_name": zod.string().optional()
})).optional(),
  "post_type": zod.enum(['Link', 'Discussion', 'Image', 'Video', 'Poll', 'Event']),
  "tags": zod.string().nullish(),
  "flair": zod.string().nullish(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish(),
  "event": zod.object({
  "start": zod.string(),
  "end": zod.string().optional(),
  "timezone": zod.string().optional(),
  "max_attendees": zod.number().optional(),
  "participant_count": zod.number().optional(),
  "full": zod.boolean().optional(),
  "online_link": zod.string().nullish(),
  "join_mode": zod.string().optional().describe('free, restricted, external, invite'),
  "external_participation_url": zod.string().nullish(),
  "anonymous_participation": zod.boolean().optional(),
  "online": zod.boolean().optional(),
  "buy_tickets_link": zod.string().nullish(),
  "event_fee_currency": zod.string().optional(),
  "event_fee_amount": zod.number().optional(),
  "location": zod.record(zod.string(), zod.unknown()).nullish().describe('JSON object containing location details')
}).optional(),
  "poll": zod.object({
  "end_poll": zod.string().optional(),
  "mode": zod.enum(['single', 'multiple']).describe('single or multiple - determines whether people can vote for one or multiple options'),
  "local_only": zod.boolean().optional(),
  "latest_vote": zod.string().optional(),
  "choices": zod.array(zod.object({
  "id": zod.number(),
  "choice_text": zod.string(),
  "sort_order": zod.number(),
  "num_votes": zod.number().optional().describe('Value is ignored when creating\/editing a poll')
})).max(postApiAlphaCommentMarkAsReadResponseCommentReplyViewPostPollChoicesMax),
  "my_votes": zod.array(zod.number()).optional()
}).optional()
}),
  "recipient": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommentMarkAsReadResponseCommentReplyViewRecipientExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommentMarkAsReadResponseCommentReplyViewRecipientNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "saved": zod.boolean(),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending'])
})
})

/**
 * @summary Mark a comment as the preferred answer to a question.
 */
export const postApiAlphaCommentMarkAsAnswerBody = zod.object({
  "comment_reply_id": zod.number(),
  "answer": zod.boolean()
})

export const postApiAlphaCommentMarkAsAnswerResponseCommentReplyViewCreatorExtraFieldsMax = 4;

export const postApiAlphaCommentMarkAsAnswerResponseCommentReplyViewCreatorNoteMax = 50;

export const postApiAlphaCommentMarkAsAnswerResponseCommentReplyViewPostEventMaxAttendeesDefault = 0;export const postApiAlphaCommentMarkAsAnswerResponseCommentReplyViewPostEventParticipantCountDefault = 0;export const postApiAlphaCommentMarkAsAnswerResponseCommentReplyViewPostEventFullDefault = false;export const postApiAlphaCommentMarkAsAnswerResponseCommentReplyViewPostEventAnonymousParticipationDefault = false;export const postApiAlphaCommentMarkAsAnswerResponseCommentReplyViewPostEventOnlineDefault = false;export const postApiAlphaCommentMarkAsAnswerResponseCommentReplyViewPostEventEventFeeAmountDefault = 0;export const postApiAlphaCommentMarkAsAnswerResponseCommentReplyViewPostPollLocalOnlyDefault = false;export const postApiAlphaCommentMarkAsAnswerResponseCommentReplyViewPostPollChoicesItemNumVotesDefault = 0;export const postApiAlphaCommentMarkAsAnswerResponseCommentReplyViewPostPollChoicesMax = 10;

export const postApiAlphaCommentMarkAsAnswerResponseCommentReplyViewRecipientExtraFieldsMax = 4;

export const postApiAlphaCommentMarkAsAnswerResponseCommentReplyViewRecipientNoteMax = 50;



export const postApiAlphaCommentMarkAsAnswerResponse = zod.object({
  "comment_reply_view": zod.object({
  "activity_alert": zod.boolean(),
  "comment": zod.object({
  "ap_id": zod.string(),
  "body": zod.string(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "path": zod.string(),
  "post_id": zod.number(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "user_id": zod.number(),
  "distinguished": zod.boolean().optional(),
  "updated": zod.string().optional(),
  "locked": zod.boolean().optional(),
  "answer": zod.boolean().optional(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish()
}),
  "comment_reply": zod.object({
  "id": zod.number(),
  "comment_id": zod.number(),
  "published": zod.string(),
  "read": zod.boolean(),
  "recipient_id": zod.number()
}),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "child_count": zod.number(),
  "comment_id": zod.number(),
  "downvotes": zod.number(),
  "published": zod.string(),
  "score": zod.number(),
  "upvotes": zod.number()
}),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommentMarkAsAnswerResponseCommentReplyViewCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommentMarkAsAnswerResponseCommentReplyViewCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "creator_banned_from_community": zod.boolean(),
  "creator_blocked": zod.boolean(),
  "creator_is_admin": zod.boolean(),
  "creator_is_moderator": zod.boolean(),
  "my_vote": zod.number(),
  "post": zod.object({
  "ap_id": zod.string(),
  "community_id": zod.number(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "locked": zod.boolean(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "sticky": zod.boolean(),
  "instance_sticky": zod.boolean(),
  "title": zod.string(),
  "user_id": zod.number(),
  "alt_text": zod.string().optional(),
  "body": zod.string().optional(),
  "small_thumbnail_url": zod.string().optional(),
  "thumbnail_url": zod.string().optional(),
  "updated": zod.string().optional(),
  "url": zod.string().optional(),
  "image_details": zod.object({
  "width": zod.number().optional(),
  "height": zod.number().optional()
}).optional(),
  "cross_posts": zod.array(zod.object({
  "post_id": zod.number().optional(),
  "reply_count": zod.number().optional(),
  "community_name": zod.string().optional()
})).optional(),
  "post_type": zod.enum(['Link', 'Discussion', 'Image', 'Video', 'Poll', 'Event']),
  "tags": zod.string().nullish(),
  "flair": zod.string().nullish(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish(),
  "event": zod.object({
  "start": zod.string(),
  "end": zod.string().optional(),
  "timezone": zod.string().optional(),
  "max_attendees": zod.number().optional(),
  "participant_count": zod.number().optional(),
  "full": zod.boolean().optional(),
  "online_link": zod.string().nullish(),
  "join_mode": zod.string().optional().describe('free, restricted, external, invite'),
  "external_participation_url": zod.string().nullish(),
  "anonymous_participation": zod.boolean().optional(),
  "online": zod.boolean().optional(),
  "buy_tickets_link": zod.string().nullish(),
  "event_fee_currency": zod.string().optional(),
  "event_fee_amount": zod.number().optional(),
  "location": zod.record(zod.string(), zod.unknown()).nullish().describe('JSON object containing location details')
}).optional(),
  "poll": zod.object({
  "end_poll": zod.string().optional(),
  "mode": zod.enum(['single', 'multiple']).describe('single or multiple - determines whether people can vote for one or multiple options'),
  "local_only": zod.boolean().optional(),
  "latest_vote": zod.string().optional(),
  "choices": zod.array(zod.object({
  "id": zod.number(),
  "choice_text": zod.string(),
  "sort_order": zod.number(),
  "num_votes": zod.number().optional().describe('Value is ignored when creating\/editing a poll')
})).max(postApiAlphaCommentMarkAsAnswerResponseCommentReplyViewPostPollChoicesMax),
  "my_votes": zod.array(zod.number()).optional()
}).optional()
}),
  "recipient": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommentMarkAsAnswerResponseCommentReplyViewRecipientExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommentMarkAsAnswerResponseCommentReplyViewRecipientNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "saved": zod.boolean(),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending'])
})
})

/**
 * @summary Lock a comment chain as a moderator.
 */
export const postApiAlphaCommentLockBody = zod.object({
  "comment_id": zod.number(),
  "locked": zod.boolean()
})

export const postApiAlphaCommentLockResponseCommentViewCreatorExtraFieldsMax = 4;

export const postApiAlphaCommentLockResponseCommentViewCreatorNoteMax = 50;

export const postApiAlphaCommentLockResponseCommentViewPostEventMaxAttendeesDefault = 0;export const postApiAlphaCommentLockResponseCommentViewPostEventParticipantCountDefault = 0;export const postApiAlphaCommentLockResponseCommentViewPostEventFullDefault = false;export const postApiAlphaCommentLockResponseCommentViewPostEventAnonymousParticipationDefault = false;export const postApiAlphaCommentLockResponseCommentViewPostEventOnlineDefault = false;export const postApiAlphaCommentLockResponseCommentViewPostEventEventFeeAmountDefault = 0;export const postApiAlphaCommentLockResponseCommentViewPostPollLocalOnlyDefault = false;export const postApiAlphaCommentLockResponseCommentViewPostPollChoicesItemNumVotesDefault = 0;export const postApiAlphaCommentLockResponseCommentViewPostPollChoicesMax = 10;



export const postApiAlphaCommentLockResponse = zod.object({
  "comment_view": zod.object({
  "activity_alert": zod.boolean(),
  "banned_from_community": zod.boolean(),
  "comment": zod.object({
  "ap_id": zod.string(),
  "body": zod.string(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "path": zod.string(),
  "post_id": zod.number(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "user_id": zod.number(),
  "distinguished": zod.boolean().optional(),
  "updated": zod.string().optional(),
  "locked": zod.boolean().optional(),
  "answer": zod.boolean().optional(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish()
}),
  "community": zod.object({
  "actor_id": zod.string(),
  "ap_domain": zod.string().optional(),
  "deleted": zod.boolean(),
  "hidden": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "name": zod.string(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "restricted_to_mods": zod.boolean(),
  "title": zod.string(),
  "banned": zod.boolean().optional(),
  "question_answer": zod.boolean().optional(),
  "banner": zod.string().nullish(),
  "description": zod.string().optional(),
  "icon": zod.string().nullish(),
  "posting_warning": zod.string().nullish(),
  "updated": zod.string().optional()
}),
  "counts": zod.object({
  "child_count": zod.number(),
  "comment_id": zod.number(),
  "downvotes": zod.number(),
  "published": zod.string(),
  "score": zod.number(),
  "upvotes": zod.number()
}),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(postApiAlphaCommentLockResponseCommentViewCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(postApiAlphaCommentLockResponseCommentViewCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
}),
  "creator_banned_from_community": zod.boolean(),
  "creator_blocked": zod.boolean(),
  "creator_is_admin": zod.boolean(),
  "creator_is_moderator": zod.boolean(),
  "post": zod.object({
  "ap_id": zod.string(),
  "community_id": zod.number(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "language_id": zod.number(),
  "local": zod.boolean(),
  "locked": zod.boolean(),
  "nsfw": zod.boolean(),
  "ai_generated": zod.boolean(),
  "published": zod.string(),
  "removed": zod.boolean(),
  "sticky": zod.boolean(),
  "instance_sticky": zod.boolean(),
  "title": zod.string(),
  "user_id": zod.number(),
  "alt_text": zod.string().optional(),
  "body": zod.string().optional(),
  "small_thumbnail_url": zod.string().optional(),
  "thumbnail_url": zod.string().optional(),
  "updated": zod.string().optional(),
  "url": zod.string().optional(),
  "image_details": zod.object({
  "width": zod.number().optional(),
  "height": zod.number().optional()
}).optional(),
  "cross_posts": zod.array(zod.object({
  "post_id": zod.number().optional(),
  "reply_count": zod.number().optional(),
  "community_name": zod.string().optional()
})).optional(),
  "post_type": zod.enum(['Link', 'Discussion', 'Image', 'Video', 'Poll', 'Event']),
  "tags": zod.string().nullish(),
  "flair": zod.string().nullish(),
  "emoji_reactions": zod.array(zod.object({
  "url": zod.string().nullish(),
  "token": zod.string().optional(),
  "authors": zod.array(zod.string()).optional(),
  "count": zod.number().optional()
})).nullish(),
  "event": zod.object({
  "start": zod.string(),
  "end": zod.string().optional(),
  "timezone": zod.string().optional(),
  "max_attendees": zod.number().optional(),
  "participant_count": zod.number().optional(),
  "full": zod.boolean().optional(),
  "online_link": zod.string().nullish(),
  "join_mode": zod.string().optional().describe('free, restricted, external, invite'),
  "external_participation_url": zod.string().nullish(),
  "anonymous_participation": zod.boolean().optional(),
  "online": zod.boolean().optional(),
  "buy_tickets_link": zod.string().nullish(),
  "event_fee_currency": zod.string().optional(),
  "event_fee_amount": zod.number().optional(),
  "location": zod.record(zod.string(), zod.unknown()).nullish().describe('JSON object containing location details')
}).optional(),
  "poll": zod.object({
  "end_poll": zod.string().optional(),
  "mode": zod.enum(['single', 'multiple']).describe('single or multiple - determines whether people can vote for one or multiple options'),
  "local_only": zod.boolean().optional(),
  "latest_vote": zod.string().optional(),
  "choices": zod.array(zod.object({
  "id": zod.number(),
  "choice_text": zod.string(),
  "sort_order": zod.number(),
  "num_votes": zod.number().optional().describe('Value is ignored when creating\/editing a poll')
})).max(postApiAlphaCommentLockResponseCommentViewPostPollChoicesMax),
  "my_votes": zod.array(zod.number()).optional()
}).optional()
}),
  "saved": zod.boolean(),
  "subscribed": zod.enum(['Subscribed', 'NotSubscribed', 'Pending']).describe('Indicates whether auth\'ed user is subscribed to the community this comment is in or not.'),
  "my_vote": zod.number().optional(),
  "can_auth_user_moderate": zod.boolean().optional()
})
})

/**
 * @summary View comment votes as a moderator.
 */
export const getApiAlphaCommentLikeListQueryPageDefault = 1;export const getApiAlphaCommentLikeListQueryLimitDefault = 50;

export const getApiAlphaCommentLikeListQueryParams = zod.object({
  "comment_id": zod.number(),
  "page": zod.number().default(getApiAlphaCommentLikeListQueryPageDefault),
  "limit": zod.number().default(getApiAlphaCommentLikeListQueryLimitDefault)
})

export const getApiAlphaCommentLikeListResponseCommentLikesItemCreatorExtraFieldsMax = 4;

export const getApiAlphaCommentLikeListResponseCommentLikesItemCreatorNoteMax = 50;



export const getApiAlphaCommentLikeListResponse = zod.object({
  "comment_likes": zod.array(zod.object({
  "score": zod.number(),
  "creator_banned_from_community": zod.boolean(),
  "creator_banned": zod.boolean(),
  "creator": zod.object({
  "actor_id": zod.string(),
  "banned": zod.boolean(),
  "bot": zod.boolean(),
  "deleted": zod.boolean(),
  "id": zod.number(),
  "instance_id": zod.number(),
  "local": zod.boolean(),
  "user_name": zod.string(),
  "about": zod.string().optional(),
  "about_html": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "banner": zod.string().nullish(),
  "extra_fields": zod.array(zod.object({
  "id": zod.number(),
  "label": zod.string(),
  "text": zod.string()
})).max(getApiAlphaCommentLikeListResponseCommentLikesItemCreatorExtraFieldsMax).optional(),
  "note": zod.string().max(getApiAlphaCommentLikeListResponseCommentLikesItemCreatorNoteMax).optional(),
  "flair": zod.string().optional(),
  "published": zod.string().optional(),
  "title": zod.string().nullish()
})
})),
  "next_page": zod.string().nullish()
})

